[[comments]]
author = "Иεşċąfě &иεmö"
date = "2008-08-25T12:24:00+00:00"
text = "طيب هي الدنيا كانت عامله ازاي ئبل الكاتشب؟ سؤال مهم يطرح نفسه و أوي تؤلي زي ما كنت ئبل المايونيز"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/14635860789423949153"
comment_url = "https://mos3abof.blogspot.com/2008/08/blog-post_25.html?showComment=1219667040000#c5041634624340970980"

[[comments]]
author = "Amr"
date = "2008-08-25T12:56:00+00:00"
text = "كانت عادية، مكانش فيه احتياج قوي للبيبسي لأنه مكانش موجود وقتها..."
avatar_url = "http://www.arttoheart.ca/newimages/blueflrs.jpg"
profile_url = "https://www.blogger.com/profile/03741243192561256269"
comment_url = "https://mos3abof.blogspot.com/2008/08/blog-post_25.html?showComment=1219668960000#c1734113439379917532"

[[comments]]
author = "Unknown"
date = "2008-08-25T13:53:00+00:00"
text = "الله يرحم ايام التمر هندي والسوبيا والزيت الحار   D:"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/09154367994040376200"
comment_url = "https://mos3abof.blogspot.com/2008/08/blog-post_25.html?showComment=1219672380000#c3533494751550897435"

[[comments]]
author = "Anonymous"
date = "2008-08-25T16:38:00+00:00"
text = "CRبظبط زى ما كانت قبل النسكافية"
comment_url = "https://mos3abof.blogspot.com/2008/08/blog-post_25.html?showComment=1219682280000#c3405298393101586240"

[[comments]]
author = "Salma Amer"
date = "2008-08-26T16:32:00+00:00"
text = "والبرجر والبطاطس المحمرة  كانوا بيتاكلوا كدة  سادة :( من غير كاتشب ازاي <br />هو يجوز <br />الحمد لله ان دي كارت مات كان انهار من السؤال دة من كتر ما هو صعب<br /><br />صباح التهيس يا مصاعيبو :)"
avatar_url = "http://farm2.static.flickr.com/1132/1365681113_f20faceeb5.jpg?v=0"
profile_url = "https://www.blogger.com/profile/08716194696950096714"
comment_url = "https://mos3abof.blogspot.com/2008/08/blog-post_25.html?showComment=1219768320000#c4099892461611490965"

[[comments]]
author = "حزينه"
date = "2008-08-27T15:12:00+00:00"
text = "ياااه<br />طيب الدنيا كانت عامله ازاى<br />قبل السوبر ماركت كله<br /><br /><br />زى ما دنيتنا دى فيها حاجات مش نقدر نستغنى عنها<br />الدنيا اللى جايه حيكون فيها حاجات<br />مش عارفين ازاى مش كانت موجودة<br /><br />وعجبى<br /><br /><br />حزينه"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEheLKcurBdg8be_diNdqTL61Ri7aPIMDfMRn4LLe5eBXkVhdWQeGkyFVL2NdkAwVbhHg1_OGYxOwW4Mk1aIU415s197Gi-JTdVFTsYUMzqoL8AK8ZGGZSmBAv9nVdOA82s/s220/gothic75[1].gif"
profile_url = "https://www.blogger.com/profile/16606949933826841309"
comment_url = "https://mos3abof.blogspot.com/2008/08/blog-post_25.html?showComment=1219849920000#c4928082792669084277"

[[comments]]
author = "Mony The Angel"
date = "2008-08-28T05:49:00+00:00"
text = "la2 7elwa bgad lool"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjj4h6hlbKyUklJB5J_QeHmZidZ8mEHO-s5lWgxcP3qUEQSPg4AS0GkKHyrjWHC4Z5y2O3vBW2OY7WPf-cZ0PSVMC-DcEJ6cu6SRYKhpVq1jh6S9ve07RM4o8WgdU_8rxE/s220/mine...jpg"
profile_url = "https://www.blogger.com/profile/02273268851121458996"
comment_url = "https://mos3abof.blogspot.com/2008/08/blog-post_25.html?showComment=1219902540000#c6780649508165341563"

[[comments]]
author = "الحلم العربي"
date = "2008-08-28T11:05:00+00:00"
text = "يا عيني هو الjunk food  اللى عمل في الناس كده<br />ربنا يتوب علينا منه"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjTdgiumpfKeU2naMdOAloE5M1oaYUxfArfOm-cYGHKhHod2DcWaAVebA6VKkbv9pk9uWp_Z-NnV5w2gnJ4EA-IYjm_5-fcg71JsKExv1ITSlGWrTF8vM3eDe4tS8_NRSM/s220/strang3.JPG"
profile_url = "https://www.blogger.com/profile/08895879839574889127"
comment_url = "https://mos3abof.blogspot.com/2008/08/blog-post_25.html?showComment=1219921500000#c1698653286184444442"

[[comments]]
author = "MarwaAshraf"
date = "2008-09-03T14:05:00+00:00"
text = "عارف أكتر حاجة عجبتني ايه.. كلمة وغودي دي.. دخلت دماغي أوي"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/12117806503113618382"
comment_url = "https://mos3abof.blogspot.com/2008/08/blog-post_25.html?showComment=1220450700000#c5287569279297562865"
