[[comments]]
author = "محمد السيد..مش حاسكت"
date = "2009-01-20T22:19:00+00:00"
text = "إنسان إنسان الصراحة ....<br /><br />حاجة ده شبه اشعار قيس ... وجميل ... وعنترة ...<br />حاجة لا تتوصف ولا تتحكي ,,, ولا ممكن تتسمع كمان ...<br /><br />دي تتحس وبس .... وبسسسسسس<br /><br /><br />ربنا يصبرك يابنتي ....<br />يااااااااااااااااااااااااارب"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/15123433931771567833"
comment_url = "https://mos3abof.blogspot.com/2009/01/blog-post_20.html?showComment=1232489940000#c9212507523751188721"

[[comments]]
author = "Amira Qassim"
date = "2009-01-20T22:25:00+00:00"
text = ":$<br />مصعب ..<br />ربنا يخليك ليا يارب، ويجي اليوم الي نكون فيه في بيت واحد، ونفضل كده على طول <br />وعاوزة أقولك إني مش محتاجة حاجة بعد الكلمة دي ..<br />ومن مكاني هذا أحب أقولك <br />           ³y ²x  = ³(1­ ²y +²x)"
avatar_url = "http://img107.imageshack.us/img107/712/ice36pd7.jpg"
profile_url = "https://www.blogger.com/profile/08351482421774299913"
comment_url = "https://mos3abof.blogspot.com/2009/01/blog-post_20.html?showComment=1232490300000#c706931224915707771"

[[comments]]
author = "Amimi Houssainy"
date = "2009-01-21T02:09:00+00:00"
text = "ربنا يخليكوا لبعضكم، يا رب...بجد انتوا اسعد زوجين شفتهم في حياتي، عقبا لنا احنا كمان يا صاحبي...ادع لنا يا مصعب  انت كمان، عشان قربت التحق بيك في القفص الذهبي، حقيقي...مبروك...مبروك...مبروك...مبروك يا مصعب."
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgZ5U4WlzUss0uPIk6CIWOP39PIGRIka0M7X7oxQFac3IA96TWm6eSkn9diM-POEGc0GEEz-HFkLZbr4bOmskrn3xWyOUmDVdCHlqDBPy-seDBJISTCwtdUdRokxve19_M/s220/coustime_album.jpg"
profile_url = "https://www.blogger.com/profile/11706534749857063059"
comment_url = "https://mos3abof.blogspot.com/2009/01/blog-post_20.html?showComment=1232503740000#c3917687766700273240"

[[comments]]
author = "menSh"
date = "2009-01-21T12:13:00+00:00"
text = "هي الفكرة بس إن  x (x-1) = x^2-x\\,. <br /><br />يعني لو (x + 1)^2 = 2x^2 + x + 1\\, كان ماشي!<br /><br />بس يللا.. معلش.. هداكما الله ووفقكما إلى ما يرضاه.. آمين :)"
avatar_url = "http://photos1.blogger.com/blogger/4938/2050/1600/am.jpg"
profile_url = "https://www.blogger.com/profile/14221308254991337821"
comment_url = "https://mos3abof.blogspot.com/2009/01/blog-post_20.html?showComment=1232539980000#c2794297879522072631"

[[comments]]
author = "Unknown"
date = "2009-01-21T12:13:00.001000+00:00"
text = "مصعب باشا<br />x + Y = 2(x+y)-2x+x.y<br />مساء الحنان"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/09154367994040376200"
comment_url = "https://mos3abof.blogspot.com/2009/01/blog-post_20.html?showComment=1232539980001#c2652570596251030149"

[[comments]]
author = "أحمد الدريني"
date = "2009-01-21T12:18:00+00:00"
text = "جمهورية \"ناش\""
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/17300680267091030312"
comment_url = "https://mos3abof.blogspot.com/2009/01/blog-post_20.html?showComment=1232540280000#c4603399408572384306"

[[comments]]
author = "moon"
date = "2009-01-21T17:09:00+00:00"
text = "loooooooooool<br />aham 7aga ennoko ento el both fahmin :)"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/06613187847365225877"
comment_url = "https://mos3abof.blogspot.com/2009/01/blog-post_20.html?showComment=1232557740000#c3421375364978933528"

[[comments]]
author = "Amr"
date = "2009-01-21T17:13:00+00:00"
text = "أحب أقول <br /><br />èpf`fçfpeçÑËïÑÔ"
avatar_url = "http://www.arttoheart.ca/newimages/blueflrs.jpg"
profile_url = "https://www.blogger.com/profile/03741243192561256269"
comment_url = "https://mos3abof.blogspot.com/2009/01/blog-post_20.html?showComment=1232557980000#c2496051537310378884"

[[comments]]
author = "Anonymous"
date = "2009-01-21T17:19:00+00:00"
text = "مصعب و أميرة في نعيم!!"
comment_url = "https://mos3abof.blogspot.com/2009/01/blog-post_20.html?showComment=1232558340000#c8496815832766175947"

[[comments]]
author = "Anonymous"
date = "2009-01-22T03:48:00+00:00"
text = "أزال أحد مشرفي المدونة هذا التعليق."
comment_url = "https://mos3abof.blogspot.com/2009/01/blog-post_20.html?showComment=1232596080000#c2258025001368335158"

[[comments]]
author = "روح"
date = "2009-01-27T23:58:00+00:00"
text = "ربنا يكرمكم ويوفقكم<br />تقبلوا خاللص تحياتي<br />ومنتظرة الزيارة"
avatar_url = "http://redondowriter.typepad.com/photos/uncategorized/268573778_a71bfed930.jpg"
profile_url = "https://www.blogger.com/profile/08902136818874003625"
comment_url = "https://mos3abof.blogspot.com/2009/01/blog-post_20.html?showComment=1233100680000#c3097512862913843527"

[[comments]]
author = "Anonymous"
date = "2009-02-10T18:56:00+00:00"
text = "الله يوفقك<br />هذه مدونة جميله<br />و سأواكب على قرائتها بإذن الله. تقبل تعليقاتي و تحياتي :)<br /><br />كنت أرغب عمل تبادل نصي مع هذه المدونة الجميله مع منتداي<br />http://7ama2i.com/forums/<br />منتظر ردك على بريدي<br />dito0o@yahoo.com<br /><br />أرجو حذف إيميلي بعد الموافقه على التعليق :)"
comment_url = "https://mos3abof.blogspot.com/2009/01/blog-post_20.html?showComment=1234292160000#c1929709947201197315"

[[comments]]
author = "الحلم العربي"
date = "2009-02-11T08:24:00+00:00"
text = "ايوة انا بردو كنت بقول واحد عبقري زيك لازم يحب بطريقة مختلفة<br />هههههههههههه<br />ربنا يكرمكم و يتمم لكم بخير يا رب<br />و تفضلزا تحلوا في المعادلات دي مع بعض طول عمركم <br />:))))"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjTdgiumpfKeU2naMdOAloE5M1oaYUxfArfOm-cYGHKhHod2DcWaAVebA6VKkbv9pk9uWp_Z-NnV5w2gnJ4EA-IYjm_5-fcg71JsKExv1ITSlGWrTF8vM3eDe4tS8_NRSM/s220/strang3.JPG"
profile_url = "https://www.blogger.com/profile/08895879839574889127"
comment_url = "https://mos3abof.blogspot.com/2009/01/blog-post_20.html?showComment=1234340640000#c7917733621021958374"
