[[comments]]
author = "Adham Khairy"
date = "2006-11-06T08:15:00.000+01:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgo0UdE5PSPM0pmQEDomQT-e8QjOyEMAY2oN_nyFFZ0DyHnFgXIOo3RvzzJfkbjn-S9dVqb9gCTK1w8N3UJGIkHIDzee3_dsegXRdaVQi7Wx9uwxFVejOATG86smjalQQ/s151/DSC00109.JPG"
profile_url = "https://www.blogger.com/profile/03004041454920220904"
comment_url = "https://mos3abof.blogspot.com/2006/02/blog-post_09.html?showComment=1162797300000#c3078733489139963316"
text = "I've always wanted to visit the \"lost cities\" of Egypt, but now after I read this post, I gotta!!!<br /><br />Actually, I think that I might live there too, but how was the weather? cause according to mahmoud el-sa'adani it is very hot, or in his own words \"qina 3athab al nar\"!!!"
