[[comments]]
author = "We2am"
date = "2008-09-12T02:12:00+00:00"
text = "oh my god! :S<br />msh moshkela eltonaa..yom sa3b msh 7kaya..enma est2altk???!!!<br />i think u have a thing to tell me :S"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhQcQ1ZEVto0d3Q-8SYrlhPe65gtdb7vieD2O9VTjley8Ol9gRSSIxfYCsbogR3Vwo_4gVGfgbPaXcMMYxpPYMmGgitzKr2RN8hp4O1ZV_ezx9D2Wqd3AhCUjMKrXUByu0/s113/14803259_10154014513627023_722172126_o.jpg"
profile_url = "https://www.blogger.com/profile/11798083370261251218"
comment_url = "https://mos3abof.blogspot.com/2008/09/blog-post.html?showComment=1221185520000#c2980390713504844365"

[[comments]]
author = "Omar"
date = "2008-09-12T02:27:00+00:00"
text = "زي ما تتزحلق على دربزين كله امواس وتقع في جردل كلونيا"
avatar_url = "http://1.bp.blogspot.com/_uU6aLT1vZs0/Sha7cwlVWFI/AAAAAAAAAUI/2a29l9P2ke4/S220/Family+(1).jpg"
profile_url = "https://www.blogger.com/profile/10164006741123254135"
comment_url = "https://mos3abof.blogspot.com/2008/09/blog-post.html?showComment=1221186420000#c1984468047644191537"

[[comments]]
author = "menSh"
date = "2008-09-12T14:16:00+00:00"
text = "yulla kaffara :)is"
avatar_url = "http://photos1.blogger.com/blogger/4938/2050/1600/am.jpg"
profile_url = "https://www.blogger.com/profile/14221308254991337821"
comment_url = "https://mos3abof.blogspot.com/2008/09/blog-post.html?showComment=1221228960000#c4923841828903279844"

[[comments]]
author = "حزينه"
date = "2008-09-12T15:18:00+00:00"
text = "دى الدنيا ملغبطه معاك اوى<br /><br /><br />حزينه"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEheLKcurBdg8be_diNdqTL61Ri7aPIMDfMRn4LLe5eBXkVhdWQeGkyFVL2NdkAwVbhHg1_OGYxOwW4Mk1aIU415s197Gi-JTdVFTsYUMzqoL8AK8ZGGZSmBAv9nVdOA82s/s220/gothic75[1].gif"
profile_url = "https://www.blogger.com/profile/16606949933826841309"
comment_url = "https://mos3abof.blogspot.com/2008/09/blog-post.html?showComment=1221232680000#c4259209483501932229"

[[comments]]
author = "Amr"
date = "2008-09-12T18:39:00+00:00"
text = "كل الأسماك، مرة في رمضان اللي فات اتسحرت مع واحد صاحبي فطير، وتاني يوم أجارك الله من العطش<br />بمناسبة التونة، إوعى تأكل أي قط تونة"
avatar_url = "http://www.arttoheart.ca/newimages/blueflrs.jpg"
profile_url = "https://www.blogger.com/profile/03741243192561256269"
comment_url = "https://mos3abof.blogspot.com/2008/09/blog-post.html?showComment=1221244740000#c2946421528705708703"

[[comments]]
author = "حواء"
date = "2008-09-13T06:30:00+00:00"
text = "ياه<br /><br />3 في الصيام يوجعوا<br /><br />تونة<br /><br />شطة<br /><br />استقالة<br /><br /><br />أعانك الله"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiPNLfILz6MSby0BEoszHpMfa580CoHTHtGGWoM9sJ5s5heHMrkVGmdm5YBrTx384oVlGygavSo6daBBG26pE8L02Ul92fyo3h_a0ybrN_5R6p7rkAYM0mixnrDGPPipmM/s220/wah.jpg"
profile_url = "https://www.blogger.com/profile/09362159503528552431"
comment_url = "https://mos3abof.blogspot.com/2008/09/blog-post.html?showComment=1221287400000#c2424594890476160891"

[[comments]]
author = "Lens Geek"
date = "2008-09-13T13:31:00+00:00"
text = "dee mo2amrah ya ostaz<br />akeed dee me7walet eghteyal IOL metwarat feeha<br />aklok toona we azeno el fajr 3ashan yemotook 3atshan<br /><br />bass la2 ya mos3ab la2 akeed enta hatfdal samd ya ibny<br /><br />U CAN DO IT MAN, U CAN DO IT"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhDH6cac8DhCu85r5fVw0KJDQyTSgnbUN_on5yZRrtKG44soaS5wrAZnDMZBnmYItm4PSgM5Be26Q5kswvv4w84fGE-zjxA4uFGBZW67q5kjJzKnPEAcvpMpdz-KsYUpg/s220/Ahmed2.gif"
profile_url = "https://www.blogger.com/profile/08391635125789451063"
comment_url = "https://mos3abof.blogspot.com/2008/09/blog-post.html?showComment=1221312660000#c3157479144998521862"

[[comments]]
author = "حـــلـــم كـــان"
date = "2008-09-16T00:03:00+00:00"
text = "ربنا معاك يابنى ده والله ظلم كده عليك"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEisvedOMRUjKx7YP_aap6J4m-3RcsVYj-mCREYVXwyO_KPDLrgr9yRuAv3c79z43F_MUhFxWqIGv3ENpPRg-A7TX0AUmC3QiX67Q-v4z_FTrG8JsiwdwvJzY9q-bNf7SRQ/s113/85303c0fbfgt.JPG"
profile_url = "https://www.blogger.com/profile/16960195539010935754"
comment_url = "https://mos3abof.blogspot.com/2008/09/blog-post.html?showComment=1221523380000#c8362986651068669446"

[[comments]]
author = "Anonymous"
date = "2008-09-16T10:24:00+00:00"
text = "ايه ثلاثية الرعب دي<br />ربنا يعينك يارب"
comment_url = "https://mos3abof.blogspot.com/2008/09/blog-post.html?showComment=1221560640000#c6913195724387338215"

[[comments]]
author = "Anonymous"
date = "2008-09-17T14:31:00+00:00"
text = "أزال أحد مشرفي المدونة هذا التعليق."
comment_url = "https://mos3abof.blogspot.com/2008/09/blog-post.html?showComment=1221661860000#c8828347992980175453"

[[comments]]
author = "Salma Amer"
date = "2008-09-20T22:20:00+00:00"
text = "ههههههه <br />تقريبا شكلها كدة تكفير ذنوب :)"
avatar_url = "http://farm2.static.flickr.com/1132/1365681113_f20faceeb5.jpg?v=0"
profile_url = "https://www.blogger.com/profile/08716194696950096714"
comment_url = "https://mos3abof.blogspot.com/2008/09/blog-post.html?showComment=1221949200000#c8053749740706068121"
