[[comments]]
author = "ام مليكة"
date = "2008-01-12T21:39:00+00:00"
text = "ياعيني يا مصاعيبو، معلش مش تبقى تخلي بالك من الكلسات يا مصعب ماهي الست مش هتقطع نفسها يعني هتضرب كلكس ولا تفرمل ولا تعمل ايه يعني الرحمة شوية مش كفاية انها سايقة اصلا<br /><br />الف سلامة عليك بس المرة الجاية ابعد عن كل الستات في عربية المترو وعربيات الشارع كمان"
avatar_url = "http://admins.20at.com/do3a2/bentbalad.jpg"
profile_url = "https://www.blogger.com/profile/17720828413632673574"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_12.html?showComment=1200173940000#c1760948657489234719"

[[comments]]
author = "nyira_elsheiref"
date = "2008-01-12T21:46:00+00:00"
text = "تعيش وتاخد غيرها يا معلم <br />أنا بهزر طبعا مش هتاخد غيرها ولا حاجه <br />المهم إنها جت سليمة الحمد لله<br />ومجربة أنا إحساس لمة الشعب المصرى على شىء ما دى (:"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/01466185015455031275"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_12.html?showComment=1200174360000#c252223953263461980"

[[comments]]
author = "menSh"
date = "2008-01-12T22:17:00+00:00"
text = "سلامتك يا مصاعيبو<br /><br />ربنا يحفظك يابني وينجيك إن شاء الله<br /><br />معلش.. دي من مستلزمات المواطنة.. إنك تعيش.. وتاخد غيرها.. إذا إنت ما أخدتش.. ومال عاوز مين يعني ياخد!"
avatar_url = "http://photos1.blogger.com/blogger/4938/2050/1600/am.jpg"
profile_url = "https://www.blogger.com/profile/14221308254991337821"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_12.html?showComment=1200176220000#c8063574870581325901"

[[comments]]
author = "Salma Amer"
date = "2008-01-12T22:21:00+00:00"
text = "الف سلامة يا مصاعيبو إن شاء الله كل الناس الوحشة وانت لأ<br />بس محدش ينكر ان الحادثة كوميدية بجد وبعدين انت اللي ماسمعتش الكلكس تبقى غلطان اكيد وبعدين المرة الجاية ممكن تشوف بظهرك مثلا حاول تخلي بالك اكتر من كدة <br />وقبل ما انسى سلامة الكوتشي بتاعك انا عرفة انه كان عزيز عليك بس ادي حال الدنيا تنزل من البيت بفردتين سلام ترجع بواحدة بس اييييية دنيا  معلش تعيش وتفتكرة بقى"
avatar_url = "http://farm2.static.flickr.com/1132/1365681113_f20faceeb5.jpg?v=0"
profile_url = "https://www.blogger.com/profile/08716194696950096714"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_12.html?showComment=1200176460000#c1996776333097372572"

[[comments]]
author = "Anonymous"
date = "2008-01-12T22:34:00+00:00"
text = "ma3lesh ya mos3ab pasha :), eb2a rakeb lomad , wala ay merayat 3ashan teshof elly warak <br />asl fe nas beteb2a mesh fadya we heya betsoo2 :)<br /><br /><br />ma3lesh 7asal 5eer"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_12.html?showComment=1200177240000#c5247387566227543226"

[[comments]]
author = "None"
date = "2008-01-12T22:50:00+00:00"
text = "حمدالله على السلامه<br />بس مقلتش<br />سالتها الساندوتش كويس ولا لا؟<br /><br />:)<br /><br /> وسلااااااااام"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi4Yu2bP8lKSq9t3v_U1xa-cd-ERVelzgHrDVr6BzjCxR8-nm2NgNMqYbMGu1MKGftLCIPDYksLr8kVRSAAcZRVFi__vwio52OOQ1WL1kTu952riMhmqtshHKQLwzWmETU/s1600/*"
profile_url = "https://www.blogger.com/profile/08542366881566698240"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_12.html?showComment=1200178200000#c6732908519524353638"

[[comments]]
author = "mohamed"
date = "2008-01-12T23:53:00+00:00"
text = "ألف سلامة عليك يامصعب ..<br /><br />شفاك الله وعافاك <br /><br />بس في سؤال عايز اسئلة <br /><br />ولا اقولك بيني وبينك بقى"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiGfWhZiigMyqtTXuNGhGuZ7kCzQpSXHHBQFxacGHOFHEX81agRvyAHVvJNqxlHc4r65JdjhzBKu76zKEj0TXhBVJ-Rjmpfciyt9XBGHfdbSKJJfq-Rc3UeAgPD5FN-SK0/s220/DSCF29155.jpg"
profile_url = "https://www.blogger.com/profile/11099621052476900765"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_12.html?showComment=1200181980000#c7397094807931522158"

[[comments]]
author = "حلم الحرية"
date = "2008-01-12T23:54:00+00:00"
text = "اهم حاجة مقلتلناش <br /><br />السندويتش كويس<br />?????<br />:D<br /><br />الحمد لله انها جت سليمة..والف سلامة عليك<br />:)"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj5134mBTHr7rVK3DSDgnRf5E_RugYPeh5cWZbeDoXKvwsHyL4tD1n_WEYXUeoJ4PMOSErPXCdUpGN274-0C5lbxDHtZQHsGch0ykrvpLnt52BWXdtpgWRytPSyMnw4MA/s1600/*"
profile_url = "https://www.blogger.com/profile/16809490468014096848"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_12.html?showComment=1200182040000#c8325759955141065284"

[[comments]]
author = "Anonymous"
date = "2008-01-13T00:23:00+00:00"
text = "واخبار السندوتش ايه صحيح؟<br />:))<br /><br />الف سلامة عليك يا فندم<br />وجت سليمة<br />:)"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_12.html?showComment=1200183780000#c3253582639846992502"

[[comments]]
author = "Unknown"
date = "2008-01-13T06:56:00+00:00"
text = "يا زعيم ألف سلامة<br />وابقى خلى بالك من عربيات الناس المرة الجية مش كل يوم تخبطلك عربية"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/12955725133588745897"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_12.html?showComment=1200207360000#c2620884058110285239"

[[comments]]
author = "قضية عم أحمد    Ahmed Case"
date = "2008-01-13T08:05:00+00:00"
text = "الراجل اللى تدوسه عربية ميقلش لاخواته علشان يجيوا يطنوا عليه ا يستاهلش سلامتك .. <br /><br />روح يا مصعب ضيعت من ايدي حبة صور كانوا هيبقوا في الجون ... <br /><br />الكلام خلص"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgV-wcarXLkgWhQQil5kwuYh3wp9AEWNEDcLSaQD2LN0vM_G4H9YJFgqa0XczHwll6yiqoYqdHkRIaOBrs7mUlUTV8btyQ-yKEFvsGrNIWlN99lkjHG8LD-zKscO0MMuVA/s220/DSC_7364.JPG"
profile_url = "https://www.blogger.com/profile/07000569434293484731"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_12.html?showComment=1200211500000#c5685923734023561274"

[[comments]]
author = "أميرة من غير قصر ولا بستان.. ولا الشاطر حسن كمان"
date = "2008-01-13T11:21:00+00:00"
text = "انا اقولك بقي علي اللي حصل بالظبط<br />هي كانت سايقة ولا بيها ولا عليها وبعدين شافتك و انت بتعدي الشارع و اتسحرت بعيونك الأخضره;) وحصل ارتباك و عدم تركيز ونسيت السواقة بقي و الفرامل وكل حاجه...و الدليل انها كانت مصممة انها توصلك الحتة اللي انت عايزها :):)<br /><br />عشان بس تعرف ف الاخر ان انت اللي غلطان...انت اللي عينيك خضراء<br /><br />الف سلامةعليك يا مصعب افندي:)"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEirdirzKebc0hcGC4MQ6kvVkx2q0MdxprJrl-jqSZ5l_jxE2bWsZVd-Pla_Zla1V4g0FjN5PUa4k3oTN0AO0cgFlRcbwr6XbP-7sqohbU_KGsAtNaDenb4eAJmqzrb0EGE/s220/blogpic5ke.jpg"
profile_url = "https://www.blogger.com/profile/16391848599214933906"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_12.html?showComment=1200223260000#c4597675801518640656"

[[comments]]
author = "أحمد الدريني"
date = "2008-01-13T11:23:00+00:00"
text = "المهم ان الساندويتش بخير.."
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/17300680267091030312"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_12.html?showComment=1200223380000#c6767491804922288753"

[[comments]]
author = "كريم"
date = "2008-01-13T11:57:00+00:00"
text = "السلام عليكم و رحمة الله و بركاته<br /><br />ألف ألف سلامة يا مصعب<br /><br />تقوم بالسلامة ان شاء الله :)"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgrGMFWS8BsbWWvzJzACj6pdRE06QBZpQFf9OlDgyhxjwZgypGFB2daJ4w-nYacwuvG0ybPKER01iLc9cjOF5TkiXXrZyIzcIgyxyYt3U_nhjXySqc1GS7ky9VqeK5bGTE/s220/Untitled.jpg"
profile_url = "https://www.blogger.com/profile/04113814959767509776"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_12.html?showComment=1200225420000#c4686476167806067256"

[[comments]]
author = "شيرين"
date = "2008-01-13T12:31:00+00:00"
text = "الخبط للجدعان يا مصاعيبو ولا يهمك.. ربنا يسلمك دايما ياااا رب"
avatar_url = "http://photos-279.ll.facebook.com/photos-ll-sctm/v99/129/13/717256279/n717256279_214552_3758.jpg"
profile_url = "https://www.blogger.com/profile/08718885335246773468"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_12.html?showComment=1200227460000#c2278733658204029085"

[[comments]]
author = "أحمد"
date = "2008-01-13T12:46:00+00:00"
text = "والله انت راجل محترم"
avatar_url = "http://photos1.blogger.com/img/41/3626/1024/egon4.jpg"
profile_url = "https://www.blogger.com/profile/04438703898828732466"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_12.html?showComment=1200228360000#c5025462048469692014"

[[comments]]
author = "همسة قلم"
date = "2008-01-13T17:57:00+00:00"
text = "حمدا لله على سلامتكم اخى مصعب <br /><br />ومعلش على الكوتشي يتعوض ان شاء الله ..<br />ألف لا بأس عليكم"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEii4ggxdv3eA4vn2CYG-b9gnvLLncfGMI7cDi3rZ745Y1YhfoeVBQ_jbwllHGEMDbghjUdisPRY1YZZUmKocY_lc9BdcNeEPdMtDjhc1mI5oky2_pjETA3EpfL8EZ1x9Q/s150/*"
profile_url = "https://www.blogger.com/profile/17533968248895951396"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_12.html?showComment=1200247020000#c3858987745177861770"

[[comments]]
author = "الطائر الحر"
date = "2008-01-13T20:14:00+00:00"
text = "أزال المؤلف هذا التعليق."
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi5iA3YXPlDr_RHPQWzh4RqFHNP3O3v6Eoe3OINmDiKqQEsvkg8RMZ-l_zBb3u_2O4AkrAeqkRVAW8-YUKxzGoeNyCBptQGe-hXgbfZq9trGbsGrIJC_D3EsAKIPBnyVg/s220/pic02b.jpg"
profile_url = "https://www.blogger.com/profile/11871033505873136821"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_12.html?showComment=1200255240000#c9102048731608881104"

[[comments]]
author = "الطائر الحر"
date = "2008-01-13T20:55:00+00:00"
text = "ألف سلامه يا مصعب الخير<br />انا عارف ان الناس هتعلق كتير علي الساندوتش بس انا هعلق علي الناس<br />فالموقف ووصفك للموقف فكرني بمقوله لواحد وقع في حفرة فتجمع عليه كثير من الناس فقال ( مالكم تكأكأتم علي كتكأكئكم على ذي جنة افرنقعوا عني)<br />وبالتوفيق<br />( شاركوا معنا فى وثيقة الألف مدون للتضامن مع أحمد محسن )"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi5iA3YXPlDr_RHPQWzh4RqFHNP3O3v6Eoe3OINmDiKqQEsvkg8RMZ-l_zBb3u_2O4AkrAeqkRVAW8-YUKxzGoeNyCBptQGe-hXgbfZq9trGbsGrIJC_D3EsAKIPBnyVg/s220/pic02b.jpg"
profile_url = "https://www.blogger.com/profile/11871033505873136821"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_12.html?showComment=1200257700000#c8699820568219396066"

[[comments]]
author = "MarwaAshraf"
date = "2008-01-13T21:11:00+00:00"
text = "إسمح لي بعد إذنك بشوية رغي كده على الماشي علشان مش حينفع مرغيش في موقف زي ده <br /><br />عمرك شوفت حد في الدنيا على وشة تعبير إنه مخضوض وفي نفس الوقت فطسان على نفسه من الضحك.. انا دخلت في الحالة دي لما قرأت البوست.. المفروض إني مخضوض علشان في حادثة وأكشن وكوتشي مخلوع بقى وحركات وفي نفس الوقت فطسانة على روحي من الضحك علشان مشهد الفيلم اللي شوفته كتير في الإعلانات وعمري ما زهقت منه وبحبه جدا كمان  لأنه بيفكرني بنفسي ، أنا صحيح مش عندي عربية إلا إن مافيش يوم بيعدي من غير ما أصتدم بحد ومش أي خبطة الصراحة بتكون في الصميم ودايما أنا اللي مش مركزة وبكون السبب في الخبطة وساعتها بيبقى نفسي اللي خبطة يسألني \"والساندوتش كويس؟\".. وعلى فكرة بتكون معجزة لو روحت بيتنا يوم من غير ما أخبط حد.. مش عارفة لما يكون عندي عربية حيحصل ايه .. هههههههه<br /><br />واللي ضحكني جدا بردوا موضوع الكوتش ده، ولا الراجل بتاع \"البتر\" .. هي كلمة توجع الصراحة بس موتتني على نفسي من الضحك ... لا بجد يا مصعب أبدعت .. محدش قبل كده إقدر يخليني مخضوضة وفي نفس الوقت فطسانة على روحي من الضحك <br /><br />شوفت بعد الرغي ده كله نسيت أقولك أهم حاجة \"سلامتك وربنا يشفيك\" يلا بسرعة قول أمين <br /><br />سلامات <br /><br />:)"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/12117806503113618382"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_12.html?showComment=1200258660000#c1266646473536459353"

[[comments]]
author = "دوللي"
date = "2008-01-14T11:03:00+00:00"
text = "سلامتك يا مصعب ان شاء الله الناس الوحشين"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/06515904854255564384"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_12.html?showComment=1200308580000#c5636758535706750304"

[[comments]]
author = "دينا فهمي"
date = "2008-01-14T16:16:00+00:00"
text = "الف سلامة عليك<br /><br />بس بجد تعليقات الناس تحفةةةةةةةة"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/07685435794478937439"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_12.html?showComment=1200327360000#c7450752149562159709"

[[comments]]
author = "Anonymous"
date = "2008-01-14T18:11:00+00:00"
text = "الف سلامة للكوتشي والسندويتش<br />ليه كل الحاجات الجميلة اللي فيها شين بتبوظ بسرعة يا تري<br />جاوب يا فيلسوف مصعب<br /><br />ساعد نسرين الايمن"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_12.html?showComment=1200334260000#c1428808989682754749"

[[comments]]
author = "Anonymous"
date = "2008-01-16T02:11:00+00:00"
text = "ana awel mara agy hena..bs fe3lan enta 3andak 7a2..e7na fe 7agat kteer awy 7awaleena bete7sal ghareeba we malhash m3na..atmanna enena nesebha we nerakkez fi el mohem<br /><br />gameel enk mardetsh tekhawef el bent aktar mahy khayfa..de rogoola menak 3alafekra..fe gheerak kan 3amal elmawdoo3 fedee7a :))<br /><br />alf salama"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_12.html?showComment=1200449460000#c8230958942766099126"

[[comments]]
author = "Mony The Angel"
date = "2008-01-18T10:04:00+00:00"
text = "salamtak alf salama"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjj4h6hlbKyUklJB5J_QeHmZidZ8mEHO-s5lWgxcP3qUEQSPg4AS0GkKHyrjWHC4Z5y2O3vBW2OY7WPf-cZ0PSVMC-DcEJ6cu6SRYKhpVq1jh6S9ve07RM4o8WgdU_8rxE/s220/mine...jpg"
profile_url = "https://www.blogger.com/profile/02273268851121458996"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_12.html?showComment=1200650640000#c7436316391079543105"

[[comments]]
author = "Mai Kamel"
date = "2008-01-18T22:34:00+00:00"
text = "الف سلامة يا ريس<br />معلش هم كل ارباب الكيبورد والماوس بيتصابوا كدة.. قلة بقى فى البلد والعين عليكو والعدو متربصلكوا<br />هههههههههههه<br />الف سلامة يا مصعب.. الحمد لله قدر ولطف<br />(F)"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/17724279077077931734"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_12.html?showComment=1200695640000#c3066790622417628802"

[[comments]]
author = "خلود صلاح"
date = "2008-01-19T08:55:00+00:00"
text = "هههههههههههههههههه<br /><br />كوتشى ايه بس؟؟<br /><br />سلامتك"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh8bvqsQIuoEibIWMkIZfW8yPxFIC54jlfIbx7_98utMiCw9cl4JmQElw0Pv6r4yIxHrgjXrp88PBjyQSCBYo81tdMG721xTA5ecCPCvONGhG6g5vHhHrCoj_vkgG90HQ/s220/U11P_omyE6cCfjc.jpg"
profile_url = "https://www.blogger.com/profile/14001025091833760135"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_12.html?showComment=1200732900000#c7098766078437066305"

[[comments]]
author = "زى الهوا"
date = "2008-01-19T19:03:00+00:00"
text = "يههههههههههه حضرتك مسهل الموضوع اوى , دا المصريين خصوصا بيحبوا يهولوا المواضيع اوى , دا انا لسة صحبتى بحدفها بالقلم من يومين لقيتها عمالة تعيط , خلاص يعنى القلم وجعها , <br /><br />البلوج جامد بحييك عليه"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgepI9NbQMmQd5gXtHiF0p2753_-Igr67W7dvbtRAWZFn1dQ1ufkW1d8C0ezc6-b9ljOQpBcVp_z5q_57jSFOIr8QrB8Sp-SRqY-wtCqeOE_wSio2JT7TPtd5L7vYiYhw/s220/103924626.jpg"
profile_url = "https://www.blogger.com/profile/00948456750372382325"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_12.html?showComment=1200769380000#c7076058252528117768"

[[comments]]
author = "weswes"
date = "2008-01-19T19:40:00+00:00"
text = "الف سلامه يا عم مصعبوف<br />خالى بالك وانت ماشى هو انت ناسى انك فى مصر ولا ايه<br />الست يا اما تسوق يا اما تفرمل انت هتحيرها ليه بس<br />انت ركز شويه<br />:)"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiw4snw0O4r8EYHQhiu7PCP3YXbjsOVmNj5zsVG2NmG_iJW8qfvdrvDKQVVXpYEQyxkgnLEal7LDhjHT9wSDmHEaztJc2mql6BgND38sUt9YXFFoG0Id5pU9R8WI3ItEKo/s220/IMG_0034.JPG"
profile_url = "https://www.blogger.com/profile/04810150175952124524"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_12.html?showComment=1200771600000#c3953439568859290631"

[[comments]]
author = "MariumaZ"
date = "2008-01-20T16:07:00+00:00"
text = "وأنا أقول انت ليه لابس سليبر مفتوح من كل ناحية في عز التلج اللي إحنا فيه ده واتكسفت أسألك.. أتاريك خبطتك بنت في الشارع وفرمت رجلك ... سلامتك ألف سلامة يا مصعب ... وعلى العموم الموقف ده فيه ثلاث نقاط مهمة ... أولاً إن اللي خبطتك بنت وأحمد ربنا لأنه لو كان ولد مش بعيد كان بعد ما خبطك .. يطلع يضربك ويشتمك ويقولك ما تفتح يا حيوان .. ودي حتكون أقل شتيمة .. وده لأن الولاد ما بيحبوش يعترفوا إنهم غلطوا وبلطجية سواقة ومابيخافوش..<br />ثانياً ... لازم يظهر العسكري المترصد لكل شخص خسيس معاه حبة فلوس خلوه يسوق عربيةولازم يكون ضد الشخص السواق على أساس إنه أغنى!!!<br />وساعات يبقى حيموت ياخد قرشين من العملية دي علشان يفوت الأمور بمزاجه ومايعملش محضر، وخصوصاً لو كانت بنت أو واحدة ست اللي سايقين!!!<br />ثالثاً... الشعب المصري اللي بيفرح في اللمة والزحمة والمصيبة واللي بيفتح قسم إفتاء فوري بيتضمن معلومات طبية وقانونية وإجتماعية ودينية ... وبرضوا بيهبوا في السواق على أساس إنه بيمثل لهم رمز مصغر للسلطة والمال والطغيان ... ولا أنت إيه رأيك؟؟؟"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg9giUV2iCTwwtfQoUxjZXLMjO4Scq0iKCUdYMCgmovIiMOde9B26aqPY_6wwiZy8PHqssu8sQSZDgaBjnhd_kQL0aeEev2mUQs1l-tOOUp6mUNQV2JilPBktEhrS_AHqU/s220/IMG_0084.jpg"
profile_url = "https://www.blogger.com/profile/12796121153780883763"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_12.html?showComment=1200845220000#c5607339820876510380"

[[comments]]
author = "Reemo"
date = "2008-01-21T07:39:00+00:00"
text = "ألف سلامه يا مصعب<br />بجد سلامتك<br />ابقى خد بالك من الساندويتش كويس المره الجايه<br />:)"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj33D5UUIoxKHG6BmBUtQumPt5l-shCl21gIybLoB6j4mIxW_6wnYKIeUOMEJf4qxgRgzg9Q6-Ju2EDL_624Dp0FY5yNDXQI-ZjTwnUjxUkOQqck8CDk55VgcupXuTMMWU/s220/n555111346_557029_3135.jpg"
profile_url = "https://www.blogger.com/profile/04634696482778663332"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_12.html?showComment=1200901140000#c4712637732073019700"

[[comments]]
author = "ihapoof"
date = "2008-01-26T12:31:00+00:00"
text = "سلامتك يا كبير .. وسلامه الكوتشى (:"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg89TopeqB1W2arvX1495NJNTW--ytSy54M0wRm7Sa1vjm2AaYC7e2M3sij-uprNK6D4y6yVBC2fXXNASH-VgS4Fjzppe1yvvrPzEcVllqUQLDsrC6eCin79ByMfv_OVw/s220/n691677246_200896_4008.jpg"
profile_url = "https://www.blogger.com/profile/09130756176295587260"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_12.html?showComment=1201350660000#c4661755726010288888"

[[comments]]
author = "nour"
date = "2008-03-13T22:07:00+00:00"
text = "الف سلامه عليك يا مصعب"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/13625151471195771582"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_12.html?showComment=1205446020000#c9210607157635561378"
