[[comments]]
author = "Anonymous"
date = "2006-02-01T08:08:00+00:00"
text = "ايه الفضايح دي يا بني حرام عليك، الاهبل ممكن يعرف كل اسرارنا بس كويس برده اهو الواحد يحس انه عايش حتى لو ع النت"
comment_url = "https://mos3abof.blogspot.com/2006/01/blog-post_113876320784498879.html?showComment=1138781280000#c113878133574705902"

[[comments]]
author = "العـابــــــــره"
date = "2006-02-09T12:08:00+00:00"
text = "ممكن اسال سؤال محيرنى <br />اليوم ده كان كام يوم؟"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjirpnB1jlU7bWG0V6oQLFugE9LdCMmPYCneTsqfh2X7QHo46m-E-v1cdrCVcEqswMoAqKAfbCjRjc-xZIYckh1rq-QCi0KDc5B3O1mEHShrSAU5djGV2RpP_EXGiIOJA/s220/amanyyyyyy.jpg"
profile_url = "https://www.blogger.com/profile/02540503067719024339"
comment_url = "https://mos3abof.blogspot.com/2006/01/blog-post_113876320784498879.html?showComment=1139486880000#c113948692107257480"

[[comments]]
author = "Mony The Angel"
date = "2007-04-25T21:38:00+00:00"
text = "ya nhaaaaaaaaaaaaaaar abiaaaaaaaaaaaaaaaad<br />kol da"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjj4h6hlbKyUklJB5J_QeHmZidZ8mEHO-s5lWgxcP3qUEQSPg4AS0GkKHyrjWHC4Z5y2O3vBW2OY7WPf-cZ0PSVMC-DcEJ6cu6SRYKhpVq1jh6S9ve07RM4o8WgdU_8rxE/s220/mine...jpg"
profile_url = "https://www.blogger.com/profile/02273268851121458996"
comment_url = "https://mos3abof.blogspot.com/2006/01/blog-post_113876320784498879.html?showComment=1177537080000#c7833234189106241927"
