[[comments]]
author = "غير معرف"
date = "2007-03-08T06:38:00+01:00"
avatar_url = ""
profile_url = ""
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_08.html#c3298460517160278321"
text = "و الله كان ليا حق لما قلت انا نفسى اكون محبوبه زيك ...ماشاء الله بجد ...الف حمدالله على سلامتك , و ربنا يباركلك فى محبه الناس و يبارك فيك"

[[comments]]
author = "ياء"
date = "2007-03-08T08:44:00+01:00"
avatar_url = "https://www.blogger.com/img/blogger_logo_round_35.png"
profile_url = "https://www.blogger.com/profile/09927085065103433253"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_08.html#c5484064677509406078"
text = "حمد لله على السلامه"

[[comments]]
author = "الحلم العربي"
date = "2007-03-08T09:35:00+01:00"
avatar_url = ""
profile_url = "https://www.blogger.com/profile/08895879839574889127"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_08.html#c8724336806238361774"
text = "فكرتنى بروايتى المحبوبة هارد تايمز و الكآبة اللى كانت بتنبعث منها ( الرواية دي كانت عاملالى عقدة نفسية في الثانوية العامة لدرجة انى كنت بتخيل نفسي البنت الأمورة اللى أشعة الشمس بتزيدها جمال و كنت بقعد في الشمس كتير لغاية ما عنيه وجعتنى).||طبعا حمدالله على السلامة . مش عارفة أقولك ربنا مايعيد الأيام دي و لا اقولك رب ضارة نافعة .. عرفت قد ايه في ناس حواليك بيحبوك .||ملحوظة : البتاعة اللى بتتركب في الذراع اسمها \"كانيولا\" أصل أختى دكتورة جراحة بعيد عنك ( مش كنت تقولى كنت خلتها تعملك العملية هي ؟ )||حمد الله على السلامة و ربنا يحبب الناس فيك أكتر و أكتر"

[[comments]]
author = "إبـراهيم ..."
date = "2007-03-08T11:52:00+01:00"
avatar_url = ""
profile_url = "https://www.blogger.com/profile/05958027012551455648"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_08.html#c8116147048160014077"
text = "حمد الله على سلاامتــــك يا جميييل||||بس إيه الإبداعات دي كلها .....||||دي عاملة زي ما تكون مدائح ( الزائدة ) عن الحـد ،،،،،، ياللا||||أشوف وشـــك بخييير"

[[comments]]
author = "emz"
date = "2007-03-08T13:21:00+01:00"
avatar_url = ""
profile_url = "https://www.blogger.com/profile/06702188321496445002"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_08.html#c7954899356073292902"
text = "حمدالله عالسلامة||ربنا يخليلك كل الناس اللى بتحبهم||و يخليك ليهم"

[[comments]]
author = "غير معرف"
date = "2007-03-08T13:41:00+01:00"
avatar_url = ""
profile_url = ""
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_08.html#c6062685627484614031"
text = "الرجال مواقف حبيبي احمد حلمى كان راجل دلوقتي بقة موقف كبير وأنا نفسي في ابقى موقف في الفلكي :)||||أولا فعلا أنت إنسان جميل وتستحق كل هذا الإجماع على الحب من جميع الناس الذين يعرفوك وأنا أولهم يا مصعب .||||فعلا يا مصعب انا كنت أتمنى أكون معاك في القصة من البداية علشان لازم كنت اكون من الاول هناك بصفتك اخويا وعلشان اوثقهالك||||روايتك للساعات العصيبة خلتني ابتسم شوية علشان يمكن أنا كنت في كواليس بعض الأشياء .||||بس أنت نسيت تقول للناس على اللى مرات عمك الله يكرمها عملته فيا وياسر تعليب كان شاهد على العصر وطبعا اخوك عمر كنت أرى في عينيه ابتسامة الليئيم وهو عمال يسخن مرات عمك وهي عماله تفتح الأكياس كيس كيس وكل اما تفتح كيس تسخن عليا اكتر (الله يسامحك يا سلمى ) وتقولى ده كلام جايبله اكل هو قاعد لوحده ، لحد اما وصلت للورد وقالت لى بنرة رقيقه جدا -مش هنساها- مين اللى بعت الوردددددددد ده طبعا انا فورا قلت والله مش انا!! ، حتى لما قدمتلى طبق فيه بونبوني وشكولاته انا عجبتني بونبونايه واخترتها لاقتها بتقولى خد شكولاته احسن طبعا انا فورا لغيت فكرة البونوبني ومن ساعتها اصبح للشكولاته مزاق خاص في حياتي .||||مش عارف اقولك ايه غير اني فعلا بحبك يا مصعب الخير والف سلامة ويارب ما ينقص منك أي حاجه تانى ."

[[comments]]
author = "Abd El Rahman Magdy"
date = "2007-03-08T14:58:00+01:00"
avatar_url = ""
profile_url = "https://www.blogger.com/profile/11553040614389148796"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_08.html#c8232095211093562131"
text = "يا سيدي حمد الله على السلامة||ويا رب ما تتألمش تاني أبدا لأنك شخصية جميلة جدا||كان نفسي جدا أكون معاك في الوقت ده لكن انت عارف بقى الثانوية وهمها||ربنا يكتر من صحابك وحبايبك||بجد انت شخصية صعب إن الواحد ما يحبهاش||ويا رب ترجع لموقعك وصحابك وحبايبك بألف سلامة||تحياتي ليك يا زعيم"

[[comments]]
author = "محمد السيد..مش حاسكت"
date = "2007-03-08T15:36:00+01:00"
avatar_url = "https://www.blogger.com/img/blogger_logo_round_35.png"
profile_url = "https://www.blogger.com/profile/15123433931771567833"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_08.html#c5175000350082893429"
text = "طيب أقول إيه يعني؟||أهنيك علي الشفاء؟||ولا أهنيك علي العودة؟||ولا اللي أحسن من ده كله أهنيك علي حب الناس ده كله ليك ؟||||تعرف؟؟أحلي حاجة كانت في الموضوع إيه؟ حب الناس وكمية الردود دي كلها ... بجد حاجة \"تتغبط\" عليها..||||بس الصراحة إنت تستاهل أكتر بكتير من ده ...||من زمان مقابلتش حد كده ...||||ربنا يخليك ليا..ولينا كلنا ...||||وبخصوص بقي الكلمتين الل كتبتهم عليا دول .....||والله ده ولا حاجة .أنايومها روحت بجد زعلان أوي ومتضايق لأني معرفتش اقعد معاك كتير ... ولما القطر فاتني ..كنت خلاص بأفكر أرجع لك تاني بس لقيت الوقت متأخر ....||||كان نفسي أوي أقعد معاك أكتر كد ه...||||بس حنقول إيه ؟؟ حتتعوض إن شاء الله ...||ودعوة اليمن السعيد دي ...ممكن أردها لك ؟؟؟ بس لما أقابلك إن شاء الله ....||||عموما...حمدا لله علي السلامة يا حبيي ..."

[[comments]]
author = "غير معرف"
date = "2007-03-08T20:15:00+01:00"
avatar_url = ""
profile_url = ""
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_08.html#c3190772241494721351"
text = "البتاعة اللى بتتركب فى الأيد اسمها||كانيولا||||هو أكيد انت بقيت كويس الحمد لله عشان تكتب كل موضوع التعبير دا :)||||والبنج فعلا بيجى بالأستسلام .. انا عملت عملية مرة وانا صغيرة , تقريبا رحت فى الأغماء قبل ما حقنة البنج تكمل وكنت مبتسمة جدا والدكتور مندهش وتقريبا كان هاين عليه يصحينى تانى يقولى ايه||اللى بيضحك !||||حمدلله ع السلامة ورب زايدة نافعة أظهرت المشاعر الجميلة دى كلها||||ربنا يديم المحبة"

[[comments]]
author = "محمود"
date = "2007-03-08T22:20:00+01:00"
avatar_url = "https://www.blogger.com/img/blogger_logo_round_35.png"
profile_url = "https://www.blogger.com/profile/04698116591720747307"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_08.html#c976490919419123047"
text = "يعني يا مصعب تعمل عملية و ماعرفش بجد انا اسف جدا لكدة اتمنى انك تكون في افضل صحة باذن الله"

[[comments]]
author = "غير معرف"
date = "2007-03-08T22:43:00+01:00"
avatar_url = ""
profile_url = ""
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_08.html#c5298743406364875483"
text = "الواحد يجرب يعمل عمليه يشوف حد هيسأل عليه ولا لأ بس انا متأكده ان مافيش حد هيسأل هههههههه||يللا الف سلامه على فكره الموضوع جميل جدا انا مت من الضحك عليه"

[[comments]]
author = "أميرة البلطجية"
date = "2007-03-08T22:51:00+01:00"
avatar_url = ""
profile_url = "https://www.blogger.com/profile/01519481371919373237"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_08.html#c3348850302114340680"
text = "اللي ليه حبايب زيك يبقي عايز يعمل عملية كل يوم||بس ربنا ما يجبلك عمليات تاني||ويا رب يباركلك في صحابك وحبايبك وتفضلوا سوا ويجمعكوا في الجنة ان شاء الله||حمد الله على سلامتك يا مصعب"

[[comments]]
author = "غير معرف"
date = "2007-03-09T00:13:00+01:00"
avatar_url = ""
profile_url = ""
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_08.html#c4454034085623549945"
text = "إيه التدوينة الأممية دي؟||مكنش ناقص غير السيد الرئيس والسيدة||حرمه في الليلة السعيدة دي||حمدا لله علي سلامتك||أكوادك فرحت بيك من تاني"

[[comments]]
author = "Aml Ghonaim"
date = "2007-03-09T00:17:00+01:00"
avatar_url = "https://www.blogger.com/img/blogger_logo_round_35.png"
profile_url = "https://www.blogger.com/profile/06063924740014634484"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_08.html#c3276539562569596733"
text = "كنت أتساءل : متى ستفرج عن ذلك المخزون فى عقلك ؟! كنت متأكدة أنك ستفرج عنه ؛ لكن ( كل شىء بوقته حلو )... حمدا لله على سلامتك ؛ ولا بأس طهور ان شاء الله ...||وبعدين يامصعب انت ماكنتش عارف ان حقنة البنج دى بياخدوها علشان يتخدروا ؟ ايه لازمتها المقاومةولا هيا بقت فى دمك خلااااص ...||ثم لاتعجب من كل هذا الحب ؛ فأنت تستحقه - باذن الله ولا أزكيك على الله \\_واذا أحب الله عبدا نادى جبريل انى أحب فلانا فأحبه ........||دمت متألقا ؛؛؛؛ ومعافى ..........</"

[[comments]]
author = "اميرة هشام"
date = "2007-03-09T07:58:00+01:00"
avatar_url = ""
profile_url = "https://www.blogger.com/profile/16048503349469323361"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_08.html#c2822244727011520515"
text = "حمدالله عالسلامة يامصعب||||مكنش له لازمة تحكي بالتفصيل||||عشان متثيرش احقاد ناس معندهمش اصحاب كتير اوي كدة بتحبهم||||قصدي ماشاء الله اللهم مالاحسد||||ربنا يخليلك اصحابك يارب وميحرمكوش من بعض ابداااااا"

[[comments]]
author = "غير معرف"
date = "2007-03-09T11:21:00+01:00"
avatar_url = ""
profile_url = ""
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_08.html#c3818362067263497304"
text = "حمدا لله على سلامتك يا مصعب||احنا اصحابك عالماسنجر افتقدنا وجودك||ومعرفناش الا بعد ما شفناك اون لاين||حمدا لله على سلامتك والحمد لله على عودتك لاخواتك واحبابك واصحابك وللموقع ولشغلك وللماسنجر بالسلامة"

[[comments]]
author = "محمد عـنـانـى"
date = "2007-03-09T18:39:00+01:00"
avatar_url = ""
profile_url = "https://www.blogger.com/profile/08868833358737956721"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_08.html#c982802949029669993"
text = "بعد السلام||اوع تكون عيان ومقلتش انا شايف الى كل بيحمد الله على سلامتك ده علشان القصه ولا اه نسيت اطبع القصه واقول للعيال يذكروها ولا رايك اه||بوست حلو مع كميه التحريف الموجود فى الحقيقه ربنا يعزك||والف سلامه عليك"

[[comments]]
author = "مُصْعَب إِبْرَاهِيم"
date = "2007-03-10T01:47:00+01:00"
avatar_url = ""
profile_url = "https://www.blogger.com/profile/02204752041306044746"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_08.html#c4380985605158992734"
is_author = true
text = "anonynous||أنا عرفت أنتي مين بس هأحترم رغبتك في إخفاء شخصيتك :) ربنا يسلمك ويبارك فيكي||||ياء||الله يسلمك يا حبيبي||||الحلم العربي||هارد تايمز رواية محبوبة عندنا كلنا :)||الله يسلمك ومتشكر جدا على اسم البتاعة دي :) وبالنسبة لموضوع أختك العملية اللي جاية إن شاء الله :)||||إبراهيم معاك||ماشي يا عم .. الله يسلمك||واحشني ياض||||emz||الله يسلمك، وربنا يخليكي انتي كمان||||أحمد رفعت||مش عارف أقول لك ايه وللا ايه||أنت عملت معايا كتير أوي اليومين دول فلو قعدت أتكلم كتير مش هأعرف أوفيك بجد||وبالله يا أحمد إني أحبك في الله||||عبووود حبيبي||ربنا يكون في عونك في ثانويتك.. نفسي تجيب مجموع كبير علشان أنت دماغك نضيفة أوي والله||||محمد السيد||هتتعوض أكيد إن شاء الله.. عارف والله وحشتني||||walaaz||هاحاول أحفظه حاضر :)||كانيولا كانويلا كانيولا||تقريبا حفظته :)||كل موضوع التعبير ده نسيت فيه حاجات مهمة||بس خير :)||||محمود حبيبي||معلش هي جت فجأة والله||وما تتأسفش.. أنا عارف يا حبيبي أنت كنت هتعمل ايه.. ولا يهمك أنا كويس دلوقتي :)||||أروى الطويل||ربنا ما يوريكي .. احنا هنيجي نسأل عليكي من غير ما تعملي عملية بعد الشر عليكي .. يا رب ما حدش تاني تجيله أي حاجة وحشة||||أميرة البلطجية||ربنا يخليكي يا رب.. آه والله ربنا يجمعنا في الجنة إن شاء الله.. علشان هي وحشتني أوي||الله يسلمك||||أحمد الدريني||إن كنت ذاكرا لهين الشيئين اللذان وضعتهما في تعليقك.. كنت سأشكرهما لسبب واحد فقط .. أنهما هما سبب التهاب زائدتي :)||الله يسلمك يا حبيبي||||إصرار أمل||كنت خايف والله أنسى حد وده اللي خللاني أتأخر، ومع ذلك في أشخاص قصرت فيحقهم :(||هي المقاومة ما بقتش في دمي.. بس بأحس إن رأسمالي الحقيقي دلوقتي هو عقلي، فأي حاجة بتيجي ناحيته لازم أقاومها بشدة :)||الله يسلمك يا رب ويكرمك||||أميرة هشام||أختي التي لم تلدها أمي ولم أرها بعد، ولكنني أتوق للقياها، ربنا يخليكي يا رب على التعليق الجميل ده وإن شاء الله نتقابل قريبا||||زهور||لا أدري ماذا أقول.. ولكن والله أنا افتقدتكم أكثر.. وأحمد الله أنا أعادني لكم||||محمد العناني||بعد الله يسلمك||أنا آسف بس ما فهمتش تعليقك خالص وقرأته كتير ومع ذلك ما فهمتش..||وحقيقة ايه اللي متحرفة والكلام اللي مش فاهم منه ولا كلمة ده؟||أنا عاوز أعرف قصدك تقول إني محرف حاجات وللا قصدك تقول ايه بالظبط..||لو قصدك كده يبقى ربنا يسامحك مش هأقول لك أكتر من كده.. لو قصدك حاجة تانية يا ريت توضح"

[[comments]]
author = "ola salem"
date = "2007-03-10T01:57:00+01:00"
avatar_url = ""
profile_url = "https://www.blogger.com/profile/16188352166168735049"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_08.html#c7117575362591424925"
text = "على فكرة بعيدا عن التدوينة وحمدا لله على السلامة والكلام ده اللى انت عارف مسبقا ومتأكد انى انبسطت جدا لما انت قمت من العملية بخير||انا انبسط اكتر حالا بعد ما كلمتنى لانى كنتى على حافة الانفجار||بجد بجد بجد انت الصديق الملاك القريب البعيد||مش بكلمك كتير خالص ومش عارفين بعض كويس||بس بنبسط جدا وبحس براحة نفسية غير عادية بعد ما بكلمك وكأنك بتبقى مرسل ليا كجند من جنود الله||شكرا يا مصعب بجد||ربنا يخليك يا رب صديق واخ محترم ومقرب||اختك علا"

[[comments]]
author = "معتـز عبد الرحمن"
date = "2007-03-10T08:28:00+01:00"
avatar_url = ""
profile_url = "https://www.blogger.com/profile/11851524285637979720"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_08.html#c1892277422519591574"
text = "لا بأس طهور إن شاء الله يا مصعب||وحمدا لله على السلامة"

[[comments]]
author = "elkamhawi"
date = "2007-03-10T13:01:00+01:00"
avatar_url = "https://www.blogger.com/img/blogger_logo_round_35.png"
profile_url = "https://www.blogger.com/profile/09923750534350910131"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_08.html#c5373756393118106891"
text = "المهم يا باشا انك قمت بالسلامة||وربنا يخليك للناس اللى بيحبوك||||||||بس جامد البوست"

[[comments]]
author = "واحد"
date = "2007-03-10T14:18:00+01:00"
avatar_url = ""
profile_url = "https://www.blogger.com/profile/00510573640135822699"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_08.html#c1275076653924940790"
text = "مصعب المزروع بقوة اليقين في شغاف محبتنا العميقة....منك لله ..خلتني أعيط من القلق عليك ياولد ...علشان كده حبيت أقولك بيني وبينك أولا ..وبعد كده للناس كلها..ماقاله عبد الله بن قيس الرقيات بمصعب بن الزبير||إنما مصعب شهاب من الله تتجلى عن وحهه الظلماء"

[[comments]]
author = "عبدالله"
date = "2007-03-10T22:24:00+01:00"
avatar_url = ""
profile_url = "https://www.blogger.com/profile/09343087147940790674"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_08.html#c2158863757216586284"
text = "في البدايه الف حمد لله علي السلامه||||بتكتب بطريقه جميله عن اشد اللحظات الصعبه الي ممكن تواجها||||ربنا يباركلك في صحابك و اضح انك محبوب وتستحق كده||||تحياتي"

[[comments]]
author = "غير معرف"
date = "2007-03-10T23:34:00+01:00"
avatar_url = ""
profile_url = ""
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_08.html#c7159300739629502886"
text = "my eyes were full of tears while reading!!||||alf 7amdela 3ala salmtak!!||||fi mizan 7asanatk insha Allah!!||||||rabna ye7'leek li e7'watak w as7abak w kol ely bey7bok ya rab insha Allah||||7amdela 3al salama"

[[comments]]
author = "دعاء عادل"
date = "2007-03-11T00:17:00+01:00"
avatar_url = "https://www.blogger.com/img/blogger_logo_round_35.png"
profile_url = "https://www.blogger.com/profile/10121139069642274432"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_08.html#c6153133602720462636"
text = "حمدلله على سلامتك يا جميل||وانشاء الله تكون اخر مره تتألم فيها||بس انا زعلت بجد يا مصعب لما قريت البوست ده ليه يا ابنى تعمل فى نفسك كده بقى يومين تتعذب كده ومستحمل||بجد يا مصعب برجوك ماتجيش على نفسك اوى كده||و ياريت تخلى بالك من نفسك مش عشانك عشان كل اللى بيحبوك||عارف والحته الى موتتنى من الضحك انك تفيت فى وش الممرضه ونفسى اعرف كانت بتعملك ازاى بعد كده .||انت انسان جميل اوى يا مصعب"

[[comments]]
author = "الدبور"
date = "2007-03-11T03:06:00+01:00"
avatar_url = ""
profile_url = "https://www.blogger.com/profile/06164252134224093258"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_08.html#c612228341861414359"
text = "هو ده البوست و لا بلاش||||توضيح بخصوص البوست بتاعي اللي عمل قلق وزعل ناس مني انا بحترمهم وبحبهم||تم توضيح وجهه نظري في بوست منفرد||اقراه وقولي ليا رايك ؟||رايك يهمني||||تحياتي||الدبور"

[[comments]]
author = "غير معرف"
date = "2007-03-11T11:38:00+01:00"
avatar_url = ""
profile_url = ""
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_08.html#c7144424345719933326"
text = "الف حمد الله علي السلامة يا فندم ... معلش متاخرة بس و الله ماكنتش اعرف غير لما شفت البلوج||يللا معلش تعيش وتاخد غيرها||عجبني جدا البوست كتبته بطريقة شيقة جدا||اكتر حاجة عجبتني \"الالم العالمي للناشئين\" جامدة جدا :)))"

[[comments]]
author = "Memo"
date = "2007-03-11T15:02:00+01:00"
avatar_url = "https://www.blogger.com/img/blogger_logo_round_35.png"
profile_url = "https://www.blogger.com/profile/10558380451353614646"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_08.html#c8881540702306678842"
text = "الف حمداله علة السلامه انا كان نفسي اجيلك بس هبعتلك حد||الف الف سلامه عليك يا مصعب الخير يا جميل||||وترجع بالسلامه ان شاء الله"

[[comments]]
author = "غير معرف"
date = "2007-03-16T14:34:00+01:00"
avatar_url = ""
profile_url = ""
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_08.html#c3857402470256598591"
text = "بجد زعلانه اووووي اووي اني شفت البوست ده متأخر وعرفت متأخر||بس انا وبكل اسف كنت مسافره ومش كنت بدخل نت نهائي||اولا حمد الله على السلامه وربنا يتم شفاك على خير||تانياً ماشاء الله ربنا يبارك فيك الناس بتحبك اوي ماشاء الله||والله وحلفات اتحاسب عليه يوم القيامه انا لو كنت عرفت وقتها كنت كلمتك||من غير ليه ... بس برغم ان مافيش مابينا تعامل شخصي وتقريبا مادخلتليش البلوج غير مره واحده بس كنت هحس انو لازم اتصل واقولك حمد الله على السلامه||طريقتك وانتي بتحكي الوقائع تحفة على فكره||جمد الله على السلامه بجد انا عارفه متأخره وجايز مش فارقه معاك بدري او متأخر بس انا كان نفسي اقولها بدري شويه||ربنا يعافيك دايماً"

[[comments]]
author = "nour"
date = "2007-03-17T16:52:00+01:00"
avatar_url = "https://www.blogger.com/img/blogger_logo_round_35.png"
profile_url = "https://www.blogger.com/profile/13625151471195771582"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_08.html#c9210705593431133634"
text = "الف سلااااامه عليك يا معلم||يا عم ده الزايدة دى لعب عيااال||عملتها و انا فى تالته اعدادى||:))))))||لا لا بجد الف سلامه و معلش بس احلى حاجة فى الحوار وقفة الناس دى كلها معاك ربنا يحيي فيك الناس اكتر يا معلم"

[[comments]]
author = "LAMIA MAHMOUD"
date = "2007-03-19T09:37:00+01:00"
avatar_url = ""
profile_url = "https://www.blogger.com/profile/05758996758350593398"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_08.html#c8719419459225339712"
text = "المرة دي شوفت الكليب .. هيييييييييييييه||||وبعدين في حد يبقى داخل يعمل العملية وبيفكر في اي ار يا مصعب .. واضح كمان ان جول فيرن عامل معاك شغل كبير||||وبعدين اية كل الناس دي .. بس انت تستاهل"

[[comments]]
author = "Camellia Hussein"
date = "2007-03-19T20:52:00+01:00"
avatar_url = ""
profile_url = "https://www.blogger.com/profile/15735434869492317332"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_08.html#c2067723827362369462"
text = "اكتر حاجة عجبتني في البوست رقم الايداع .,...بشوية تخمين أتاح لي الفرصة ان اقول لك بنفسي حمدا لله علي السلامة||..كاميليا حسين"
