[[comments]]
author = "Angel"
date = "2007-04-18T00:27:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiBB0l4hrjG6YwtvhjW50fBh0qgKq1tVvrgLvMFCjsXpssq7_JP-x8X_O-MS1tfHxAZZqqNd-3BYZZFPAmK1ODxYlNBTQgTUIZzC_4y723TdF-F8UeoYNZx4f4C2T2Qxw/s220/WXD57840.jpg"
profile_url = "https://www.blogger.com/profile/14016929410723462752"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_30.html?showComment=1176848820000#c7312100276842038630"
text = "WoOoOoOoOoOow<br /><br />حروف الصمت..<br />ألواني<br />وصوتي ..<br />بوح كتماني<br /><br />كلام جدا راااااااااائع وبيتحس اوووي<br /><br />الله يعطيك العافيه مصعب"

[[comments]]
author = "العـابــــــــره"
date = "2007-04-06T02:04:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjirpnB1jlU7bWG0V6oQLFugE9LdCMmPYCneTsqfh2X7QHo46m-E-v1cdrCVcEqswMoAqKAfbCjRjc-xZIYckh1rq-QCi0KDc5B3O1mEHShrSAU5djGV2RpP_EXGiIOJA/s220/amanyyyyyy.jpg"
profile_url = "https://www.blogger.com/profile/02540503067719024339"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_30.html?showComment=1175817840000#c2819684144779718557"
text = "بعد كل الكلام الجميل ده<br /> تفتكر انا ممكن اقول ايه<br /><br />قد اصبحت<br />حروف الصمت<br /> ألوانى<br />وصوتى بوح <br />كتمانى<br /><br />    تحياتى<br />العابره"

[[comments]]
author = "Anonymous"
date = "2007-04-02T12:23:00.000+02:00"
avatar_url = ""
profile_url = ""
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_30.html?showComment=1175509380000#c6616418464709599523"
text = "قصيدة جميلة فعلا يا مصعب ... ربنا يوفقك<br /><br />فاطمة"

[[comments]]
author = "Dananeer"
date = "2007-04-02T08:19:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhDHGvgY5KpZ8XEsPyzaaDpmG53SKgaqkXxb8lI5SrPxQajlLmAm6PnP9A8howzgOVmDKonJLsRa4LRH3mPV9LiGH0oloUzdu0hFwoqEumr2ko-f1X_ntVu5FpwKKpEWtE/s1600/2141.jpg"
profile_url = "https://www.blogger.com/profile/08617762348908989998"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_30.html?showComment=1175494740000#c6722209050061870185"
text = "حلوه اوى اوى يا مصعب<br />و فىى نفس الوقت بتوجع<br />انت فعلا انسان بجد"

[[comments]]
author = "واحد"
date = "2007-04-01T18:31:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi37t7mh7aHlRtywrfjt3RwMvasU-MSkxiycXUcUK5xqgPJku0lRGLIrnYzSG_pELCPH5S0tUz8cC27131ULK22TSZIKAz4Srx-cwaLO8Qs6UY5YKGfkNKKmFfsFWQpaw/s220/354845.jpg"
profile_url = "https://www.blogger.com/profile/00510573640135822699"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_30.html?showComment=1175445060000#c5814147525259853809"
text = "أنا أعلم أنك تعلم مايدور بذهني حولها ..ومايفسد متعتي بها..لعلك ترقب أن أعلن..والله لا أفعل ..إلا كما يعلن النجم عن ذاته ساعة قيظ الظهيرة<br />عزيزي مصعب .. أنتظر مكالمتك"

[[comments]]
author = "دينا فهمي"
date = "2007-04-01T15:30:00.000+02:00"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/07685435794478937439"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_30.html?showComment=1175434200000#c6537962457544441194"
text = "مصعب هقتلك بجد<br />انت قاطعتني وللا ايه؟؟؟؟؟؟؟؟؟"

[[comments]]
author = "محمد عـنـانـى"
date = "2007-04-01T02:06:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgJnCNkc7USpPPEve4_7xQydB8hcjxa2wpdqlI7T2iRaONRzHUjr5_uu7gd2NjpB_w_sIS2z7IpitEW5BemfGhkyd0BmpH4wk1hSBOINmH1MBYd6A_Va5Og7lA42QG_BA/s220/180431_493177197810_617102810_6572296_2307502_n.jpg"
profile_url = "https://www.blogger.com/profile/08868833358737956721"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_30.html?showComment=1175385960000#c7005251638510354278"
text = "اكيد انت فنان <br />واكيد انا متاثر جدا بما كتبت انت <br />فليرعاك الله ويوفقق"

[[comments]]
author = "السلحفاة تطير"
date = "2007-03-31T23:31:00.000+02:00"
avatar_url = "http://farm2.static.flickr.com/1333/694624784_e83631cc4b_m.jpg"
profile_url = "https://www.blogger.com/profile/14292515793606937051"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_30.html?showComment=1175376660000#c5257291806236867568"
text = "شعر جميل قوى يا مصعب، أخيرا الحوت كشف عن شِعره الجميل"

[[comments]]
author = "ام مليكة"
date = "2007-03-31T15:14:00.000+02:00"
avatar_url = "http://admins.20at.com/do3a2/bentbalad.jpg"
profile_url = "https://www.blogger.com/profile/17720828413632673574"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_30.html?showComment=1175346840000#c2471425329323056017"
text = "عندك حق قوي اي مصاعيبو وعارف ايه اللي يقتلك ويخليك  محتار اكثر كل ما حبايبك دول يصروا على جرحك وانت تصر على سكوتك تحس انك مقتول من جوه ومش قادر تشتكي ويمكن متقدرش تبكي فتحزن"

[[comments]]
author = "Anonymous"
date = "2007-03-31T13:51:00.000+02:00"
avatar_url = ""
profile_url = ""
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_30.html?showComment=1175341860000#c4240598450744348527"
text = "ما بيدك غير احتراف الصمت<br />والوان رسمك ستبهت بمور الوقت<br /><br />حريتك سجنك فانت سجينك وسجانك<br />وفرحك بالمك ووحدتك اصبح كل اشجانك<br /><br />وقلبك الموجوع ادمي هواك وابكي الدموع<br />وذنبك في الحياة انك لغيرك اضأت الشموع<br /><br /><br />طبعا انا مش عارفة سر كتابة القصيدة دي<br />بس حسيت بيك اوي<br />ربنا يفك كرب الجميع يارب"

[[comments]]
author = "Anonymous"
date = "2007-03-31T13:42:00.000+02:00"
avatar_url = ""
profile_url = ""
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_30.html?showComment=1175341320000#c5096639258841025838"
text = "حريتي ..<br />ذاتها سجني<br />و قيد سجّاني<br />..<br /><br />حلو اوى ..<br />عقبال ما تقرالك حاجه مش حزينة بقى <br />:))"

[[comments]]
author = "Camellia Hussein"
date = "2007-03-31T10:56:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg6KZuDgMk9CMt_vMft5N5xJJ0k5I3QTlPdcU-TQPDTAqe5E0uZpMiiL0V6jMKlMsbmPuUaXlDuyN0331exGVVvOkUtkGfdGgwbvWbDcfylIeb8mzTpbcywmnIF-RRV8Vc/s220/reflections.jpg"
profile_url = "https://www.blogger.com/profile/15735434869492317332"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_30.html?showComment=1175331360000#c5685424337482586909"
text = "حلوة أوي .. ووجعتي أوى..صمتي بوح كتماني..حقيقي الله عليك"

[[comments]]
author = "Oma"
date = "2007-03-31T03:52:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgkyjSYWqXw4YBOpvP-96TyE2UNOj8WOswTKULdPzB70B6zrqDGJHhff9VHgxIxelyXO3EKU7YW8ajjqkmMwG9IO7yT-08dfl5BYELB9hvKRZscAn2UfctX1Oxivr_uIw/s220/dancing.jpg"
profile_url = "https://www.blogger.com/profile/00803900258553286221"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_30.html?showComment=1175305920000#c1868634027586362339"
text = "قلبي ..<br />-الذي أهوى ويهواني-<br />شدّ ما أدماني<br /><br />وذنبي.؟!<br />كل ذنبي<br />أنني -دون إرادة مني-<br />شخص إنساني<br /><br />الحته دي روووعه بجد<br />وواضح انها هزت كل الناس<br /><br />وكمان لما كنا عالماسنجر وشفتك كاتب حروف الصمت الواني وصوتي بوح كتماني كنت هعلق اصلا بس النت السخيف بقى نساني<br />بجد تحفه يامصعب<br />(f)"

[[comments]]
author = "Tamer"
date = "2007-03-31T01:04:00.000+02:00"
avatar_url = "http://www.shazly.net/~freehosting/5x1/8hviqn26_swrh003.jpg"
profile_url = "https://www.blogger.com/profile/09456408548642615815"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_30.html?showComment=1175295840000#c55052775694869438"
text = "من المرات القليلة اللى تعجبنى فيها أشعار او بالأصح احاسيس مكتوبة من فترة ليست بالقصيرة <br /><br />مشكلة كبيرة إن الحزن دائما هو صاحب أكبر لمسة للكتابة ,, <br /><br />ربنا يسعدك ,, ويومك أجمل"

[[comments]]
author = "Mony The Angel"
date = "2007-03-31T00:38:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjj4h6hlbKyUklJB5J_QeHmZidZ8mEHO-s5lWgxcP3qUEQSPg4AS0GkKHyrjWHC4Z5y2O3vBW2OY7WPf-cZ0PSVMC-DcEJ6cu6SRYKhpVq1jh6S9ve07RM4o8WgdU_8rxE/s220/mine...jpg"
profile_url = "https://www.blogger.com/profile/02273268851121458996"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_30.html?showComment=1175294280000#c2397025708385569897"
text = "mawqef sa3b akeed<br />w e7saas as3ab tab3an :)<br /><br />kollaha tanaqodaat gamda<br />bas da7 :)))<br /><br />so nice post ya mos3ab :))"

[[comments]]
author = "LAMIA MAHMOUD"
date = "2007-03-31T00:22:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj9Eh5lF-XRHtud8suhl5K4yhMxWsSKxr7oyl2dnkn5hzt8OEtado-gJjkufoVPTgqAHHfWXLwNj3X6sZUl4NWiUVH9XjUZWWmADmu-GQHwrYWvQyo2KAfaSJmBtk1jSw/s220/lets-dance-2.jpg"
profile_url = "https://www.blogger.com/profile/05758996758350593398"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_30.html?showComment=1175293320000#c3731509065476742789"
text = "وذنبي.؟!<br />كل ذنبي<br />أنني -دون إرادة مني-<br />شخص إنساني<br /><br /><br /><br />ده ذنب ناس كتير اوي يا مصعب صدقني<br /><br /><br />بس حلوة اوي بجد"

[[comments]]
author = "ola salem"
date = "2007-03-31T00:18:00.002+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjHFDt3TCMySOaOIfSKy1pm6Fftth7KbZ_FXRBySjWFuS7GVEefAkoeQ4UT7wLJKsNj-DSKxiKoIDNRQxC5kWxU39tZKuKXxikTJMw7maf5gEdDgr9yq5SBrSAtNlvcZw/s220/ola.jpg"
profile_url = "https://www.blogger.com/profile/16188352166168735049"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_30.html?showComment=1175293080002#c2626711457899087227"
text = "الثورى النورى الكلامنجى<br />التدوينة جامدة جدا زى ما قلتلك <br />انت حوت صديق صدقنى<br />منطقى وعاقل وراقى<br />الصورة حلوة يا مصعب جدا<br />اللى فى التدوينة طبعا مش اللى عالماسينجر(:"

[[comments]]
author = "Amira Hassan"
date = "2007-03-31T00:18:00.001+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjKwkbS92ad0pzdLQkHLcToR78dqrG___FfPXTF7qAL6Eml7VawwAzFxt-bHWDIWOwjxbeWWob3GpF-cygVRx34PDduMFcrff3Zh1VxP_o5DrDK-5RHQ3UVoWbveXLLzg/s220/DSC04172.JPG"
profile_url = "https://www.blogger.com/profile/08135823930111514700"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_30.html?showComment=1175293080001#c5896231227880668800"
text = "مش قادره اقولك غير ان ده اكتر شعر اثر فيا بعد محمود دروييش<br /><br />و اللي يعرفني هيعرف انه اثر فيا اووووووووووووووووووووووووووووووو ووووووووووووووووووووووووووووووووووووووووووو وووووووووووووووووووووووووووووووووووووووووووووووووووووووووووووووووووووووووووووووووووووووووي<br /><br />رائع بجد يا مصعب"

[[comments]]
author = "shimaa"
date = "2007-03-31T00:18:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj0Q5LXS1guXTqQoB0zCHEZOdUy6VL3nZOF09JFgFjB2ZKI7SRVGnsEpow8i6WeBwPNL3VCRwjsY6jLM3vTnN_MxCnD6L9Mx9G_Jib_8zjjXWZsvvskr0XyKAIKOdV0xw/s220/hyori-lee[1].jpg"
profile_url = "https://www.blogger.com/profile/10764917878271047406"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_30.html?showComment=1175293080000#c4747774158424373808"
text = "fahma 2dk kwyes blmwakf de:(<br />قلبي ..<br />-الذي أهوى ويهواني-<br />شدّ ما أدماني<br /><br />وذنبي.؟!<br />كل ذنبي<br />أنني -دون إرادة مني-<br />شخص إنساني<br /><br />to7fa 2wii el7ta de bgd"

[[comments]]
author = "أميرة من غير قصر ولا بستان.. ولا الشاطر حسن كمان"
date = "2007-03-31T00:15:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEirdirzKebc0hcGC4MQ6kvVkx2q0MdxprJrl-jqSZ5l_jxE2bWsZVd-Pla_Zla1V4g0FjN5PUa4k3oTN0AO0cgFlRcbwr6XbP-7sqohbU_KGsAtNaDenb4eAJmqzrb0EGE/s220/blogpic5ke.jpg"
profile_url = "https://www.blogger.com/profile/16391848599214933906"
comment_url = "https://mos3abof.blogspot.com/2007/03/blog-post_30.html?showComment=1175292900000#c5782395738263305929"
text = "وذنبي.؟!<br />كل ذنبي<br />أنني -دون إرادة مني-<br />شخص إنساني<br /><br />صدقنى يا مصعب<br />ده احلى ذنب ف الدنيا <br />و الذنب الوحيد اللى مش هاتتعاقب عليه ف الاخره"
