[[comments]]
author = "ام مليكة"
date = "2006-09-12T12:35:00+00:00"
text = "مش ممكن<br />يخرب عقلك يامصعب  دي حلوة قوي يا مصاعيبو<br /><br />هايل هايل هايل"
avatar_url = "http://admins.20at.com/do3a2/bentbalad.jpg"
profile_url = "https://www.blogger.com/profile/17720828413632673574"
comment_url = "https://mos3abof.blogspot.com/2006/09/blog-post_12.html?showComment=1158064500000#c9134510291097481368"

[[comments]]
author = "محمد السيد..مش حاسكت"
date = "2006-09-12T12:46:00+00:00"
text = "إيه الجمال ده يا عم الريس ...<br />خلي بالك إنت علي نفسك بس  ...<br /><br />بس بجد جميلة والله .... ماتسيبك من العالم بتوع عشرينات واعمل لك انت واحد ....... بس خدني معاك !!!<br /><br />مش ناوي تيجي اسكندرية برضه؟"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/15123433931771567833"
comment_url = "https://mos3abof.blogspot.com/2006/09/blog-post_12.html?showComment=1158065160000#c7716429813528089435"

[[comments]]
author = "Anonymous"
date = "2006-09-12T19:26:00+00:00"
text = "I am afraid from crocodiles, I even don't like the brand LACOSTE because of that."
comment_url = "https://mos3abof.blogspot.com/2006/09/blog-post_12.html?showComment=1158089160000#c4199850627614205692"

[[comments]]
author = "Anonymous"
date = "2006-09-12T22:25:00+00:00"
text = "إلا صحيح، هو مش سمسم ده يبقى من صيد البحر؟!<br />زي السلحفاة وزي سمك القرش وزي سمك البلطي؟!<br /><br />طعمه ازاي بقىىىىى؟!"
comment_url = "https://mos3abof.blogspot.com/2006/09/blog-post_12.html?showComment=1158099900000#c7050641232027515367"

[[comments]]
author = "مُصْعَب إِبْرَاهِيم"
date = "2006-09-29T13:37:00+00:00"
text = "إهئ إهئ إهئ<br /><br />توفي إلى رحمة الله تعالى .. التمساح سمسم<br /><br />للفيد الرحمة و لأسرته الصبر و السلوان..<br />هذا و  تصلى الجنازة و يقام العزاء على روح الفقيد في منور عمارتنا!"
is_author = true
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgODM4s6ekNMNbaTTY1KX0U5U6D_NmyJiuN60nsF_0DI--Js7olkUmXZpRkimU0I2gC8pwXBGOZKcTWjzCKgs6XJHV-A4s5wS7B14z2CPMUU-zrXc2WZZqVk9n76-iUZg/s220/mosab_profile.jpg"
profile_url = "https://www.blogger.com/profile/02204752041306044746"
comment_url = "https://mos3abof.blogspot.com/2006/09/blog-post_12.html?showComment=1159537020000#c6632340703438773155"
