[[comments]]
author = "ساعه الغروب"
date = "2007-11-30T00:47:00.000+01:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh-BfGCSmQul27LefumFQhk_DqA90sjigwS-U-seep4BgWJ8SQwbJCJqx6NblkiF2mTSHgoYz8Lpu0QNyUhc8repFIWl9D1O0ieZx9wKXniLSCRaFBJFxALqzNuMlhfe9w/s220/294284_10150301520531946_677441945_8352669_962921791_n.jpg"
profile_url = "https://www.blogger.com/profile/01070664710874666846"
comment_url = "https://mos3abof.blogspot.com/2007/11/blog-post_25.html?showComment=1196380020000#c1293120656837934367"
text = "رحمه الله واسكنه فسيح جناته <br /><br />وكل سنه وانت طيب وبافضل حال"

[[comments]]
author = "اسامة يس"
date = "2007-11-29T22:53:00.000+01:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiQB_ueIHz_5973BgWB_vc7wXqwXpD5sx0FlNrNCCjW6eHTA_oUOE2grKc-Z9vDq8fp4oCvE12XfYO6RKBwCBxfY4hZs8DQpR4IJ__PhTFBPAMfCrS3yDrYH4gEAq8R0Tw/s149/%D9%8A%D8%B3.jpg"
profile_url = "https://www.blogger.com/profile/05313390111101507418"
comment_url = "https://mos3abof.blogspot.com/2007/11/blog-post_25.html?showComment=1196373180000#c1408774819147566800"
text = "كدت ابك يا صديقي ولولا اني تمالكت نفسي لفرت دمعة...<br /><br />كل سنه وهو في نعيم مقيم ..."

[[comments]]
author = "الحلم العربي"
date = "2007-11-29T19:26:00.000+01:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjTdgiumpfKeU2naMdOAloE5M1oaYUxfArfOm-cYGHKhHod2DcWaAVebA6VKkbv9pk9uWp_Z-NnV5w2gnJ4EA-IYjm_5-fcg71JsKExv1ITSlGWrTF8vM3eDe4tS8_NRSM/s220/strang3.JPG"
profile_url = "https://www.blogger.com/profile/08895879839574889127"
comment_url = "https://mos3abof.blogspot.com/2007/11/blog-post_25.html?showComment=1196360760000#c4214125722606736738"
text = "كل سنة وهو طيب و فرحان في الجنة بأبناؤه المشرفين<br />وأكيد هو في صحبةأحسن بكتييير دلوقتى إن شاءالله<br />ربنا يرحمه و يجمعنا بيه في الجنة إن شاء الله<br /><br />ما قدرتش أقرأ التدوينة اللى في اللينك تانى لأن لسة أثرها في نفسي من أول مرة قرأتها وبكيت لها <br /><br />طبعا انت محضر له هدية محترمة من دعاء ولد صالح ربنا يجعله رحمة له <br /><br />تحياتي"

[[comments]]
author = "Anonymous"
date = "2007-11-28T16:13:00.000+01:00"
avatar_url = ""
profile_url = ""
comment_url = "https://mos3abof.blogspot.com/2007/11/blog-post_25.html?showComment=1196262780000#c5268195590203380492"
text = "متزعلش مني يا مصعب لاني لم اعطك حقك علي كـأخ صغير و صديق عزيز<br /><br />اعذر مشاغلي و انشغالي و تغيبي عن كثير من الاخداث المهمة معك<br />للاسف انا مقدرتش اكون معاك في ازمتك الدراسية <br />ولا في مواقف كتير<br />والله مش بإيدي و بجد بزعل ان مش عارفة اعمل لك حاجة<br /><br />دايما ادعي لوالك و ربنا يصبرك<br />في اية معناها ان اليتامي ده اصلاح لهم يعني ممكن انت تكون اكتسبت قوة من كده<br />الي اقصده<br />ان الرسول مثلا عليه الصلاة و الصلام كان يتيم الاب و الام وده اكسبه صلابة<br />ربنا معاك يا مصعب و بجد انا موجودة اي وقت انت عندك مشكلة انا هنا<br /><br />نونا المجنونة"

[[comments]]
author = "عمر محمود"
date = "2007-11-27T16:31:00.000+01:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgJtHKs88p1wHzsQ93Tc3kT_jleEXS0RxQZQAh2Kx403hAQuwv09INg-6JH-G0fhBKmiuKVJGvdeTFHnHOxk1_uX45lE0DDEb7jyEb3yhYEzZvvWd8NuBEw6dVEHUuQovQ/s220/Titel_01.gif"
profile_url = "https://www.blogger.com/profile/12161387737338769681"
comment_url = "https://mos3abof.blogspot.com/2007/11/blog-post_25.html?showComment=1196177460000#c6071797323433033429"
text = "اللهم رفقة الجنة خير لنا <br />فلا تحرمنا إياها<br />كل سنة وهو بجد طيب<br />ومصعب بجد أطيب"

[[comments]]
author = "MarwaAshraf"
date = "2007-11-25T22:28:00.000+01:00"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/12117806503113618382"
comment_url = "https://mos3abof.blogspot.com/2007/11/blog-post_25.html?showComment=1196026080000#c2743316634999492670"
text = "كل سنة وإنت طيب يا عمو أحمد... يارب ربنا يجمعنا معاك في الجنة"

[[comments]]
author = "weswes"
date = "2007-11-25T22:26:00.000+01:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiw4snw0O4r8EYHQhiu7PCP3YXbjsOVmNj5zsVG2NmG_iJW8qfvdrvDKQVVXpYEQyxkgnLEal7LDhjHT9wSDmHEaztJc2mql6BgND38sUt9YXFFoG0Id5pU9R8WI3ItEKo/s220/IMG_0034.JPG"
profile_url = "https://www.blogger.com/profile/04810150175952124524"
comment_url = "https://mos3abof.blogspot.com/2007/11/blog-post_25.html?showComment=1196025960000#c2625126727913291718"
text = "كل سنه وانت طيب وفى مكان احسن ومع النبين والصدقين<br />واحد شافت حسن تربيتك فى ابنك"

[[comments]]
author = "شيرين"
date = "2007-11-25T14:04:00.000+01:00"
avatar_url = "http://photos-279.ll.facebook.com/photos-ll-sctm/v99/129/13/717256279/n717256279_214552_3758.jpg"
profile_url = "https://www.blogger.com/profile/08718885335246773468"
comment_url = "https://mos3abof.blogspot.com/2007/11/blog-post_25.html?showComment=1195995840000#c1554828039794936372"
text = "كل سنة وانت وانت في أحسن مكان<br /><br />وبجد بجد شكرا قوي على هديتك لينا.. وإن شاء الله هنردهالك دعاء صادق من قلوبنا."

[[comments]]
author = "همسة قلم"
date = "2007-11-25T13:57:00.000+01:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEii4ggxdv3eA4vn2CYG-b9gnvLLncfGMI7cDi3rZ745Y1YhfoeVBQ_jbwllHGEMDbghjUdisPRY1YZZUmKocY_lc9BdcNeEPdMtDjhc1mI5oky2_pjETA3EpfL8EZ1x9Q/s150/*"
profile_url = "https://www.blogger.com/profile/17533968248895951396"
comment_url = "https://mos3abof.blogspot.com/2007/11/blog-post_25.html?showComment=1195995420000#c4362663928212889990"
text = "وأنا كمان أبي واحشني أوي:(<br /><br />ربنا يرحمهم ويجمعنا بيهم في الجنة"

[[comments]]
author = "Lens Geek"
date = "2007-11-25T13:25:00.000+01:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhDH6cac8DhCu85r5fVw0KJDQyTSgnbUN_on5yZRrtKG44soaS5wrAZnDMZBnmYItm4PSgM5Be26Q5kswvv4w84fGE-zjxA4uFGBZW67q5kjJzKnPEAcvpMpdz-KsYUpg/s220/Ahmed2.gif"
profile_url = "https://www.blogger.com/profile/08391635125789451063"
comment_url = "https://mos3abof.blogspot.com/2007/11/blog-post_25.html?showComment=1195993500000#c8841893599539408953"
text = "الله يرحمه، خلف اوفى الابناء، و اطيب الرجال، و أجيك الجيــــكس :)<br /><br />رحمه الله و كل عام وانت مع النبي عليه الصلاة والسلام في الجنه"

[[comments]]
author = "أميرة من غير قصر ولا بستان.. ولا الشاطر حسن كمان"
date = "2007-11-25T10:28:00.000+01:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEirdirzKebc0hcGC4MQ6kvVkx2q0MdxprJrl-jqSZ5l_jxE2bWsZVd-Pla_Zla1V4g0FjN5PUa4k3oTN0AO0cgFlRcbwr6XbP-7sqohbU_KGsAtNaDenb4eAJmqzrb0EGE/s220/blogpic5ke.jpg"
profile_url = "https://www.blogger.com/profile/16391848599214933906"
comment_url = "https://mos3abof.blogspot.com/2007/11/blog-post_25.html?showComment=1195982880000#c4073190648874381642"
text = "رحمك الله واسكنك فسيح جناته<br /><br />وكل سنه وانت طيب<br />كل سنه وانت اكثر فخر بأن ابنك هو \"مصعب\""

[[comments]]
author = "Salma Amer"
date = "2007-11-25T09:59:00.001+01:00"
avatar_url = "http://farm2.static.flickr.com/1132/1365681113_f20faceeb5.jpg?v=0"
profile_url = "https://www.blogger.com/profile/08716194696950096714"
comment_url = "https://mos3abof.blogspot.com/2007/11/blog-post_25.html?showComment=1195981140001#c3876651573223637516"
text = "الله يرحمة رحمه واسعة <br />وكل سنة وانت اطيب واحلى وتفتكره وتدعو له"

[[comments]]
author = "قضية عم أحمد    Ahmed Case"
date = "2007-11-25T09:59:00.000+01:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgV-wcarXLkgWhQQil5kwuYh3wp9AEWNEDcLSaQD2LN0vM_G4H9YJFgqa0XczHwll6yiqoYqdHkRIaOBrs7mUlUTV8btyQ-yKEFvsGrNIWlN99lkjHG8LD-zKscO0MMuVA/s220/DSC_7364.JPG"
profile_url = "https://www.blogger.com/profile/07000569434293484731"
comment_url = "https://mos3abof.blogspot.com/2007/11/blog-post_25.html?showComment=1195981140000#c4880580750644798933"
text = "كل سنة وانت طيب انا شفت طيبتك وكرمك وحبك وحاجات كتير حلوة .. <br /><br />كل سنة وانت طيب وانت في النعيم <br />كل سنة وانت مع النبي في الجنة .. <br /><br />كل سنة وانت طيب ... <br /><br />ابنك اللى مشفكش بس شاف بعضك .."
