[[comments]]
author = "روح"
date = "2009-04-09T02:58:00.000+02:00"
avatar_url = "http://redondowriter.typepad.com/photos/uncategorized/268573778_a71bfed930.jpg"
profile_url = "https://www.blogger.com/profile/08902136818874003625"
comment_url = "https://mos3abof.blogspot.com/2009/03/23.html?showComment=1239238680000#c8691387276163748859"
text = "عام مليء بالقرب من الله<br />وهنيئا لك الصحبة الصالحة<br />والزوجة الصالحة ان شاء الله"

# [[comments]]
# author = "Anonymous"
# date = "2009-04-02T10:45:00.000+02:00"
# avatar_url = ""
# profile_url = ""
# comment_url = "https://mos3abof.blogspot.com/2009/03/23.html?showComment=1238661900000#c2237070452346632626"
# text = "إلى مدوني مصر الأحرار <br />السيد الفاضل  صاحب مدونة /صـ( الخير )ـعب - رب الكيبورد و الماوس<br /> <br />تحية طيبة وبعد<br /><br />شباب مصر الأوفياء <br />أمل الحرية وبناة المستقبل<br />ندعوكم للمشاركة معنا في <br />التحالف الوطني ضد التزوير <br />تحالف يضم كافة القوى الوطنية الموجودة على الساحة المصرية <br />نهدف إلى فضح وتوثيق كافة أشكال التزوير التي تتم في الانتخابات المصرية <br />نهدف لنشر الوعي الانتخابي وثقافة المشاركة و مبدءا المساواة والحرية <br />ندعوكم للمشاركة معنا بالإدلاء بشهادتكم و أرائكم حول تزوير الانتخابات وما هو منشور <br />ندعوا كل صاحب كلمة حرة للتعبير معنا عن رأيه في هذا الداء وطرح صور للدواء <br />ندعوا كل شريف حر يستطيع مساعدتنا للمشاركة معنا بما لدية من إمكانيات ومواهب ووقت<br />و نرجوا منكم المساهمة معنا في نشر إعلانات الموقع والجروب والقناة على مدوناتكم الشخصية في سبيل نشر الحق والعدل ومن باب المشاركة في التوعية والتوثيق لحقيقة هذا النظام المزور لإرادة الشعب <br />نرجوا ممن يضع الإعلان لدية إبلاغنا عبر أيميل الموقع لوضع أسم موقعة او مدونتة ضمن قائمة المواقع الصديقة لدينا <br />شاكرين لكم حسن تعاونكم معنا <br /><br />موقعنا www.sgelalmozwreen.com سجل المزورين <br /><br />لتحميل إعلانات الموقع هنا <br />http://sgelalmozwreen.com/images/e3lan-1.gif<br />أو<br />http://sgelalmozwreen.com/images/e3lan-2.gif<br />أو<br />http://sgelalmozwreen.com/images/e3lan-3.gif<br /><br />لتحميل إعلانات قناة سجل المزورين على اليوتيوب<br />رابط القناة http://www.youtube.com/Sgelalmozwreen <br /><br />الاعلانات <br />http://sgelalmozwreen.com/uploads/you tube.jpg<br />أو <br />http://sgelalmozwreen.com/images/1.gif<br />أو<br />http://sgelalmozwreen.com/images/1%5C%27%5C%27%20copy.gif<br />أو<br />ولتحميل إعلان جروب الفيس بوك <br />رابط الجروب http://www.facebook.com/group.php?gid=57329097688 <br />الاعلانات <br />http://sgelalmozwreen.com/images/11%5C%27%5C%27.gif<br />والسلام عليكم ورحمة الله وبركاته <br />سجل المزورين"

[[comments]]
author = "david santos"
date = "2009-03-30T00:10:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhKcTvexjr6LUQ-DTvSon30w8huz5vYXVGOpfFpYWCmGdej6VsgNt0xWBMnVbxJCnCPBjulluIf0kENAVluI_c9na-Sm6Y-NhSYi_YYn6MCjWOfyJJ1mfGYK3xO1yB71w/s220/bg_profile.jpg"
profile_url = "https://www.blogger.com/profile/08976825493652779441"
comment_url = "https://mos3abof.blogspot.com/2009/03/23.html?showComment=1238364600000#c2866233075283822408"
text = "Excellent posting!!!<br />Happy week!!!!"

[[comments]]
author = "Amimi Houssainy"
date = "2009-03-26T14:00:00.000+01:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgZ5U4WlzUss0uPIk6CIWOP39PIGRIka0M7X7oxQFac3IA96TWm6eSkn9diM-POEGc0GEEz-HFkLZbr4bOmskrn3xWyOUmDVdCHlqDBPy-seDBJISTCwtdUdRokxve19_M/s220/coustime_album.jpg"
profile_url = "https://www.blogger.com/profile/11706534749857063059"
comment_url = "https://mos3abof.blogspot.com/2009/03/23.html?showComment=1238072400000#c6749034461267081299"
text = "rabena yetamem Lakoma Norkom Ya rab ....Ya a3az Sadi9 Chofto fi 7ayati :) we koli Sana we nta  ubuntu  and Apple Mac..."

[[comments]]
author = "Mony The Angel"
date = "2009-03-21T03:03:00.000+01:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjj4h6hlbKyUklJB5J_QeHmZidZ8mEHO-s5lWgxcP3qUEQSPg4AS0GkKHyrjWHC4Z5y2O3vBW2OY7WPf-cZ0PSVMC-DcEJ6cu6SRYKhpVq1jh6S9ve07RM4o8WgdU_8rxE/s220/mine...jpg"
profile_url = "https://www.blogger.com/profile/02273268851121458996"
comment_url = "https://mos3abof.blogspot.com/2009/03/23.html?showComment=1237600980000#c995674837690997748"
text = "kol sana wenta m3aha :)"

[[comments]]
author = "ياء"
date = "2009-03-20T22:29:00.000+01:00"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/09927085065103433253"
comment_url = "https://mos3abof.blogspot.com/2009/03/23.html?showComment=1237584540000#c6204497208803295895"
text = "كل عام وانت ب1000 خير<br /><br />وكل سنه وانت طيب"

[[comments]]
author = "تــسنيـم"
date = "2009-03-18T20:12:00.000+01:00"
avatar_url = "http://1.bp.blogspot.com/-unAk4PRAf0k/T2EgcoozgEI/AAAAAAAAB5c/zOYIlMms6vo/s220/%25D8%25A7%25D9%2584%25D9%2585%25D9%2586%25D8%25B5%25D9%2588%25D8%25B1%25D8%25A9%2B1.jpg"
profile_url = "https://www.blogger.com/profile/17390698031839586224"
comment_url = "https://mos3abof.blogspot.com/2009/03/23.html?showComment=1237403520000#c1840599322885171072"
text = "ربنــا يديمهــا عليك نعمـــة<br /><br /><br />:))"
