[[comments]]
author = "Anonymous"
date = "2008-04-23T09:59:00.000+02:00"
avatar_url = ""
profile_url = ""
comment_url = "https://mos3abof.blogspot.com/2008/04/blog-post_21.html?showComment=1208937540000#c8878982274208241408"
text = "أزال أحد مشرفي المدونة هذا التعليق."

[[comments]]
author = "الحلم العربي"
date = "2008-04-22T21:14:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjTdgiumpfKeU2naMdOAloE5M1oaYUxfArfOm-cYGHKhHod2DcWaAVebA6VKkbv9pk9uWp_Z-NnV5w2gnJ4EA-IYjm_5-fcg71JsKExv1ITSlGWrTF8vM3eDe4tS8_NRSM/s220/strang3.JPG"
profile_url = "https://www.blogger.com/profile/08895879839574889127"
comment_url = "https://mos3abof.blogspot.com/2008/04/blog-post_21.html?showComment=1208891640000#c511206408644225811"
text = "و أنا بدوري أهنئ شعوب المنطقة و أهيب بكل الذين شاركوا في الاستقلال <br />و أنصح الزعماء في المنطقة بالتعاون المشترك مع زعماء المناطق المجاورة و العمل على انشاء سوق مشتركة و فتح الحدود لسكان المناطق المجاورة مع العمل على تأمين الدولة من الدخلاء و الحاقدين و أصحاب المصالح الشخصية و الناقمين على الاستقلال (و اللى متغاظين ان مناطقهم ما استقلتش )<br />و من موقعي هذا أعلن أننا نحن سكان مدينة العبور سوف نحارب العدو حتى ننتصر و نستقل بمدينتنا و سوف نبذل من أجل ذلك كل ثمين و نفيس واضعين أمام أعيننا التجربة الحلوانية كمثال حي <br />و اشكركم <br />مديحة حاتم<br />مدينة العبور<br />القاهرة"

[[comments]]
author = "Salma Amer"
date = "2008-04-22T09:57:00.000+02:00"
avatar_url = "http://farm2.static.flickr.com/1132/1365681113_f20faceeb5.jpg?v=0"
profile_url = "https://www.blogger.com/profile/08716194696950096714"
comment_url = "https://mos3abof.blogspot.com/2008/04/blog-post_21.html?showComment=1208851020000#c960812610917666472"
text = "بالاصالة عن عن نفسية وعن شعب القاهرة اقدمة التهاني لشعب حلوان الشقيق وخصوصا الاخ المناضل هواري <br />بس عايزة اسأل سؤوال مين أبو رجيلة دة ؟؟؟"

[[comments]]
author = "حنة"
date = "2008-04-22T01:59:00.000+02:00"
avatar_url = "http://bp2.blogger.com/_v4oJSvfy-oU/R9mr3J5nn5I/AAAAAAAAANY/4jO5btBksag/S220/Picture+013.jpg"
profile_url = "https://www.blogger.com/profile/15883050286032618417"
comment_url = "https://mos3abof.blogspot.com/2008/04/blog-post_21.html?showComment=1208822340000#c3858185281523475022"
text = "مبروك لشعب حلوان <br />عقبال استقلال الجيزةوضواحيها<br />بس عاوزين قيادة ملهمة وقائد معلم زي الهواري<br />وبنأمل فيك يا مصعب تلعب الدور ده<br />الله الهرم فيصل"

[[comments]]
author = "صاحب المضيفة"
date = "2008-04-22T01:08:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhDN_UQtt5dcg7mN6V-HaKHt0g1FU7xvoK8oRMwkWRLkyatyHJ1MMHC5x2OvInC9NOuilnKdQVe06-oP5eMapajnpULPVvBp9MOB2W4VTgy2H4zaVN3Zv_fajIlEl1L22U/s220/parisnajd127168.JPG"
profile_url = "https://www.blogger.com/profile/12611574570083465867"
comment_url = "https://mos3abof.blogspot.com/2008/04/blog-post_21.html?showComment=1208819280000#c2498274217551579219"
text = "لكن الل أعرفه الان المحافظات رجعت قواعدها تاني سالمة غانمة <br /><br />وكله رجع مكانه تاني من غير شوشرة ولا بهدلة <br /><br />مش عارف اي الخبرين أصح من التاني <br /><br /><br />تحياتي يا مصعب باشا"

[[comments]]
author = "dead man"
date = "2008-04-21T13:38:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgblVMh7Nlr7ton4EF6_WEIvx8uFAb-eyxAuL1LWv4FXTV92r6gCplvVR4alR4sN7zoTvIKKNYNdwspZiK_KxIj22bYHSiigq8zeWWpnNoyw8kdaUTj-R6MOh9v1vhBvNg/s220/wait.jpg"
profile_url = "https://www.blogger.com/profile/10592260848284665609"
comment_url = "https://mos3abof.blogspot.com/2008/04/blog-post_21.html?showComment=1208777880000#c4374415647659543118"
text = "سيد مصعب .. ان شعب حلوان المناضل يشكرك من صميم قلبه علي دعمك الواضح في الوقت الذي تخلت فيه دول كبرى عن إعلان تأيدها لاستقلال حلوان.. <br /><br />وانا اتفق مع الاستاذ احمد عبد الفتاح في تصحيح المعلومة المغلوطة حول الهتافات ، فقد اجمعت الجماهير المطحونة في ميدان المحطة علي هتاف الله حلوان أبو رجيلة، وبمناسبة اعياد الربيع تنوي بعض الجماهير تغيير الهتاف الى الله الوطن الحديقة اليابانية <br /><br />وقبل أن أنهى كلامي اوجه رسالة أشكر فيها من قدموا أرواحهم علي مدار التاريخ حتى تحصل حلوان علي استقلالها التام.. وشكرا<br /><br />تصفيق حااااااااااد"

[[comments]]
author = "MariumaZ"
date = "2008-04-21T12:59:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg9giUV2iCTwwtfQoUxjZXLMjO4Scq0iKCUdYMCgmovIiMOde9B26aqPY_6wwiZy8PHqssu8sQSZDgaBjnhd_kQL0aeEev2mUQs1l-tOOUp6mUNQV2JilPBktEhrS_AHqU/s220/IMG_0084.jpg"
profile_url = "https://www.blogger.com/profile/12796121153780883763"
comment_url = "https://mos3abof.blogspot.com/2008/04/blog-post_21.html?showComment=1208775540000#c5961164345419051297"
text = "كنت أقصد الشعار المتعارف عليه<br /><br />الله ... هايبر وان ... المحور"

[[comments]]
author = "MariumaZ"
date = "2008-04-21T12:57:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg9giUV2iCTwwtfQoUxjZXLMjO4Scq0iKCUdYMCgmovIiMOde9B26aqPY_6wwiZy8PHqssu8sQSZDgaBjnhd_kQL0aeEev2mUQs1l-tOOUp6mUNQV2JilPBktEhrS_AHqU/s220/IMG_0084.jpg"
profile_url = "https://www.blogger.com/profile/12796121153780883763"
comment_url = "https://mos3abof.blogspot.com/2008/04/blog-post_21.html?showComment=1208775420000#c2294815659358410478"
text = "الأستاذ مصعب الخير القاطن بحي الجيزة زيي يعني... أود أن أضم صوتي إلى صوتك وأهني بجوار شعب حلوان شعب 6 اكتوبر العظيم (اللي لا حضر العبور ولا نيلة)... وأود ان انوه أيضاً بوجود أقارب وأصدقاء لي في المحافظتين المستقلتين<br />العار المتعارف عليه في أكنوبر كما سمعت من مصادر مجهولة هو<br />الله ... هايبر وان ... المحور"

[[comments]]
author = "أحمد عبد الفتاح"
date = "2008-04-21T10:53:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjBEankZM8eqnMmm6H2qUuYBC3weT9HKhjtlpU9dAKIiaZsigEwFPgAhS28TpfN9Q8sPR-Gmtwf0ARei7KlSiK-Ujn_KRF9EyyfSEwoDVyR_8Ps5b7XCqqx5vmhSQaMSg/s1600/436599030_8f4a4e7f11.jpg"
profile_url = "https://www.blogger.com/profile/10557032081902417963"
comment_url = "https://mos3abof.blogspot.com/2008/04/blog-post_21.html?showComment=1208767980000#c211663953216546340"
text = "باسم كل شعب حلوان المناضل <br />نشكر الرفيق مصعب رب الكي بور والموس علي تهنئته لنا بمناسبة عيد الاستقلال<br />واحب اصحح معلومة ان الهتاف مش الله ... الوطن ... حلوان <br />ولكن الهتاف هو الله ... حلوان ... ابو رجيلة<br />ولو عايز تعرف مين هو الزعيم الخالد ابو رجيلة اسال صاحبك"
