[[comments]]
author = "shimaa"
date = "2007-04-01T01:07:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj0Q5LXS1guXTqQoB0zCHEZOdUy6VL3nZOF09JFgFjB2ZKI7SRVGnsEpow8i6WeBwPNL3VCRwjsY6jLM3vTnN_MxCnD6L9Mx9G_Jib_8zjjXWZsvvskr0XyKAIKOdV0xw/s220/hyori-lee[1].jpg"
profile_url = "https://www.blogger.com/profile/10764917878271047406"
comment_url = "https://mos3abof.blogspot.com/2006/12/blog-post_22.html?showComment=1175382420000#c1508879278534091696"
text = "حتى أي حد على الماسينجر (أو على الطبيعة) بيسألني عن تاريخي الدراسي أقول له \"دي قصة طوييييييييييييلة تعود إلى KG 2\" وما يصدقنيش<br /><br />2ywan hoa da eli 7sl m3ya blzbt..s2lt so2al bre2 2omt b3tli el link da eli wad7 eno kan m7wla mnk enk tre7 nfsk 3shan ama 7d ys2lk elso2al da tb3tholo :D<br /><br />allah yekon fe 3onk bgd ...bs thx God 3rft 27'ern enk fe tagara w da 2ngaz fe 7d zato :D"

[[comments]]
author = "Faheem"
date = "2007-01-16T13:12:00.000+01:00"
avatar_url = "http://z.about.com/d/websearch/1/0/4/A/egypt.png"
profile_url = "https://www.blogger.com/profile/17970507786694183589"
comment_url = "https://mos3abof.blogspot.com/2006/12/blog-post_22.html?showComment=1168949520000#c6566606960358879363"
text = "عموماً يا مصعب احمد ربنا انك مكملتش في هندسة<br />انا بقى كنت اشطر منك و نطيت لغاية تالتة على طول بس انا دلوقتي في تالتة تالت يعني من الخارج ولو كان ده حصل من زمان كنت عملت زيك و حولت تجارة فهيمة و ريحت دماغي."

[[comments]]
author = "Anonymous"
date = "2007-01-12T03:01:00.000+01:00"
avatar_url = ""
profile_url = ""
comment_url = "https://mos3abof.blogspot.com/2006/12/blog-post_22.html?showComment=1168567260000#c406970202569268328"
text = "و الله ياأستاذ مصعب \"و أستاذ دى للاحترام لأنه واضح إن خبرتك فى التعليم كبيييييييييييرة قوى قوى\"<br />بس و الله تعبتلك، إذا كان أنا تعبت من قرائتها تعمل انت ايه و انت عشتها كلها، ربنا يكون فى عونك و يصبرك و إن شاء الله ربنا هايكرمك بأحسن من كل اللى فات طالما نيتك سليمة و مع ربنا"

[[comments]]
author = "محمود"
date = "2007-01-03T02:51:00.000+01:00"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/04698116591720747307"
comment_url = "https://mos3abof.blogspot.com/2006/12/blog-post_22.html?showComment=1167789060000#c7321336969083583153"
text = "ماشي يا مصعب يابني اهم محطة في حياتك لما اتقابلنا في احمد بهجت و يا سعدك يا فرحتك لما اتقابلنا تاني في هندسة ...لا والله يا مصعب انا الي كنت سعيد بمعرفة الكائن الفضائي في مدرستنا لانه كانعقل جميل و محترم..."

[[comments]]
author = "Anonymous"
date = "2006-12-26T14:49:00.000+01:00"
avatar_url = ""
profile_url = ""
comment_url = "https://mos3abof.blogspot.com/2006/12/blog-post_22.html?showComment=1167140940000#c1457051781133685815"
text = "عاوز اقول زى دنانير ...عارف احلى حاجه ايه<br />ان كل الحاجات دى خلتك مصعب <br /><br />و بتمنالك كل التوفيق فى الدنيا و الاخرة و"

[[comments]]
author = "طلال فيصل"
date = "2006-12-25T17:13:00.000+01:00"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/12524562781376529224"
comment_url = "https://mos3abof.blogspot.com/2006/12/blog-post_22.html?showComment=1167063180000#c7652614209118392291"
text = "لمصعب اذن فى عنقى اعتذار واجب<br />كنت كلما سألته عن اخبار امتحاناته يجيب<br />الحياه كلها امتحانات يا اخ طلال<br />واقول فى نفسى ايه الرد اللزج من هذا البنى ادم الأكثر لزوجة<br />معلش يا عم مصعب<br />اللى ميعرفش يقول ...مصر"

[[comments]]
author = "Bahz.Baih"
date = "2006-12-25T12:40:00.000+01:00"
avatar_url = "http://farm2.static.flickr.com/1216/1407323379_55eefd71bc_o.jpg"
profile_url = "https://www.blogger.com/profile/13872500067980083476"
comment_url = "https://mos3abof.blogspot.com/2006/12/blog-post_22.html?showComment=1167046800000#c4903260945065936411"
text = "يااااااه يا عم مصعب<br />وانا اللى كنت فاكر أن قصتى مع التعليم غريبه<br /><br />بص صدقنى التعليم مش كل حاجه أهم حاجه الدماغ الجامده<br /><br />مش عارف أقولك أيه بس هو فى النهايه أنت أسقريت على أيه ... خلاص تجاره القاهره<br /><br />على العموم أنت لسه صغير سناً مش عقلاٍ و لسه الفرصه قدامك تخلص تجاره و تعمل حاجات كتير <br /><br />شوف كمان ممكن تتطوع فى أحد الجمعيات الأهليه المنتشره فى القاهره... هتديك خبره حلوه قوى <br /><br />حاجه زى نهضه المحروسه أو مشوار أو الحالمون بالغد<br /><br />هتغير فى حياتك كتير"

[[comments]]
author = "ابن مرّ"
date = "2006-12-25T01:21:00.000+01:00"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/00657991931774204232"
comment_url = "https://mos3abof.blogspot.com/2006/12/blog-post_22.html?showComment=1167006060000#c2956265990412320862"
text = "انت قوي قوي<br />لأن السلاسل تعلمنا أن نقاتل<br />بجد أنا بحترمك جدا جدا جدا<br />جايز ما اعرفكش ولكن أكيد شخص زيك لازم النا تسعى انها تتعرف عليه<br /><br />ربنا يباركلك في دنتك وآخرتك"

[[comments]]
author = "معتـز عبد الرحمن"
date = "2006-12-24T17:25:00.000+01:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi9YGLkDAqJuo7sS7Fr9Ad2up0smIWcnrTcw1aqY_o6hWtG5ypp-8gSrIe98x2XkBAXNXuYjpuClJiJu9lB9a9FQ5RDXNPjbZrZj1fKpMxsQ-Xe9ZM8WHx7bbnYmWzZ1KE/s220/1962855_1543779689213647_3833343368396054294_n.jpg"
profile_url = "https://www.blogger.com/profile/11851524285637979720"
comment_url = "https://mos3abof.blogspot.com/2006/12/blog-post_22.html?showComment=1166977500000#c4157965109369615918"
text = "ربنا يكرمك يا مصعب<br /><br />وياسيدي يمكن أكون أنا من المستفيدين من اللخبطة اللي حصلتلك دي ، على الأقل قابلتك في يوم من الأيام؟ ولا إيه؟<br /><br />وطبعا لا يخفى على أحد مشاكل التعليم في مصر ومنها طبعا كليتنا العزيزة<br /><br />لكن برضه أنت كانت ظروفك خاصة شوية<br />والحمد لله رب العالمين<br /><br />ويمكن ده كله كان إعداد ليك لشيء معين انت لسه متعرفوش<br />الله أعلم<br />وربنا يوفقك لما تحب وترضى"

[[comments]]
author = "bagabigo"
date = "2006-12-24T11:08:00.000+01:00"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/09883934031777235451"
comment_url = "https://mos3abof.blogspot.com/2006/12/blog-post_22.html?showComment=1166954880000#c5113081761135215393"
text = "thank u 4 ur comment and ur support"

[[comments]]
author = "bagabigo"
date = "2006-12-24T09:11:00.000+01:00"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/09883934031777235451"
comment_url = "https://mos3abof.blogspot.com/2006/12/blog-post_22.html?showComment=1166947860000#c3031271985047781205"
text = "ربنا معاك"

[[comments]]
author = "Dananeer"
date = "2006-12-24T02:12:00.000+01:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhDHGvgY5KpZ8XEsPyzaaDpmG53SKgaqkXxb8lI5SrPxQajlLmAm6PnP9A8howzgOVmDKonJLsRa4LRH3mPV9LiGH0oloUzdu0hFwoqEumr2ko-f1X_ntVu5FpwKKpEWtE/s1600/2141.jpg"
profile_url = "https://www.blogger.com/profile/08617762348908989998"
comment_url = "https://mos3abof.blogspot.com/2006/12/blog-post_22.html?showComment=1166922720000#c5880083982864463863"
text = "عارف احلى حاجه ايه<br />ان كل الحاجات دى خلتك مصعب اللى احنا عارفينه<br /><br />اللى محولتوش كم المشاكل المش معقوله دى<br />لكائن لا بيفكر و لا بيفهم<br /><br />ربنا معاك فى امتحاناتك<br />و تحقق المشروع<br />;)<br /><br />صور دريم حلوه<br />حقدت عليكم رغم انى جبانه"

[[comments]]
author = "dead man"
date = "2006-12-23T23:13:00.000+01:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgblVMh7Nlr7ton4EF6_WEIvx8uFAb-eyxAuL1LWv4FXTV92r6gCplvVR4alR4sN7zoTvIKKNYNdwspZiK_KxIj22bYHSiigq8zeWWpnNoyw8kdaUTj-R6MOh9v1vhBvNg/s220/wait.jpg"
profile_url = "https://www.blogger.com/profile/10592260848284665609"
comment_url = "https://mos3abof.blogspot.com/2006/12/blog-post_22.html?showComment=1166911980000#c2529831552657401314"
text = "تخيل معايا كده لو الامتحانات في مصر جت للي بيفكروا مش بيحفظوا تفتكر نسبة النجاح هتبقى كام؟"

[[comments]]
author = "Anonymous"
date = "2006-12-23T15:04:00.000+01:00"
avatar_url = ""
profile_url = ""
comment_url = "https://mos3abof.blogspot.com/2006/12/blog-post_22.html?showComment=1166882640000#c1942914320693184703"
text = "الاخ العزيز مصعب <br /><br />اولا: يا سيدي <br /><br />نسأل الله ان تنجح وتخلص من الكلية والدراسة <br />وتحقق حلمك <br /><br />ثانيا : اوقات يمر الانسان بأحداث قد يرى أنها سئية له لكن مع الزمن ومرو الوقت يرى انها كانت الخير له <br /><br />والانسان منا يقاس بخبرته في الحياة والخبرة تبنى بكل موقف وأزمة يمر بها الانسان التي تزيد من شخصيته ثقلا <br /><br />أنا أغبطك لأنك عارف انت عاوز ايه وماشي في سكة  محددها قبل ذلك <br />اعانك الله يا مصعب الخير <br /><br />مجاهد شرارة"

[[comments]]
author = "Mony The Angel"
date = "2006-12-23T13:59:00.000+01:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjj4h6hlbKyUklJB5J_QeHmZidZ8mEHO-s5lWgxcP3qUEQSPg4AS0GkKHyrjWHC4Z5y2O3vBW2OY7WPf-cZ0PSVMC-DcEJ6cu6SRYKhpVq1jh6S9ve07RM4o8WgdU_8rxE/s220/mine...jpg"
profile_url = "https://www.blogger.com/profile/02273268851121458996"
comment_url = "https://mos3abof.blogspot.com/2006/12/blog-post_22.html?showComment=1166878740000#c5165790865168705722"
text = "elwa2ty fhemt ma3na kalamak lama gah aldoor 3aleek 3shan t3arraf nafsak :)<br />bgad rabena ykoon f 3oonak<br />pravo enak lsa 3aiesh, w pravo enak ader tkammel"

[[comments]]
author = "frozen love"
date = "2006-12-23T13:55:00.000+01:00"
avatar_url = "http://gallery4collectors.com/images/ABrandNewHope.jpg"
profile_url = "https://www.blogger.com/profile/09234631877092795314"
comment_url = "https://mos3abof.blogspot.com/2006/12/blog-post_22.html?showComment=1166878500000#c101060682021188025"
text = "wlahy ya abo ms3b....ana fakr m3anatk ayam elmdrsa...we knt bt7kely elm2sah de..lol,,,kl ely a2dr a2olholk gher eno nsebk y3ny...enk lazm t3tbr kl da khbra lek...we ht3rf bnfsk eny mafesh 7aga 3mltha we mstfdsh beha....rbna ytwlana fe elbld elghreba de ya sdeky"

[[comments]]
author = "Anonymous"
date = "2006-12-23T09:51:00.000+01:00"
avatar_url = ""
profile_url = ""
comment_url = "https://mos3abof.blogspot.com/2006/12/blog-post_22.html?showComment=1166863860000#c4543544595393335497"
text = "والله يا مصعب ..بعيدا عن كل اللى حصل ده واللى هايحصل .. إنت عارف طبعا إن هى دى الحياة ولازم يحصل فيها كدة عشان نتعلم من المواقف دى كلها<br />لكن إنت فاكر التفاصيل دى كلها إزاى؟؟<br />!!<br />:)<br />على فكرة يمكن دى على ما أعتقد تعليقى الأول فى مدونتك لكن كنت عايز أشكرك على مقالاتك كلها ..أنا متابعها من فترة <br />وأكتر حاجة عجبانى فيها الطابع العائلى اللى فيها يعنى وأنا بقرأ مقالاتك بحس إنى مع صاحب أو أخ مش مجرد مع كاتب فى مدونة <br />تقبل صداقتى <br />وبالتوفيق دائما إن شاء الله<br />:)"

[[comments]]
author = "TheSane"
date = "2006-12-23T01:10:00.000+01:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgKwTj0zQgdDd0xQOrF03RqMVoarSutn2qURyauLXgFJKVxbDE0CxZvBPwHxOZoqTAXnuZYAU1G7DsfBUFAv5qrjFiSB0RS1eGrSfDKcGjZxeU-JSeYk1JZcKOyRcWo9Q/s220/3G.jpg"
profile_url = "https://www.blogger.com/profile/07162269646851276658"
comment_url = "https://mos3abof.blogspot.com/2006/12/blog-post_22.html?showComment=1166832600000#c2102878660471297681"
text = "كويس انه حصلك ده كله والا مكنتش قابلتني :P"

[[comments]]
author = "Anonymous"
date = "2006-12-22T23:28:00.000+01:00"
avatar_url = ""
profile_url = ""
comment_url = "https://mos3abof.blogspot.com/2006/12/blog-post_22.html?showComment=1166826480000#c313781595395840066"
text = "المهم انك رجعت بالسلامة ياوغد وطلعت من المعركة علي خير دون فقد ايا من أطرافك..<br />واحمد الله انك متنبه انك توازي حمار في المعرفة مادام التعليم المصري قد وضع بصمته فيك..<br />انا عن نفسي بحس اني قبيلة من الحمير بسبب التعليم اللي اتعلمته<br />فقط علينا أن نعلم انفسنا بأنفسنا يافتي"

[[comments]]
author = "We2am"
date = "2006-12-22T22:56:00.000+01:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhQcQ1ZEVto0d3Q-8SYrlhPe65gtdb7vieD2O9VTjley8Ol9gRSSIxfYCsbogR3Vwo_4gVGfgbPaXcMMYxpPYMmGgitzKr2RN8hp4O1ZV_ezx9D2Wqd3AhCUjMKrXUByu0/s113/14803259_10154014513627023_722172126_o.jpg"
profile_url = "https://www.blogger.com/profile/11798083370261251218"
comment_url = "https://mos3abof.blogspot.com/2006/12/blog-post_22.html?showComment=1166824560000#c4683440851107450548"
text = "deh ma2sah e3'reqyya aslan!!!<br />ana te3bt awe awl masm3t.ha esra7a..w an leha naseeb kber fe ene 2olt enk momyz w mmkn netsa7b..rbna yenwrlk tare2k yabne..shoft masr baldna weslt feen? :D"

[[comments]]
author = "محمد السيد..مش حاسكت"
date = "2006-12-22T22:33:00.000+01:00"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/15123433931771567833"
comment_url = "https://mos3abof.blogspot.com/2006/12/blog-post_22.html?showComment=1166823180000#c1625872836236217332"
text = "كانت المشاكل في الجامعة وما أدراك ما الجامعة ...<br /><br />الغربة في القاهرة ... البعد عن أحلي حتة في الدنيا \" الإسكندرية \"<br /><br />المدينة الجامعية واللي فيها .... سواء العصافير سواء الجهل الثقافي اللي يشل ... سواء الولاد اللي كل حياتهم بنات وحاجات من دي  ...<br /><br />الشقة اللي كانت من غير عفش وساكن فيها كام واحد ...<br /><br />الأوضة اللي فوق السطوح الللي تفكرك بفيلم \" شباب إمراة \" ...<br /><br />والنهاية السفر رايح جاي ... من القاهرة للإسكندرية في القطر المميز ... لغاية لما تطلع عينك ...<br /><br />خلال الفترة دي .. ونتيجة للتنطيط .. طبيعي انك تعيد سنة تالتة ...<br /><br />وطبيعي لما تتمسك في مظاهرات القضاة أيام الامتحانات تعيد سنة رابعة كمان ....<br />وهي اللي أنا وصلت لها دلوقتي ....<br /><br />بس برضه مش حاسكت<br />لا للتمديد ... لا للتوريث  ... نعم لتعديل الدستور المصري"

[[comments]]
author = "محمد السيد..مش حاسكت"
date = "2006-12-22T22:28:00.000+01:00"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/15123433931771567833"
comment_url = "https://mos3abof.blogspot.com/2006/12/blog-post_22.html?showComment=1166822880000#c197565686682746955"
text = "ايه ياعم ........<br /><br />إيه الجمال ده ؟؟؟ في حتت كتير حسيت إني ممكن أستعير نفس العبارت ويمكن أحداث متشابعة ....<br /><br />أنا ياسيدي بقي اتولدت في اليمن وجيت وأناعندي ست سنين ...<br /><br />يمكن مفتكرش حاجة كتير من أيامها ...<br /><br />ويمكن أيام الابتدائي والإعدادي والثانوي مرت بيا علي خير ...<br /><br />والفضل كده يرجع للمدرسة العظيمة اللي بجد الواحد اتعلم فيها كتير ... \" المدينة المنورة \"<br /><br />والفضل فيها للإخوان المسلمين اللي فعلا ربوا وعلموا وتعبوا فينا عشان ما يطلعونا ناس محترمين وكويسين كده ....<br /><br />لكن كانت المشاكل بعد كده<br /><br /><br />لا للتمديد ... لا للتوريث ... نعم لتعديل الدستور المصري<br />mohamedmat@hotmail.com"

[[comments]]
author = "Amira Hassan"
date = "2006-12-22T19:44:00.000+01:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjKwkbS92ad0pzdLQkHLcToR78dqrG___FfPXTF7qAL6Eml7VawwAzFxt-bHWDIWOwjxbeWWob3GpF-cygVRx34PDduMFcrff3Zh1VxP_o5DrDK-5RHQ3UVoWbveXLLzg/s220/DSC04172.JPG"
profile_url = "https://www.blogger.com/profile/08135823930111514700"
comment_url = "https://mos3abof.blogspot.com/2006/12/blog-post_22.html?showComment=1166813040000#c6856443860806350816"
text = "اه...افتكرت..في يوم من الايام اللي ببقى فيهم متهورة طلبت منك انك تحكيلي حكايتك ممع التعليم...بجد انا اشفقت عليك جدااااااااااا.....سوري بس اصل احنا اساسا بلد********"

[[comments]]
author = "Anonymous"
date = "2006-12-22T19:33:00.000+01:00"
avatar_url = ""
profile_url = ""
comment_url = "https://mos3abof.blogspot.com/2006/12/blog-post_22.html?showComment=1166812380000#c1681445963459449974"
text = "the mere fact that your brain still able to work after all these changes is impressive."

[[comments]]
author = "saso"
date = "2006-12-22T19:31:00.000+01:00"
avatar_url = "http://www.geocities.com/mgm21m/mad.jpg"
profile_url = "https://www.blogger.com/profile/17003802864573876073"
comment_url = "https://mos3abof.blogspot.com/2006/12/blog-post_22.html?showComment=1166812260000#c4204293958301567247"
text = "هوا انا حاولت اركز واستوعب..بس بجد ماعرفتش اتخيل نفسي مكانك  <br />رجعت للبروفايل لقيت سنك عشرين..كل دة يعدي عليك في اقل من عشرين سنة وتقلبات وشوش ولهجات واسماء وصحاب<br />ربنا يكون في عونك طبعا..بس اكيد كده احسن ربنا عاوزك تمر بدة اكيد"

[[comments]]
author = "nour"
date = "2006-12-22T18:51:00.000+01:00"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/13625151471195771582"
comment_url = "https://mos3abof.blogspot.com/2006/12/blog-post_22.html?showComment=1166809860000#c7212710400952161774"
text = "ايه يا بنى المآساة دى<br />ده انت ربنا يكون فى عونك بس الحمد لله عدت"

[[comments]]
author = "Lens Geek"
date = "2006-12-22T17:49:00.000+01:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhDH6cac8DhCu85r5fVw0KJDQyTSgnbUN_on5yZRrtKG44soaS5wrAZnDMZBnmYItm4PSgM5Be26Q5kswvv4w84fGE-zjxA4uFGBZW67q5kjJzKnPEAcvpMpdz-KsYUpg/s220/Ahmed2.gif"
profile_url = "https://www.blogger.com/profile/08391635125789451063"
comment_url = "https://mos3abof.blogspot.com/2006/12/blog-post_22.html?showComment=1166806140000#c3733781228812138363"
text = "You should be proud of yourself. Man with a lot of experience is a man with a lot of wisdom.<br /><br />learn from the next quote<br /><i><b>\"Experience is what we get when we do not get what we want.\" ~ Enio Carvalho</b></i>"

[[comments]]
author = "emz"
date = "2006-12-22T17:06:00.000+01:00"
avatar_url = "http://www2.0zz0.com/2007/11/09/21/19408873.jpg"
profile_url = "https://www.blogger.com/profile/06702188321496445002"
comment_url = "https://mos3abof.blogspot.com/2006/12/blog-post_22.html?showComment=1166803560000#c1540818526183438408"
text = "ما شاءالله .. ربنا يكملكبعقلك يا مصعب :P"
