[[comments]]
author = "تــسنيـم"
date = "2009-03-18T19:12:00+00:00"
text = "ربنــا يديمهــا عليك نعمـــة<br /><br /><br />:))"
avatar_url = "http://1.bp.blogspot.com/-unAk4PRAf0k/T2EgcoozgEI/AAAAAAAAB5c/zOYIlMms6vo/s220/%25D8%25A7%25D9%2584%25D9%2585%25D9%2586%25D8%25B5%25D9%2588%25D8%25B1%25D8%25A9%2B1.jpg"
profile_url = "https://www.blogger.com/profile/17390698031839586224"
comment_url = "https://mos3abof.blogspot.com/2009/03/23.html?showComment=1237403520000#c1840599322885171072"

[[comments]]
author = "ياء"
date = "2009-03-20T21:29:00+00:00"
text = "كل عام وانت ب1000 خير<br /><br />وكل سنه وانت طيب"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/09927085065103433253"
comment_url = "https://mos3abof.blogspot.com/2009/03/23.html?showComment=1237584540000#c6204497208803295895"

[[comments]]
author = "Mony The Angel"
date = "2009-03-21T02:03:00+00:00"
text = "kol sana wenta m3aha :)"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjj4h6hlbKyUklJB5J_QeHmZidZ8mEHO-s5lWgxcP3qUEQSPg4AS0GkKHyrjWHC4Z5y2O3vBW2OY7WPf-cZ0PSVMC-DcEJ6cu6SRYKhpVq1jh6S9ve07RM4o8WgdU_8rxE/s220/mine...jpg"
profile_url = "https://www.blogger.com/profile/02273268851121458996"
comment_url = "https://mos3abof.blogspot.com/2009/03/23.html?showComment=1237600980000#c995674837690997748"

[[comments]]
author = "Amimi Houssainy"
date = "2009-03-26T13:00:00+00:00"
text = "rabena yetamem Lakoma Norkom Ya rab ....Ya a3az Sadi9 Chofto fi 7ayati :) we koli Sana we nta  ubuntu  and Apple Mac..."
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgZ5U4WlzUss0uPIk6CIWOP39PIGRIka0M7X7oxQFac3IA96TWm6eSkn9diM-POEGc0GEEz-HFkLZbr4bOmskrn3xWyOUmDVdCHlqDBPy-seDBJISTCwtdUdRokxve19_M/s220/coustime_album.jpg"
profile_url = "https://www.blogger.com/profile/11706534749857063059"
comment_url = "https://mos3abof.blogspot.com/2009/03/23.html?showComment=1238072400000#c6749034461267081299"

[[comments]]
author = "david santos"
date = "2009-03-29T22:10:00+00:00"
text = "Excellent posting!!!<br />Happy week!!!!"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhKcTvexjr6LUQ-DTvSon30w8huz5vYXVGOpfFpYWCmGdej6VsgNt0xWBMnVbxJCnCPBjulluIf0kENAVluI_c9na-Sm6Y-NhSYi_YYn6MCjWOfyJJ1mfGYK3xO1yB71w/s220/bg_profile.jpg"
profile_url = "https://www.blogger.com/profile/08976825493652779441"
comment_url = "https://mos3abof.blogspot.com/2009/03/23.html?showComment=1238364600000#c2866233075283822408"

[[comments]]
author = "روح"
date = "2009-04-09T00:58:00+00:00"
text = "عام مليء بالقرب من الله<br />وهنيئا لك الصحبة الصالحة<br />والزوجة الصالحة ان شاء الله"
avatar_url = "http://redondowriter.typepad.com/photos/uncategorized/268573778_a71bfed930.jpg"
profile_url = "https://www.blogger.com/profile/08902136818874003625"
comment_url = "https://mos3abof.blogspot.com/2009/03/23.html?showComment=1239238680000#c8691387276163748859"
