[[comments]]
author      = "Mai Kamel"
date        = "2009-10-04T15:45:20.647+02:00"
avatar_url  = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/17724279077077931734"
comment_url = "https://mos3abof.blogspot.com/2009/09/wanted.html?showComment=1254663920647#c6913815936979530283"
text        = "معلش يا مصعب انت عارف بقى البنات وأحلامهم وطموحاتهم وسلطاتهم وبابا غنوجهم<br /><br />فوت <br />فوت<br />:))))"


[[comments]]
author      = "mohamed"
date        = "2009-09-25T10:22:16.951+02:00"
avatar_url  = "//blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiGfWhZiigMyqtTXuNGhGuZ7kCzQpSXHHBQFxacGHOFHEX81agRvyAHVvJNqxlHc4r65JdjhzBKu76zKEj0TXhBVJ-Rjmpfciyt9XBGHfdbSKJJfq-Rc3UeAgPD5FN-SK0/s220/DSCF29155.jpg"
profile_url = "https://www.blogger.com/profile/11099621052476900765"
comment_url = "https://mos3abof.blogspot.com/2009/09/wanted.html?showComment=1253866936951#c257087419794210230"
text        = "معاها حق <br />أنا أول ما شفت الرسمة قولت هو بكي بورده بموسةبلاب توبة..<br /><br />فنانة يا أميرة من يومك"
