[[comments]]
author = "Nohaz"
date = "2006-02-14T20:28:00+00:00"
text = "ana kaman el farda el shemal bardo<br /><br />bas ana ba2it adkhal el robat goa el gazma<br /><br />hope u r fine mashoftakesh today i guess"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjIL2Z6FgqS2BzmD5surOJddf86weillgt5JtPyrgYF4iz2gB7mG4eN1loo1l0iKz2klyPj0rW39wWI9ANzGY5FQsPPr-Y2fjZ6RjrO2ZtfS2SOIXKeQUD1jMkHpvSHlUY/s113/lip-synching_1710116i.jpg"
profile_url = "https://www.blogger.com/profile/14313688156868197076"
comment_url = "https://mos3abof.blogspot.com/2006/02/blog-post_13.html?showComment=1139948880000#c113994891427446785"

[[comments]]
author = "العـابــــــــره"
date = "2006-02-17T13:08:00+00:00"
text = "when i feel sad. i read this page<br />because it's make me laugh... and laugh..hahaha ....and laugh hhahaaa"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjirpnB1jlU7bWG0V6oQLFugE9LdCMmPYCneTsqfh2X7QHo46m-E-v1cdrCVcEqswMoAqKAfbCjRjc-xZIYckh1rq-QCi0KDc5B3O1mEHShrSAU5djGV2RpP_EXGiIOJA/s220/amanyyyyyy.jpg"
profile_url = "https://www.blogger.com/profile/02540503067719024339"
comment_url = "https://mos3abof.blogspot.com/2006/02/blog-post_13.html?showComment=1140181680000#c114018172277272864"
