[[comments]]
author = "moon"
date = "2008-01-01T02:22:00+00:00"
text = "wallahy hwa gaii, hwa 2ally ana kman enno gaii,, gaii mneen w feen w emta ma2alsh bas el mohem enno gaii :)))<br /><br />happy new year with the \"daii\" ya mos3ab :))"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/06613187847365225877"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post.html?showComment=1199154120000#c6961000206211760338"

[[comments]]
author = "Unknown"
date = "2008-01-01T06:41:00+00:00"
text = "ياخوفى <br />شكلك هتصوم تلات أيام يا زعيم<br /><br />بس علشان الضمان خليهم أيام<br />29-12-2008<br />30-12-2008<br />31-12-2008<br />على فكره انا طبعا مش عوزك تصمهم<br />يااااامسهل ادينا مستنيين"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/12955725133588745897"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post.html?showComment=1199169660000#c8045266493079323899"

[[comments]]
author = "Salma Amer"
date = "2008-01-01T06:43:00+00:00"
text = "اية الرواقن والابداع ده شكلك بتطلع البدع لما بتصل لقمة التعب بحكم ان انت بقالك يومين مانمتش<br />بالنسبة للأستاذ ضي فانا كنت واخدة على خاطري منه لانه اتاخر علينا حبتين وكنت خلاص حرمي طوبته <br />بس بيقولوا الغايب حجته معاه <br />لذلك أنا بضم صوتي لصوتك وبستحلفة أن يجي واننا لن نفقد الأمل يوم أنه جاي لأنه أكيد أكيد جاي وحينور السما والأرض وبعدين يجلنا ينور قلوبنا قبل عنينا <br />وأنا معاك في انتظار الاستاذ ضي"
avatar_url = "http://farm2.static.flickr.com/1132/1365681113_f20faceeb5.jpg?v=0"
profile_url = "https://www.blogger.com/profile/08716194696950096714"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post.html?showComment=1199169780000#c5640198424964363591"

[[comments]]
author = "Anonymous"
date = "2008-01-01T06:48:00+00:00"
text = "ان شاء الله جاي \"ضي\"<br /><br />وهيطلع من جوه قلوبنا وراح ينتشر <br /><br />ويشيل الظلمة <br /><br />ويرجع يكبر يصبح نور حولينا<br /><br />نرجع نصحى ونبقى فى نور <br /><br />وكل اللى جواه الـ\"ضي\"<br /><br /><br />\"بيبو\""
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post.html?showComment=1199170080000#c171488551866212122"

[[comments]]
author = "TheSane"
date = "2008-01-01T09:53:00+00:00"
text = "أنا جيت اهو <br />معلش أتاخرت عليكو<br />D:"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgKwTj0zQgdDd0xQOrF03RqMVoarSutn2qURyauLXgFJKVxbDE0CxZvBPwHxOZoqTAXnuZYAU1G7DsfBUFAv5qrjFiSB0RS1eGrSfDKcGjZxeU-JSeYk1JZcKOyRcWo9Q/s220/3G.jpg"
profile_url = "https://www.blogger.com/profile/07162269646851276658"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post.html?showComment=1199181180000#c7749503224979615689"

[[comments]]
author = "دوللي"
date = "2008-01-01T10:51:00+00:00"
text = "كل سنة وانت طيب وتكون حياتك كلها ضي <br />ربنا يسعدك"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/06515904854255564384"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post.html?showComment=1199184660000#c1318601239441230904"

[[comments]]
author = "أحمد الدريني"
date = "2008-01-01T12:10:00+00:00"
text = "لقد وصل منذ قليل"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/17300680267091030312"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post.html?showComment=1199189400000#c4270748603762096499"

[[comments]]
author = "nyira_elsheiref"
date = "2008-01-01T13:17:00+00:00"
text = "أنا كمان واثقه إنه جى<br />وأنتظره على أحر من الجمر <br />بس يارب ما يتأخرش<br />يحسن خلااااااااص بلغت الروح الحلقوم"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/01466185015455031275"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post.html?showComment=1199193420000#c8167963266172946628"

[[comments]]
author = "mohamed"
date = "2008-01-01T14:27:00+00:00"
text = "مهو الامل في الضي دا هو اللي مصبرنا"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiGfWhZiigMyqtTXuNGhGuZ7kCzQpSXHHBQFxacGHOFHEX81agRvyAHVvJNqxlHc4r65JdjhzBKu76zKEj0TXhBVJ-Rjmpfciyt9XBGHfdbSKJJfq-Rc3UeAgPD5FN-SK0/s220/DSCF29155.jpg"
profile_url = "https://www.blogger.com/profile/11099621052476900765"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post.html?showComment=1199197620000#c6840304842476536812"

[[comments]]
author = "شيرين"
date = "2008-01-01T17:14:00+00:00"
text = "مصعب انت أكيد بتهزر.. لا لا بجد بتهزر.. ايييييييييييييه الروعة دي.. بجد أنا متأثرة قوييييييييييي<br /><br />أما بالنسبة بقى لمسألة الضي احنا طبعا عارفين انه جاي، بس المشكلة امتى.. امتاااااااااااا"
avatar_url = "http://photos-279.ll.facebook.com/photos-ll-sctm/v99/129/13/717256279/n717256279_214552_3758.jpg"
profile_url = "https://www.blogger.com/profile/08718885335246773468"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post.html?showComment=1199207640000#c5975522935707022044"

[[comments]]
author = "MariumaZ"
date = "2008-01-01T18:33:00+00:00"
text = "مصعب ... إنت اللي كاتب ده بجد؟؟؟<br />مش مصدقة .. بجد حلوة أوي أوي أوي<br />الضي موجود يابني بس احنا مش شايفينه .. بكرة إحنا اللي نفتح ونشوف المستخبي:)<br />بجد روعة يا مصعب...<br />ياريت نتابع مدونات بعض زي زمان<br />ونكتب تعليقات، كل سنة وانت طيب ويارب 2008 يبقى عام حلو علينا كلنا بإذن الله."
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg9giUV2iCTwwtfQoUxjZXLMjO4Scq0iKCUdYMCgmovIiMOde9B26aqPY_6wwiZy8PHqssu8sQSZDgaBjnhd_kQL0aeEev2mUQs1l-tOOUp6mUNQV2JilPBktEhrS_AHqU/s220/IMG_0084.jpg"
profile_url = "https://www.blogger.com/profile/12796121153780883763"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post.html?showComment=1199212380000#c4561494354248670217"

[[comments]]
author = "MarwaAshraf"
date = "2008-01-01T22:00:00+00:00"
text = "طول قرائتي للبوست كان بيتردد جوايا سؤال \"تفتكر هو جاي؟\" وعارف فضل السؤال من غير جواب حتى لما وصلت لأخر جملة برودا فضل سؤالي جوايا بيلح  <br /><br />تفتكر هو جاي؟؟؟"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/12117806503113618382"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post.html?showComment=1199224800000#c5417129403504630394"

[[comments]]
author = "Mony The Angel"
date = "2008-01-01T22:47:00+00:00"
text = "kol sana wenta tayeb :)"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjj4h6hlbKyUklJB5J_QeHmZidZ8mEHO-s5lWgxcP3qUEQSPg4AS0GkKHyrjWHC4Z5y2O3vBW2OY7WPf-cZ0PSVMC-DcEJ6cu6SRYKhpVq1jh6S9ve07RM4o8WgdU_8rxE/s220/mine...jpg"
profile_url = "https://www.blogger.com/profile/02273268851121458996"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post.html?showComment=1199227620000#c5525184548743197427"

[[comments]]
author = "العـابــــــــره"
date = "2008-01-02T03:30:00+00:00"
text = "الأمل مهما يعاند دربنا<br />لعمرنا نحود فى يوم عن حلمنا<br />ولو طال ليلناعلينا<br />فبكره جاى<br />جاى بضى<br />  تحياتى<br />وكل سنه وانت طيب"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjirpnB1jlU7bWG0V6oQLFugE9LdCMmPYCneTsqfh2X7QHo46m-E-v1cdrCVcEqswMoAqKAfbCjRjc-xZIYckh1rq-QCi0KDc5B3O1mEHShrSAU5djGV2RpP_EXGiIOJA/s220/amanyyyyyy.jpg"
profile_url = "https://www.blogger.com/profile/02540503067719024339"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post.html?showComment=1199244600000#c1803619166629652995"

[[comments]]
author = "تــسنيـم"
date = "2008-01-02T11:44:00+00:00"
text = "رائعة بجد<br /><br />وما تقلقش جاي<br /><br /><br />هو قال"
avatar_url = "http://1.bp.blogspot.com/-unAk4PRAf0k/T2EgcoozgEI/AAAAAAAAB5c/zOYIlMms6vo/s220/%25D8%25A7%25D9%2584%25D9%2585%25D9%2586%25D8%25B5%25D9%2588%25D8%25B1%25D8%25A9%2B1.jpg"
profile_url = "https://www.blogger.com/profile/17390698031839586224"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post.html?showComment=1199274240000#c3070149863607967082"

[[comments]]
author = "الطائر الحر"
date = "2008-01-02T22:16:00+00:00"
text = "الضي جاي من القلب من جوه"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi5iA3YXPlDr_RHPQWzh4RqFHNP3O3v6Eoe3OINmDiKqQEsvkg8RMZ-l_zBb3u_2O4AkrAeqkRVAW8-YUKxzGoeNyCBptQGe-hXgbfZq9trGbsGrIJC_D3EsAKIPBnyVg/s220/pic02b.jpg"
profile_url = "https://www.blogger.com/profile/11871033505873136821"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post.html?showComment=1199312160000#c6970846531629949024"

[[comments]]
author = "حلم الحرية"
date = "2008-01-03T12:57:00+00:00"
text = "ساعات بيجي بسرعة<br />وساعات بيتاخر<br /><br />بس الاكيد انه بييجي في الاخر ان شاء الله<br /><br /><br />تحياتي"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj5134mBTHr7rVK3DSDgnRf5E_RugYPeh5cWZbeDoXKvwsHyL4tD1n_WEYXUeoJ4PMOSErPXCdUpGN274-0C5lbxDHtZQHsGch0ykrvpLnt52BWXdtpgWRytPSyMnw4MA/s1600/*"
profile_url = "https://www.blogger.com/profile/16809490468014096848"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post.html?showComment=1199365020000#c4491522723842433235"

[[comments]]
author = "أميرة من غير قصر ولا بستان.. ولا الشاطر حسن كمان"
date = "2008-01-04T17:55:00+00:00"
text = "و اذا جييت يا ضي خليك شويه<br />بلاش بخل بقي <br />تعالي ..و استني معانا و ياريت لو تفضل بقي على طووول <br />يا سلاااااااام"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEirdirzKebc0hcGC4MQ6kvVkx2q0MdxprJrl-jqSZ5l_jxE2bWsZVd-Pla_Zla1V4g0FjN5PUa4k3oTN0AO0cgFlRcbwr6XbP-7sqohbU_KGsAtNaDenb4eAJmqzrb0EGE/s220/blogpic5ke.jpg"
profile_url = "https://www.blogger.com/profile/16391848599214933906"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post.html?showComment=1199469300000#c2026908560552535657"

[[comments]]
author = "دينا فهمي"
date = "2008-01-14T16:19:00+00:00"
text = "حلوة جدااااااااااااا يا مصعب"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/07685435794478937439"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post.html?showComment=1200327540000#c7869926174706655041"

[[comments]]
author = "sherif"
date = "2008-05-07T09:58:00+00:00"
text = "الف الف الف مبروك يا مصاعيبو"
avatar_url = "http://photos1.blogger.com/blogger/2776/3195/400/Image%28926%29.jpg"
profile_url = "https://www.blogger.com/profile/15629143312998547267"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post.html?showComment=1210154280000#c3359295715642901620"
