[[comments]]
author = "Oma"
date = "2007-05-04T11:45:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgkyjSYWqXw4YBOpvP-96TyE2UNOj8WOswTKULdPzB70B6zrqDGJHhff9VHgxIxelyXO3EKU7YW8ajjqkmMwG9IO7yT-08dfl5BYELB9hvKRZscAn2UfctX1Oxivr_uIw/s220/dancing.jpg"
profile_url = "https://www.blogger.com/profile/00803900258553286221"
comment_url = "https://mos3abof.blogspot.com/2007/04/4.html?showComment=1178271900000#c8073313741085595705"
text = "بحب اوي الناس دي<br />لما بشوف اتنين زيكو كده بحس الدنيا لسا جميله اوي وبحس اني عايزه ادحك كتيير عشان فيه ناس جميله كده<br />بجد حاله زيكو بتديني امل وبتنورلي الدنيا<br />ربنا مايحرمكو من بعض ابداً<br />ويفضل اللي بينكو يزيد دايماً"

[[comments]]
author = "Anonymous"
date = "2007-05-01T20:29:00.000+02:00"
avatar_url = ""
profile_url = ""
comment_url = "https://mos3abof.blogspot.com/2007/04/4.html?showComment=1178044140000#c3457407053777397809"
text = "انا عبرتك يامصعب ..اخبارك ايه ..المقالة حلوة قوي قوي .. وعقبالك ..انا محمد عبد اللطيف قابلتك في حفلة وجيه عزيز وسالتك اجيب الاغاني بتاعته من فين .. فاكر <br />بص ياسيدي البراء اداني دفعة كده علشان اكتب مدونة .. وانا بدات مع مجموعة من صحابي في كتابةمدونة اسمها الصيف الهندي<br />اتمنى انك تخش على المدونة وتقوللي رايك<br />اللينك اهه<br />http://elsaifelhendy.blogspot.com/"

[[comments]]
author = "AbdElRaHmaN Ayyash"
date = "2007-04-29T17:16:00.000+02:00"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/01249867116407271986"
comment_url = "https://mos3abof.blogspot.com/2007/04/4.html?showComment=1177859760000#c6332687750150831304"
text = "ياااه يا مصعب<br />:) ده كله يابني<br />ربنا يحميكم ويخلليكم ويخلليهم لبعض<br />ان شاء الله اليوم اللي انت مستنيه هييجي بسرعه<br />تعرف أحسن حاجه فيكم ايه<br />انك مصعب<br />وهو براء<br />:) وأحسن حاجه فيك انت ايه<br />انك فاكر كل اللحظات دي في زمن محدش بيفتكر فيه حاجه<br />:) وتعرف أحلى حاجه في براء ايه<br />انه تخين وبنضاره <br />وتعرف أحسن حاجه دعاء ايه <br />انها بقت مدام بيرو<br />ربنا يخلليكم كووووولكم<br />:)سلام يا حبي"

[[comments]]
author = "دعاء عادل"
date = "2007-04-29T04:13:00.000+02:00"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/10121139069642274432"
comment_url = "https://mos3abof.blogspot.com/2007/04/4.html?showComment=1177812780000#c5161483933828543246"
text = "ايه ده يا مصعب انا مش عارفه اقول ايه..البوست حلو اوى.. بجد مشاعرك حلوه وحقيقيه اوووووووى   <br />انت انسان جميل جداوربنا يخليكو لبعض وتزيد الذكريات اللى بينكوا اكتر <br />متخيلاكو بعد اربعين سنه كده وانتوا قاعدين مع اولادكوا واحفادكوا بتحكوا ليهم عن الايام دى والايام اللى جاية انشاء الله وتكون فيه ذكريات حلوه كتير <br />ربنا يسعدك يارب يابراء انت ودعاء بجد فرحنا بيكم اوى ودى اول مره على فكرة حد من اصحابى يتجوز واحضر فرحه وكده يعنى بيرو ودودو هما اول فرحتى (:   <br />بس يا مصعب لسه لم تتم بعد انشاء الله براء يكتب بسلامته بيخطب 5 <br />وتكون انت اللى بتخطب المرة دى ربنا يوفقك يارب  ونفرح بيك انت كمان <br />و تكملوا بقى الذكريات اللى ها تحكوها الى اولادكم ربنا يوفقكم بجد انا بحبكم كلكم اووووووووووووى"

[[comments]]
author = "Abd El Rahman Magdy"
date = "2007-04-28T19:09:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEie05qMeu7V48_3dBNQEYO3OBDi5E0pp7Wy0vOg3nuiYP3hlHnNWMWP6NfLj-Jk-_3m4I7jZ-fB_RjGtoGgTm5Zp9ElDC32VphGJXzionJF9BM2tahgJBFC4NQB4hxuKQ/s220/n648672760_6730.jpg"
profile_url = "https://www.blogger.com/profile/11553040614389148796"
comment_url = "https://mos3abof.blogspot.com/2007/04/4.html?showComment=1177780140000#c8026043538363103466"
text = "كان نفسي اكون موجود ساعة الفرح<br />يللا الحمد لله<br />على العموم ألف مبروك لبراء<br />وربنا يخليهم لبعض<br />وربنا يخليك انت وبراء لبعض"

[[comments]]
author = "أميرة من غير قصر ولا بستان.. ولا الشاطر حسن كمان"
date = "2007-04-28T03:08:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEirdirzKebc0hcGC4MQ6kvVkx2q0MdxprJrl-jqSZ5l_jxE2bWsZVd-Pla_Zla1V4g0FjN5PUa4k3oTN0AO0cgFlRcbwr6XbP-7sqohbU_KGsAtNaDenb4eAJmqzrb0EGE/s220/blogpic5ke.jpg"
profile_url = "https://www.blogger.com/profile/16391848599214933906"
comment_url = "https://mos3abof.blogspot.com/2007/04/4.html?showComment=1177722480000#c9189031887732119552"
text = "ربنا يكرمهم يارب<br />انا عرفت براء بس للأسف متعرفتش بدعاء خالص بس انا واثقه انها هى كمان انسانه طيبه و جميله<br />و ربنا يخليهم لبعض و يخليك ل براء يا مصعب و نفرح بيك قريب :):):)"

[[comments]]
author = "Amira Hassan"
date = "2007-04-28T01:18:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjKwkbS92ad0pzdLQkHLcToR78dqrG___FfPXTF7qAL6Eml7VawwAzFxt-bHWDIWOwjxbeWWob3GpF-cygVRx34PDduMFcrff3Zh1VxP_o5DrDK-5RHQ3UVoWbveXLLzg/s220/DSC04172.JPG"
profile_url = "https://www.blogger.com/profile/08135823930111514700"
comment_url = "https://mos3abof.blogspot.com/2007/04/4.html?showComment=1177715880000#c631828760246687938"
text = "مش عارفه اقولك بجد غير انك جميل اووووووووووي يا مصعب<br /><br />ربنا يديك على اد نيتك الصافية دي<br /><br />و الف مبروك لدعاء و براء"

[[comments]]
author = "elkamhawi"
date = "2007-04-27T00:45:00.000+02:00"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/09923750534350910131"
comment_url = "https://mos3abof.blogspot.com/2007/04/4.html?showComment=1177627500000#c5559753914381031201"
text = "ربنا يخليكو لبعض"

[[comments]]
author = "Anonymous"
date = "2007-04-26T19:17:00.000+02:00"
avatar_url = ""
profile_url = ""
comment_url = "https://mos3abof.blogspot.com/2007/04/4.html?showComment=1177607820000#c72302778711507156"
text = "that's was so so sweet masha Allah<br /><br />Rabena yekremak ya Rab..w 3o2balak<br /><br />for Baraa and Doa'a.... mabroook ya shabab :))"

[[comments]]
author = "NeRmeeN"
date = "2007-04-26T16:36:00.000+02:00"
avatar_url = "http://img144.imageshack.us/img144/3264/89488358eh5.jpg"
profile_url = "https://www.blogger.com/profile/10873105042013904968"
comment_url = "https://mos3abof.blogspot.com/2007/04/4.html?showComment=1177598160000#c7105743211453923308"
text = "احم احم...بص يا مصعب ..انا عارفة ان يمكن دى اول مرة اعلق فيها عندك ...لكن انا متابعة البلوج بتاعك من مدة...ومع الاسف كل مرة معرفش اعلق على اللى انت كاتبه ..معرفش ليه!!بحس ان معنديش حاجة اقولها..يمكن عشان معظم الحاجات اللى انت بتكتبها هنا فى البلوج بتاعك خاصة بيك انت وصحابك لكن معرفش ليه كلامك بيأثر فيا اوى ..بحس ان الدنيا لسه بخير ..اينعم انا مؤمنة بالنظرية اللى بتقول مفيش  حد عدل دلوقتى ومفيش حد يستاهل اصلا ان حد يحرق نفسه عشان التانى.. بس انت بوظتلى نظريتى دى يا عم مصعب<br />                    تحياتى ليك"

[[comments]]
author = "ola salem"
date = "2007-04-26T12:51:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjHFDt3TCMySOaOIfSKy1pm6Fftth7KbZ_FXRBySjWFuS7GVEefAkoeQ4UT7wLJKsNj-DSKxiKoIDNRQxC5kWxU39tZKuKXxikTJMw7maf5gEdDgr9yq5SBrSAtNlvcZw/s220/ola.jpg"
profile_url = "https://www.blogger.com/profile/16188352166168735049"
comment_url = "https://mos3abof.blogspot.com/2007/04/4.html?showComment=1177584660000#c2294196900340391948"
text = "هههههههههه<br />والله يا مصعب انت حته سكره<br />الف مبروك لبيرو طبعا ودعاء السكرة<br /> الاتنين اطيب من بعض الصراحة<br />نا معرفتى بيهم مش قوية جدا بس بخترمهم جدا عشان يستاهلوا بجد<br />وحكاية العيال دى ربنا يكرم فيها <br />ههههههههه <br />انا كل اللى كان شاغلنى ساعة اما براء قالى فرحى يوم الجمعة انه كان هيتجوز قبل الصلاة ولا بعدها<br />ولما سألته افتكرنى بهزر وقعد يهزر هو كمان <br />الف الف الف مليون مبروك يا بيرو انت ودعاء وعقبال ما نشوفك كده رايح توصل عيالك عالمدرسة <br /><br />علا"

[[comments]]
author = "البراء أشرف"
date = "2007-04-26T11:40:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjR5QwG3EKgc90btNCRDohKP-WGgiLKAQTNIDurR7dtvfhnepaXeKFtCcsCxYvRAUzdEZm9oicrHBqzRWws8HEbVWGwlA8yUn3xQg-aomFeCIfdRcqXMZNIhyY37_pyH9M/s220/n691415567_1097076_8349.jpg"
profile_url = "https://www.blogger.com/profile/00023818092400005677"
comment_url = "https://mos3abof.blogspot.com/2007/04/4.html?showComment=1177580400000#c960672995796459133"
text = "لالالالالالا بجد.. <br /><br />هو أنا مفروض أرد على الكلام ده.. <br /><br />يا نهار يا نهار.. <br /><br />لا يا عم.. الصلح خير!<br /><br />أنت أكيد تقصد حد تاني غيري.. <br /><br />صح يا رفعت.. هو يمكن يقصدك أنت.. أنتوا أصحاب حقيقيين قوي، وقريبيين من بعض الفترة اللي فاتت، يمكن يقصد حد من أصدقاء طفولت.. <br /><br />مش عارف.. <br />على قد ما أنا فرحان، على قد ما أنا بشك إنها مكتوبة عشاني.. <br /><br />يمكن عشان بلوم نفسي شوية إننا مش عارفين نلاقي وقت نقعد فيه مع بعض الفترة اللي فاتت.. <br /><br />مش عارف يا مصعب. <br /><br />أنا مش عارف أكتب بصراحة<br /><br />متلخبط<br /><br />الله يسامحك<br />ويكرمك<br />ويزيدك حب الناس ليك وحبك للناس<br />ويكرمك ببنت حلال مصفي<br />وبعيال كتير كتير كتير <br />وتشتغل في جوجل<br />لأ<br />تشتري جوجل<br />وتستلف مني شوية فلوس تكمل بيهم على اللي معاك وتشتري جوجل<br />وتضم جوجل لعشرينات ويبقى اللينك بتاعه : <br /><br />google.20at.com<br /><br />مصعب<br /><br /><br /><br />أنا بحبك"

[[comments]]
author = "ام مليكة"
date = "2007-04-26T11:34:00.000+02:00"
avatar_url = "http://admins.20at.com/do3a2/bentbalad.jpg"
profile_url = "https://www.blogger.com/profile/17720828413632673574"
comment_url = "https://mos3abof.blogspot.com/2007/04/4.html?showComment=1177580040000#c7852953166600545568"
text = "مصاعيبوووووووووووووووومرسي يا مصعب الخير والجمال والحب والامل عارف يا مصعب انت فاكر لما انا كنت باقول امنيتي  فاكرها ولا نسيت \"اني اخلف ولد مؤدب زي مصعب بس يكون شبه بيرو \" بجد مش هزار انا لسه بتمنى كده وبيرو  مزعلش خالص  لانه فاهم انا ليه باقول كده انا حاسه اني خطفت صاحبك منك  وفضل الاحساس ده مسيطر علي لفترة طويلة  بس دلوقتي مش حاسه كده حاسه انكم كسبتوا صديقة جديدة هي انا  مرسي يا مصاعيبو وبعدين تخيلت انك هاتجيب سيرة البسلة والمكرونة البشامل وانت ولا الهوا ماشي يا عمنا ربنا يخلي لك صاحب ونفرح بيك"

[[comments]]
author = "marwa salah"
date = "2007-04-26T11:08:00.000+02:00"
avatar_url = "http://photos1.blogger.com/blogger/6631/3271/1600/water.1.jpg"
profile_url = "https://www.blogger.com/profile/01915363504191088852"
comment_url = "https://mos3abof.blogspot.com/2007/04/4.html?showComment=1177578480000#c4167991787194016837"
text = "الف مبروك يا مصعب لصاحبك وعقبال ما يفرح بيك هو كمان وربنا يخليكم لبعض"

[[comments]]
author = "قضية عم أحمد    Ahmed Case"
date = "2007-04-26T10:17:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgV-wcarXLkgWhQQil5kwuYh3wp9AEWNEDcLSaQD2LN0vM_G4H9YJFgqa0XczHwll6yiqoYqdHkRIaOBrs7mUlUTV8btyQ-yKEFvsGrNIWlN99lkjHG8LD-zKscO0MMuVA/s220/DSC_7364.JPG"
profile_url = "https://www.blogger.com/profile/07000569434293484731"
comment_url = "https://mos3abof.blogspot.com/2007/04/4.html?showComment=1177575420000#c3764209259709549779"
text = "على فكرة يا مصعب <br />انت من اطيب واجدع الناس اللى شفتهم <br /><br />ربنا يحفظك اوي"

[[comments]]
author = "الحلم العربي"
date = "2007-04-26T10:15:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjTdgiumpfKeU2naMdOAloE5M1oaYUxfArfOm-cYGHKhHod2DcWaAVebA6VKkbv9pk9uWp_Z-NnV5w2gnJ4EA-IYjm_5-fcg71JsKExv1ITSlGWrTF8vM3eDe4tS8_NRSM/s220/strang3.JPG"
profile_url = "https://www.blogger.com/profile/08895879839574889127"
comment_url = "https://mos3abof.blogspot.com/2007/04/4.html?showComment=1177575300000#c870151436939765270"
text = "بسلامته بيخطب....كانت مقالة جميلة ...أنا فاكراها لغاية دلوقتى كانت حاجة كده على شكل سيناريو بس كان كوميدي جدا ..انا يومها خليت عيلتى كلها تقراها...<br />أما بقى عن مشاعرك الجميلة الواحد ما يقدرش يقول غير ربنا يخليكوا لبعض و يبعد عنكوا العين و يديم المودة بينكوا و محدش فيكوا يتغير أبدا من ناحية التانى مهما عملت فيه الدنيا...ربنا يوفقكو...و ما تتأخرش علينا تانى في التدوين مهما كنت مشغول احنا بننتظر تدويناتك بفارغ الصبر"

[[comments]]
author = "قضية عم أحمد    Ahmed Case"
date = "2007-04-26T10:14:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgV-wcarXLkgWhQQil5kwuYh3wp9AEWNEDcLSaQD2LN0vM_G4H9YJFgqa0XczHwll6yiqoYqdHkRIaOBrs7mUlUTV8btyQ-yKEFvsGrNIWlN99lkjHG8LD-zKscO0MMuVA/s220/DSC_7364.JPG"
profile_url = "https://www.blogger.com/profile/07000569434293484731"
comment_url = "https://mos3abof.blogspot.com/2007/04/4.html?showComment=1177575240000#c4952586903978691674"
text = "مصعب الحبوب <br />بصراحة البوست اللي انت كاتبه ده خاص اوي وحساس اوي وتقريبا محدش هيعرف يعلق كويس ويفهم اوي غير براء . <br />انصحك حبيبي نصيحتي الدائمة <br />ان في هذا الكون اناس لا يمرون في حياتنا الا مرة واحدة فاذا وجدتهمفحافظ عليهم لانهم اذا ذهبوا لن يعودوا مرة اخرى فهم لا يمرون في العمر الا مرة . <br /><br />ربنا يحفظكم لبعض ويجعل حبكم فب الله"

[[comments]]
author = "Salma Amer"
date = "2007-04-26T08:41:00.000+02:00"
avatar_url = "http://farm2.static.flickr.com/1132/1365681113_f20faceeb5.jpg?v=0"
profile_url = "https://www.blogger.com/profile/08716194696950096714"
comment_url = "https://mos3abof.blogspot.com/2007/04/4.html?showComment=1177569660000#c2637721904325109163"
text = "الف الف مبروك لدودو وبيرو يارب يسعدكم ويهنيكم ببعض لانكم فعلا ناس تستهلوا كل الخير اللي في الدنيا وانا اتبسطت جدا أني اتعرفت عليهم الفترة اللي فاتت . وانت كمان يا مصعب ألف مبروك وعقبال لما تشوف أحفدهم مش اولادهم بس زي ما حلمت."

[[comments]]
author = "Anonymous"
date = "2007-04-26T06:55:00.000+02:00"
avatar_url = ""
profile_url = ""
comment_url = "https://mos3abof.blogspot.com/2007/04/4.html?showComment=1177563300000#c627875790394134406"
text = "السلام عليكم و رحمة الله و بركاته<br />تصدق انا فيا حاجة لله <br />يا خلاسي على حلاوتكو.. و ربنا انتوا عيال عسل .. مش عارفة و الله اقول ايه لان وشي فلّق من الابتسامة الغبية اللي معلقة من ساعة ما بدأت اقرا البوست <br />المهم ربنا يخليكوا لبعض و يديم عليكوا المحبه و الوفاق و.. مش عارفة ..بس ربنا عارف النيه و هايستجيب ان شاء الله<br />احلى حاجة ان انا اخر واحدة علقت على البوست اللي فات-امبارح-و كنت طالبه لما ادخل تاني الاقي بوست جديد .... و فعلا لقيت -النهارده-... ربنا يكرمك يا مصعب يا رب يا رب يا رب<br /><br />the wall"

[[comments]]
author = "حلم الحرية"
date = "2007-04-26T02:36:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj5134mBTHr7rVK3DSDgnRf5E_RugYPeh5cWZbeDoXKvwsHyL4tD1n_WEYXUeoJ4PMOSErPXCdUpGN274-0C5lbxDHtZQHsGch0ykrvpLnt52BWXdtpgWRytPSyMnw4MA/s1600/*"
profile_url = "https://www.blogger.com/profile/16809490468014096848"
comment_url = "https://mos3abof.blogspot.com/2007/04/4.html?showComment=1177547760000#c8835488843290275326"
text = "تمت أو هكذا يهيأ لي..<br />ــــــــــــــــــ<br /><br />لا يا مصعب <br />الكلمة الصح مش تمت ...لا..بدات<br />حياة جديدة بدات<br />اسرة جديدة ودنيا جديدة بدات <br /><br />ربنا يرزقهم السعادة ويظلل حياتهم بالحب دايما<br />ويخليك لصاحبك وتفضل معاه ..مش لحد مراتي بتولد.. لا لغاية انا نازل اخطب لابني تعالي معايا يا مصعب ما انت عمه"

[[comments]]
author = "Anonymous"
date = "2007-04-26T02:33:00.000+02:00"
avatar_url = ""
profile_url = ""
comment_url = "https://mos3abof.blogspot.com/2007/04/4.html?showComment=1177547580000#c7998921472219448836"
text = "الف مبروك لهذا الزواج المبارك والخلف الصالح بارا بوالديه ، لقد اعجبتنى هذه الاسره الصغيره الودوده فلقد ذكرتنى بمشاعرى تجاه اصدقاء عمرى الذين افتفدهم كثيرا وعقبال ما صاحبك يقف لك فى زواجك ان شاء الله<br />نيره عصام عبد المحسن"

[[comments]]
author = "Mony The Angel"
date = "2007-04-26T00:26:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjj4h6hlbKyUklJB5J_QeHmZidZ8mEHO-s5lWgxcP3qUEQSPg4AS0GkKHyrjWHC4Z5y2O3vBW2OY7WPf-cZ0PSVMC-DcEJ6cu6SRYKhpVq1jh6S9ve07RM4o8WgdU_8rxE/s220/mine...jpg"
profile_url = "https://www.blogger.com/profile/02273268851121458996"
comment_url = "https://mos3abof.blogspot.com/2007/04/4.html?showComment=1177539960000#c7116845363720587518"
text = "ana lamma ereet al post kan there's no comments<br />bas 3alabaal ma 7'alast w lafeet laffet om al3aroosa<br />gete l2eet al commentata ad kda :D<br />yalla msh 7'sara felpost 3shan a2raah 3ala fehm :))<br /><br />bas ma2oltelnaash al nono esmo/aha eh ;) ??"

[[comments]]
author = "LAMIA MAHMOUD"
date = "2007-04-25T23:30:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj9Eh5lF-XRHtud8suhl5K4yhMxWsSKxr7oyl2dnkn5hzt8OEtado-gJjkufoVPTgqAHHfWXLwNj3X6sZUl4NWiUVH9XjUZWWmADmu-GQHwrYWvQyo2KAfaSJmBtk1jSw/s220/lets-dance-2.jpg"
profile_url = "https://www.blogger.com/profile/05758996758350593398"
comment_url = "https://mos3abof.blogspot.com/2007/04/4.html?showComment=1177536600000#c3419108759173833118"
text = "سيبك انت احلى حاجة في البوست انه باين فيه نقاء مشاعرك وقد ايه انت حد بيحب اصحابه اوي<br /><br />ربنا يخليلك اصحابك ويخليك ليهم"

[[comments]]
author = "Lens Geek"
date = "2007-04-25T23:22:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhDH6cac8DhCu85r5fVw0KJDQyTSgnbUN_on5yZRrtKG44soaS5wrAZnDMZBnmYItm4PSgM5Be26Q5kswvv4w84fGE-zjxA4uFGBZW67q5kjJzKnPEAcvpMpdz-KsYUpg/s220/Ahmed2.gif"
profile_url = "https://www.blogger.com/profile/08391635125789451063"
comment_url = "https://mos3abof.blogspot.com/2007/04/4.html?showComment=1177536120000#c8911802058073013509"
text = "الله،هيه دي الصداقة كل كلمه قلتها اثرت في اوي فعلا شريط الذكريات بيطول كل ما عمر الانسان بيطول ! المهم ربنا يكرمك و تعملها زي ما براء عملها و انا  اكتبلك حتت تتدوينه تهز البلجسفير * كلها ان شاء الله<br /><br />* Blog sphere"

[[comments]]
author = "دينا فهمي"
date = "2007-04-25T23:00:00.000+02:00"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/07685435794478937439"
comment_url = "https://mos3abof.blogspot.com/2007/04/4.html?showComment=1177534800000#c268415095502329784"
text = "بسم الله ما شاء الله<br />ربنا يبارك لهم يا رب<br />وعقبالك يا مصعب<br /><br />بجد تعبيرك حلو أوي"

[[comments]]
author = "Angel"
date = "2007-04-25T22:33:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiBB0l4hrjG6YwtvhjW50fBh0qgKq1tVvrgLvMFCjsXpssq7_JP-x8X_O-MS1tfHxAZZqqNd-3BYZZFPAmK1ODxYlNBTQgTUIZzC_4y723TdF-F8UeoYNZx4f4C2T2Qxw/s220/WXD57840.jpg"
profile_url = "https://www.blogger.com/profile/14016929410723462752"
comment_url = "https://mos3abof.blogspot.com/2007/04/4.html?showComment=1177533180000#c8070888343411669476"
text = "اولا مبرووووووك لبراء ودعاء <br /><br />ويارب تدوم المحبه والصداقه اللي بينكم <br />مصعب<br /> احساسك حلو وروحك احلى ^^"

[[comments]]
author = "اميرة هشام"
date = "2007-04-25T22:26:00.000+02:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgzhHsKSw_63WMVYoxM1E7Gqma2VMArukpqj1084AIl6g7XJS2oC7MDNhOm01CT3678md0HSGIHEpoYkK2Er6QGarwKHFwUItjRFzsCMITsQJgcpqQmRiXJcZIY0MY9doU/s220/n1225417935_30237264_2188.jpg"
profile_url = "https://www.blogger.com/profile/16048503349469323361"
comment_url = "https://mos3abof.blogspot.com/2007/04/4.html?showComment=1177532760000#c4737334445797872052"
text = "مش انت لوحدك يامصعب اللي فرحانلهم<br /><br />كلنا كلنا كنا فرحانييييييييييين اوييييييييي<br /><br />بجد يوم الفرح بتاعهم ده بيمثلي شلال من الزكريات <br /><br />واول فرحة لينا <br />انا مشيت وانا مستنية  الفرحة اللي بعديها<br /><br />يارب يجعل كل ايامنا سعادة وهنا"
