[[comments]]
author = "الحلم العربي"
date = "2009-02-11T09:24:00.000+01:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjTdgiumpfKeU2naMdOAloE5M1oaYUxfArfOm-cYGHKhHod2DcWaAVebA6VKkbv9pk9uWp_Z-NnV5w2gnJ4EA-IYjm_5-fcg71JsKExv1ITSlGWrTF8vM3eDe4tS8_NRSM/s220/strang3.JPG"
profile_url = "https://www.blogger.com/profile/08895879839574889127"
comment_url = "https://mos3abof.blogspot.com/2009/01/blog-post_20.html?showComment=1234340640000#c7917733621021958374"
text = "ايوة انا بردو كنت بقول واحد عبقري زيك لازم يحب بطريقة مختلفة<br />هههههههههههه<br />ربنا يكرمكم و يتمم لكم بخير يا رب<br />و تفضلزا تحلوا في المعادلات دي مع بعض طول عمركم <br />:))))"

[[comments]]
author = "Anonymous"
date = "2009-02-10T19:56:00.000+01:00"
avatar_url = ""
profile_url = ""
comment_url = "https://mos3abof.blogspot.com/2009/01/blog-post_20.html?showComment=1234292160000#c1929709947201197315"
text = "الله يوفقك<br />هذه مدونة جميله<br />و سأواكب على قرائتها بإذن الله. تقبل تعليقاتي و تحياتي :)<br /><br />كنت أرغب عمل تبادل نصي مع هذه المدونة الجميله مع منتداي<br />http://7ama2i.com/forums/<br />منتظر ردك على بريدي<br />dito0o@yahoo.com<br /><br />أرجو حذف إيميلي بعد الموافقه على التعليق :)"

[[comments]]
author = "روح"
date = "2009-01-28T00:58:00.000+01:00"
avatar_url = "http://redondowriter.typepad.com/photos/uncategorized/268573778_a71bfed930.jpg"
profile_url = "https://www.blogger.com/profile/08902136818874003625"
comment_url = "https://mos3abof.blogspot.com/2009/01/blog-post_20.html?showComment=1233100680000#c3097512862913843527"
text = "ربنا يكرمكم ويوفقكم<br />تقبلوا خاللص تحياتي<br />ومنتظرة الزيارة"

[[comments]]
author = "Anonymous"
date = "2009-01-22T04:48:00.000+01:00"
avatar_url = ""
profile_url = ""
comment_url = "https://mos3abof.blogspot.com/2009/01/blog-post_20.html?showComment=1232596080000#c2258025001368335158"
text = "أزال أحد مشرفي المدونة هذا التعليق."

[[comments]]
author = "Anonymous"
date = "2009-01-21T18:19:00.000+01:00"
avatar_url = ""
profile_url = ""
comment_url = "https://mos3abof.blogspot.com/2009/01/blog-post_20.html?showComment=1232558340000#c8496815832766175947"
text = "مصعب و أميرة في نعيم!!"

[[comments]]
author = "Amr"
date = "2009-01-21T18:13:00.000+01:00"
avatar_url = "http://www.arttoheart.ca/newimages/blueflrs.jpg"
profile_url = "https://www.blogger.com/profile/03741243192561256269"
comment_url = "https://mos3abof.blogspot.com/2009/01/blog-post_20.html?showComment=1232557980000#c2496051537310378884"
text = "أحب أقول <br /><br />èpf`fçfpeçÑËïÑÔ"

[[comments]]
author = "moon"
date = "2009-01-21T18:09:00.000+01:00"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/06613187847365225877"
comment_url = "https://mos3abof.blogspot.com/2009/01/blog-post_20.html?showComment=1232557740000#c3421375364978933528"
text = "loooooooooool<br />aham 7aga ennoko ento el both fahmin :)"

[[comments]]
author = "أحمد الدريني"
date = "2009-01-21T13:18:00.000+01:00"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/17300680267091030312"
comment_url = "https://mos3abof.blogspot.com/2009/01/blog-post_20.html?showComment=1232540280000#c4603399408572384306"
text = "جمهورية \"ناش\""

[[comments]]
author = "Unknown"
date = "2009-01-21T13:13:00.001+01:00"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/09154367994040376200"
comment_url = "https://mos3abof.blogspot.com/2009/01/blog-post_20.html?showComment=1232539980001#c2652570596251030149"
text = "مصعب باشا<br />x + Y = 2(x+y)-2x+x.y<br />مساء الحنان"

[[comments]]
author = "menSh"
date = "2009-01-21T13:13:00.000+01:00"
avatar_url = "http://photos1.blogger.com/blogger/4938/2050/1600/am.jpg"
profile_url = "https://www.blogger.com/profile/14221308254991337821"
comment_url = "https://mos3abof.blogspot.com/2009/01/blog-post_20.html?showComment=1232539980000#c2794297879522072631"
text = "هي الفكرة بس إن  x (x-1) = x^2-x\\,. <br /><br />يعني لو (x + 1)^2 = 2x^2 + x + 1\\, كان ماشي!<br /><br />بس يللا.. معلش.. هداكما الله ووفقكما إلى ما يرضاه.. آمين :)"

[[comments]]
author = "Amimi Houssainy"
date = "2009-01-21T03:09:00.000+01:00"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgZ5U4WlzUss0uPIk6CIWOP39PIGRIka0M7X7oxQFac3IA96TWm6eSkn9diM-POEGc0GEEz-HFkLZbr4bOmskrn3xWyOUmDVdCHlqDBPy-seDBJISTCwtdUdRokxve19_M/s220/coustime_album.jpg"
profile_url = "https://www.blogger.com/profile/11706534749857063059"
comment_url = "https://mos3abof.blogspot.com/2009/01/blog-post_20.html?showComment=1232503740000#c3917687766700273240"
text = "ربنا يخليكوا لبعضكم، يا رب...بجد انتوا اسعد زوجين شفتهم في حياتي، عقبا لنا احنا كمان يا صاحبي...ادع لنا يا مصعب  انت كمان، عشان قربت التحق بيك في القفص الذهبي، حقيقي...مبروك...مبروك...مبروك...مبروك يا مصعب."

[[comments]]
author = "Amira Qassim"
date = "2009-01-20T23:25:00.000+01:00"
avatar_url = "http://img107.imageshack.us/img107/712/ice36pd7.jpg"
profile_url = "https://www.blogger.com/profile/08351482421774299913"
comment_url = "https://mos3abof.blogspot.com/2009/01/blog-post_20.html?showComment=1232490300000#c706931224915707771"
text = ":$<br />مصعب ..<br />ربنا يخليك ليا يارب، ويجي اليوم الي نكون فيه في بيت واحد، ونفضل كده على طول <br />وعاوزة أقولك إني مش محتاجة حاجة بعد الكلمة دي ..<br />ومن مكاني هذا أحب أقولك <br />           ³y ²x  = ³(1­ ²y +²x)"

[[comments]]
author = "محمد السيد..مش حاسكت"
date = "2009-01-20T23:19:00.000+01:00"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/15123433931771567833"
comment_url = "https://mos3abof.blogspot.com/2009/01/blog-post_20.html?showComment=1232489940000#c9212507523751188721"
text = "إنسان إنسان الصراحة ....<br /><br />حاجة ده شبه اشعار قيس ... وجميل ... وعنترة ...<br />حاجة لا تتوصف ولا تتحكي ,,, ولا ممكن تتسمع كمان ...<br /><br />دي تتحس وبس .... وبسسسسسس<br /><br /><br />ربنا يصبرك يابنتي ....<br />يااااااااااااااااااااااااارب"
