[[comments]]
author = "أميرة من غير قصر ولا بستان.. ولا الشاطر حسن كمان"
date = "2007-07-21T17:04:00+00:00"
text = "لو مصر ردت على جوابك يا مصعب ابقى قولها ان اننا كمان نفسى اعملها اى حاجه و مش لاقيه فرصه اصل كل ما اروح اسأل ف حته يقولوا لى عايزين خبره و ميعرفوش ان الحياه فيها ادتنا اكبر خبر"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEirdirzKebc0hcGC4MQ6kvVkx2q0MdxprJrl-jqSZ5l_jxE2bWsZVd-Pla_Zla1V4g0FjN5PUa4k3oTN0AO0cgFlRcbwr6XbP-7sqohbU_KGsAtNaDenb4eAJmqzrb0EGE/s220/blogpic5ke.jpg"
profile_url = "https://www.blogger.com/profile/16391848599214933906"
comment_url = "https://mos3abof.blogspot.com/2007/07/blog-post.html?showComment=1185037440000#c3919249389557930763"

[[comments]]
author = "Anonymous"
date = "2007-07-21T17:16:00+00:00"
text = "تعبير جميل... نثر ممتع.. ولكن في النهاية مصر كائن افتراضي لا شأن له بالواقع.. فلا داعي أن ندخلها في ما يحدث لنا.. فهذا شأننا نحن لا شأنها :)"
comment_url = "https://mos3abof.blogspot.com/2007/07/blog-post.html?showComment=1185038160000#c3189023206011642690"

[[comments]]
author = "Anonymous"
date = "2007-07-21T21:21:00+00:00"
text = "ابدعت اخي مصعب <br /> بارك الله في يمينك <br />كنت افكر في لوم من يظل يطالب وطنه ويلومها  دون ان يتحرك لكنك اوجزت بجملة جعلتني اتراجع بعض الشيء وهي <br />عزيزتي مصر..<br />أكثير عليّ أن أطلب أن تساعديني أن أكون ابنا بارا بك؟!!"
comment_url = "https://mos3abof.blogspot.com/2007/07/blog-post.html?showComment=1185052860000#c4253089552155657542"

[[comments]]
author = "أحمد الدريني"
date = "2007-07-21T22:23:00+00:00"
text = "عزيزي مصعب<br />مصر مرفوعة مؤقتا من الخدمة<br />مصرهم مصر قبيحة ووسخة<br />مصرنا بتاعتنا ممكن ترجعلنا..<br />اتصرف بقي يارب احنا زهقنا"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/17300680267091030312"
comment_url = "https://mos3abof.blogspot.com/2007/07/blog-post.html?showComment=1185056580000#c2656313345437974222"

[[comments]]
author = "أحمد عبد الفتاح"
date = "2007-07-21T23:11:00+00:00"
text = "عاشت بلدنا المنكوبة ... مصر"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjBEankZM8eqnMmm6H2qUuYBC3weT9HKhjtlpU9dAKIiaZsigEwFPgAhS28TpfN9Q8sPR-Gmtwf0ARei7KlSiK-Ujn_KRF9EyyfSEwoDVyR_8Ps5b7XCqqx5vmhSQaMSg/s1600/436599030_8f4a4e7f11.jpg"
profile_url = "https://www.blogger.com/profile/10557032081902417963"
comment_url = "https://mos3abof.blogspot.com/2007/07/blog-post.html?showComment=1185059460000#c1512611864207521507"

[[comments]]
author = "عمر عاشق القرآن"
date = "2007-07-22T01:10:00+00:00"
text = "جميل يا ابنى والله أثرت فيا <br /><br />فكرتنى بموضوع كتبته زمااااااان عن مصر <br /><br />أصل انا اكتشفت ان مصر مش أمنا بجد هى يمكن لقيتنا فى الشارع او هى مراة ابونا او الظاهر ولاد مش شرعيين <br /><br />متعرفش بقى !!!!!!<br />بس جامد يا مصعب"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/03483148284575692297"
comment_url = "https://mos3abof.blogspot.com/2007/07/blog-post.html?showComment=1185066600000#c6443979972685367859"

[[comments]]
author = "ســـارة"
date = "2007-07-22T03:49:00+00:00"
text = "مناجاة جميلة لبلدنا<br />مليئة بآلام جيلنا<br />ويظل التساؤل قائماً : هل تسمح لنا مصرنا بأن نؤدي لها واجبها؟"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgQlWSJKlN2FTbvAXEdMe8PiTLeHfO6peazIGd9hsMEEZs4GfgZk5P3p4rAqZo33QNM-n9H5PAMspCxoYZWDrNSHsqMGdMd2gCQf-n7rGYQkprkUliL_CevB5w98I4ShyM/s220/18732_328127670201_629925201_5206552_2916529_n.jpg"
profile_url = "https://www.blogger.com/profile/03269418268550982678"
comment_url = "https://mos3abof.blogspot.com/2007/07/blog-post.html?showComment=1185076140000#c5146390805501307540"

[[comments]]
author = "We2am"
date = "2007-07-22T11:04:00+00:00"
text = "mmmm..wlhy msh 3arf 22olk eh...7tta dah maynf3sh..wl3lmk masr msh hatsebk t3ml ay 7aga..ela lama teqarr tmot..sa3et.ha haatsebk tent7r..wtnwalk elsem b2edha :("
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhQcQ1ZEVto0d3Q-8SYrlhPe65gtdb7vieD2O9VTjley8Ol9gRSSIxfYCsbogR3Vwo_4gVGfgbPaXcMMYxpPYMmGgitzKr2RN8hp4O1ZV_ezx9D2Wqd3AhCUjMKrXUByu0/s113/14803259_10154014513627023_722172126_o.jpg"
profile_url = "https://www.blogger.com/profile/11798083370261251218"
comment_url = "https://mos3abof.blogspot.com/2007/07/blog-post.html?showComment=1185102240000#c445650525722299533"

[[comments]]
author = "MariumaZ"
date = "2007-07-22T11:14:00+00:00"
text = "بصراحة لما كانوا بيقولوا لنا مصر دي أم الدنيا كنت بقول دنيا مين؟؟؟<br />يعني مش أمنا إحنا المصريين .. أم الناس  الدونيين فقط .. الناس الدوون<br /><br />مصر مش حاسة إنها بتاعتي<br />بلد ما بتديش حاجة علشان الواحد يديها<br />إحساسي تجاها عالي أوووي .. بس بديها زي ما كنت حدي في أي بلد برة ويمكن أقل<br /><br />ما بحبش أوسخ شوارعها وبحبش حد يجيب سيرتها بحاجة وحشة برة بس في نفس الوقت بكره حكومتها وكثير من ناسها اللي فقدوا الطيبة والبراءة من زمان ومفضلهومش غير الهمجية والفقر والعنف<br /><br />في ناس كتير بتقول مصر مابقتش زمان ... وزمان الناس كانت بتقول برضه مصر مابقتش زي زمان<br /><br />لكن هو زمان ده كان عامل زاي؟؟؟<br />نفسي أعرف مين اللي المفروض يدي مين؟؟؟<br />إحنا اللي ندي مصر ولا مصر هي اللي تدينا ... هي فعلاً بتدينا ... بتدينا على دماغنا وبتدينا على قفانا"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg9giUV2iCTwwtfQoUxjZXLMjO4Scq0iKCUdYMCgmovIiMOde9B26aqPY_6wwiZy8PHqssu8sQSZDgaBjnhd_kQL0aeEev2mUQs1l-tOOUp6mUNQV2JilPBktEhrS_AHqU/s220/IMG_0084.jpg"
profile_url = "https://www.blogger.com/profile/12796121153780883763"
comment_url = "https://mos3abof.blogspot.com/2007/07/blog-post.html?showComment=1185102840000#c3044795456962357810"

[[comments]]
author = "قضية عم أحمد    Ahmed Case"
date = "2007-07-22T11:28:00+00:00"
text = "عزيزتهم مصر <br /><br />المشكله مش فيكي المشكله في اللى فيكي . <br /><br />عزيزتهم مصر <br /><br />بحبك ومش عارف ادوب فيكي <br /><br />عزيزتهم مصر <br /><br />حزين لك ولكني لازلت أحبك"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgV-wcarXLkgWhQQil5kwuYh3wp9AEWNEDcLSaQD2LN0vM_G4H9YJFgqa0XczHwll6yiqoYqdHkRIaOBrs7mUlUTV8btyQ-yKEFvsGrNIWlN99lkjHG8LD-zKscO0MMuVA/s220/DSC_7364.JPG"
profile_url = "https://www.blogger.com/profile/07000569434293484731"
comment_url = "https://mos3abof.blogspot.com/2007/07/blog-post.html?showComment=1185103680000#c8414327537742784968"

[[comments]]
author = "Lens Geek"
date = "2007-07-22T12:02:00+00:00"
text = "صراحة يا مصعب انا مش حاسس بوجود حاجه اسمها مصر. الي انا اعرفه كالاتي:-<br />مكان بنعيش فيه مليان ناس مضايقه و عرقانه و حر و هواء ملوث و بطاله و احلام محطمه و ناس سلبيه و ناس تانيه مستبده و ممشينها بالدراع و ناس عماله تتكلم عن 7000 سنه مبقاش منها الا شوية حجاره (مع العلم ان كتير من الحجاره معرفناش نحافظ عليها) و ..... الخ. ممكن نسمي ده مصر او نسميه اي حاجه تانيه دي مش فرقه و مدام مفرقتش المسمى اذن مفرقش اذا انا كنت عايش في مصر او عايش في اليمن !!!<br /><br />اخوكوا ابو رجل منمله من كتر ركوب الميكروباصات  احمد عبدالله!!"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhDH6cac8DhCu85r5fVw0KJDQyTSgnbUN_on5yZRrtKG44soaS5wrAZnDMZBnmYItm4PSgM5Be26Q5kswvv4w84fGE-zjxA4uFGBZW67q5kjJzKnPEAcvpMpdz-KsYUpg/s220/Ahmed2.gif"
profile_url = "https://www.blogger.com/profile/08391635125789451063"
comment_url = "https://mos3abof.blogspot.com/2007/07/blog-post.html?showComment=1185105720000#c2981482630178883364"

[[comments]]
author = "Salma Amer"
date = "2007-07-22T14:42:00+00:00"
text = "طبعا احنا بقلنا فترة بتكلم في الموضوع ده انا وانت .<br />وسألت سؤال سعتها هو ممكن نحب البلد من طرف واحد يعني احنا نحب البلد وهي لا تبدلنا نفس الشعور ولا ده حب من طرف ثالث ولا اية <br />ونعمل اية وانت بتحاول تعمل حاجة ومفيش اي حاجة مسعداك"
avatar_url = "http://farm2.static.flickr.com/1132/1365681113_f20faceeb5.jpg?v=0"
profile_url = "https://www.blogger.com/profile/08716194696950096714"
comment_url = "https://mos3abof.blogspot.com/2007/07/blog-post.html?showComment=1185115320000#c85737116682424220"

[[comments]]
author = "الحلم العربي"
date = "2007-07-22T20:33:00+00:00"
text = "ياااااااااااه يا مصعب بتغيب تغيب و ترجعلنا بتحفة جميلة<br /><br />مصر بنت غريبة تاهت وسط الزحمة ...كل اللى حواليها كبار ...ماشية وسطهم و خايفة يدوسوا عليها ...عمالة تناديلهم و محدش سامعها...مفيش غير شوية ناس بيبصوا عليها من البلورة المسحورة و بينادولها زيك و زينا كلنا ...تفتكر هي هتسمعهم وسط كل الزحام ده؟؟<br /><br />لازم ندخل جوة و نروحلها احنا و نقولها : أأمرينى هكون معاكي ...هحميكى منهم حتى لو دفعت حياتى ...كفاية انك تعيشي دي كل أمنياتي<br /><br /><br />تحياتى ثم تحياتي ثم تحياتي"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjTdgiumpfKeU2naMdOAloE5M1oaYUxfArfOm-cYGHKhHod2DcWaAVebA6VKkbv9pk9uWp_Z-NnV5w2gnJ4EA-IYjm_5-fcg71JsKExv1ITSlGWrTF8vM3eDe4tS8_NRSM/s220/strang3.JPG"
profile_url = "https://www.blogger.com/profile/08895879839574889127"
comment_url = "https://mos3abof.blogspot.com/2007/07/blog-post.html?showComment=1185136380000#c600947921665662826"

[[comments]]
author = "MarwaAshraf"
date = "2007-07-22T22:35:00+00:00"
text = "وما ذنب مصر يارجل ؟<br /><br />لا أعتقد أنها السبب فيما أنت فيه .. إبحث عن السبب الحقيقي <br /><br />ولعلمك مصر هي التي ستخرجك من جمودك..<br /><br />بوست أكثر من رائع .. تحياتي"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/12117806503113618382"
comment_url = "https://mos3abof.blogspot.com/2007/07/blog-post.html?showComment=1185143700000#c8406896597006177151"

[[comments]]
author = "Anonymous"
date = "2007-07-23T12:49:00+00:00"
text = "هو فيه مشكلة أكبر من ان ولادها مش عارفين يخدموها او بشكل ادق مش مسموح ليهم يخدموها<br />يا رب والله نتوفق في خدمتها"
comment_url = "https://mos3abof.blogspot.com/2007/07/blog-post.html?showComment=1185194940000#c2985399977673331930"

[[comments]]
author = "سارة بندارى"
date = "2007-07-23T21:51:00+00:00"
text = "هههههههههه<br /><br />اسلوب ساخر <br /><br />بس رائع <br /><br />جزاك الله خيرا"
avatar_url = "http://bp1.blogger.com/_Uw_yud2ML0Y/R6ECnB4yENI/AAAAAAAAAIY/RQuMV_3l1gI/S220/Copy+of+sara.gif"
profile_url = "https://www.blogger.com/profile/14512357164215137478"
comment_url = "https://mos3abof.blogspot.com/2007/07/blog-post.html?showComment=1185227460000#c2312789333909440719"

[[comments]]
author = "dead man"
date = "2007-07-24T15:59:00+00:00"
text = "يا حبيبي علي راي المسيو عادل امام البلد دى اللي يشوفها من فوق غير اللي يشوفها من تحت<br /><br />تعالي منفكرش في اللي فوق ونفرح باللى تحت.. تحت ادينا.. كباية شاي تحت كوبري قصر النيل.. شوية نتمشي علي الكورنيش.. وسط البلد الساعة 2 بالليل.. عربية الفول.. شط اسكندرية.. سندوتشين كبده من عند علي بركة.. <br /><br />مش عارف ليه يا مصعب حاسس أن اللى انت كتبته ده ترجمة لنقش كتبه واحد من العبيد اللى بنوا الهرم وانت جاى النهاردة تفكه"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgblVMh7Nlr7ton4EF6_WEIvx8uFAb-eyxAuL1LWv4FXTV92r6gCplvVR4alR4sN7zoTvIKKNYNdwspZiK_KxIj22bYHSiigq8zeWWpnNoyw8kdaUTj-R6MOh9v1vhBvNg/s220/wait.jpg"
profile_url = "https://www.blogger.com/profile/10592260848284665609"
comment_url = "https://mos3abof.blogspot.com/2007/07/blog-post.html?showComment=1185292740000#c7227526684105303624"

[[comments]]
author = "محمود على"
date = "2007-07-25T09:05:00+00:00"
text = "<B><br />عمرها مهترد عليك<br />مصر في ايامها الاخيره <br />لا مستنيه واجبات <br />ولا هتديك حقوق<br /></B>"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjJUDiBlq5tkNO4o15Ei8pp8HMne-l_77JuK-151SVcNE5mAOy6pPF9RfaxO56ViBAXfGF0xZclD8XXhhSkaTy6_iDzePyhcXCplhOlu2fZ7zQLbPkV8qwD-XWRfDY5fA/s400/desert-for-baby.jpg"
profile_url = "https://www.blogger.com/profile/08431473033254491017"
comment_url = "https://mos3abof.blogspot.com/2007/07/blog-post.html?showComment=1185354300000#c6118017426533195615"

[[comments]]
author = "moodysalihamidzic"
date = "2007-07-26T12:40:00+00:00"
text = "لازم تديها حقها<br />ولازم تطالب بحقوقك"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjw3-k6mbp2_HFYeMui6SVJpEsfGMYABElP-WuyAJsrbLQDEBO0j16bMmMybdf3KEXi-0H14hx6cNHzfa06s6QL0k_XNbyPSsZqGkDekeA350iefVq7Q7AXwo94chgQEQ/s220/mmmmmm.jpg"
profile_url = "https://www.blogger.com/profile/07854567324462397155"
comment_url = "https://mos3abof.blogspot.com/2007/07/blog-post.html?showComment=1185453600000#c2607803696959236935"

[[comments]]
author = "Anonymous"
date = "2007-07-26T23:44:00+00:00"
text = "يا عم ما تقلبش علينا المواجع بقى<br />احنا عمالين نؤدى فى واجبات ليل نهار ..احنا عاوزين حقوقنا شويه"
comment_url = "https://mos3abof.blogspot.com/2007/07/blog-post.html?showComment=1185493440000#c7762124422678506169"

[[comments]]
author = "سكوت هنصوت"
date = "2007-07-27T11:28:00+00:00"
text = "مصعب<br /><br />محتاجين دعمك و مساندتك في حملة معا للقضاء على الكيف..الحملة بتفاصيلها موجودة عند صاحب البوابة و عندي..العنوان هو www.elbawaba.blogspot.com تعالى بسرعة...منتظرينك هناك"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/04457878477221973610"
comment_url = "https://mos3abof.blogspot.com/2007/07/blog-post.html?showComment=1185535680000#c2152398302879641966"

[[comments]]
author = "حلم الحرية"
date = "2007-07-27T16:35:00+00:00"
text = "مصر بتاعتنا غير مصر بتاعتهم<br /><br />مصر بتاعتنا بحبها وباموت فيها<br /><br />ومهما عملوا فيا مش هيخلوني اكرهها <br />في  يوم <br /><br />بس يا تري بتحبني زي ما باحبها"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj5134mBTHr7rVK3DSDgnRf5E_RugYPeh5cWZbeDoXKvwsHyL4tD1n_WEYXUeoJ4PMOSErPXCdUpGN274-0C5lbxDHtZQHsGch0ykrvpLnt52BWXdtpgWRytPSyMnw4MA/s1600/*"
profile_url = "https://www.blogger.com/profile/16809490468014096848"
comment_url = "https://mos3abof.blogspot.com/2007/07/blog-post.html?showComment=1185554100000#c7466717389666022338"

[[comments]]
author = "Anonymous"
date = "2007-07-28T21:27:00+00:00"
text = "بالفعل فنحن لا نريد من مصر شىء ولا حقوقها التى لنا<br />ولكنى لا الوم مصر بل الوم حكامها<br />لانهم اخذوا منا كل عزيز فمن ابسط حقوقها علينا ان ترد لنا كل غائب  <br />اللهم فرج كربه ابى ومن معه<br />وجزاك الله خيرا على هذه التدوينه الرائعه<br />نيره عصام عبد المحسن"
comment_url = "https://mos3abof.blogspot.com/2007/07/blog-post.html?showComment=1185658020000#c4165414833833841993"

[[comments]]
author = "غجرية"
date = "2007-07-29T01:45:00+00:00"
text = "so beautifule, so painfully true"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiPVmMqNIvt4lArIE28cI1BlYHBjmZHKW2ONIPIXKwSpnpkK9Y4v4d1g7sSmVDiNDbKemjHVM2Wcu0BuonmXWYyISZFSGkFFRIGdFDmXIoDJ58mXAtca5dqnNG7p7pbIw/s220/i_lovewhoiam@hotmail_com_a90ca9b7.jpg"
profile_url = "https://www.blogger.com/profile/15055816453264731358"
comment_url = "https://mos3abof.blogspot.com/2007/07/blog-post.html?showComment=1185673500000#c8624008185799474566"

[[comments]]
author = "Anonymous"
date = "2007-07-31T11:03:00+00:00"
text = "بس تفتكر ان مصر هتسمعك او جوابك دة هيوصلها<br /><br />انا عن نفسي مش افتكر<br />لاننا في بلد تانية غير مصر<br /><br />اسكت مش غيروها <br />:))"
comment_url = "https://mos3abof.blogspot.com/2007/07/blog-post.html?showComment=1185879780000#c2799538558794840570"

[[comments]]
author = "Mony The Angel"
date = "2007-08-01T00:10:00+00:00"
text = "aah tab3an keteer 3aleek<br />enta 3andak shak walla eh lol"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjj4h6hlbKyUklJB5J_QeHmZidZ8mEHO-s5lWgxcP3qUEQSPg4AS0GkKHyrjWHC4Z5y2O3vBW2OY7WPf-cZ0PSVMC-DcEJ6cu6SRYKhpVq1jh6S9ve07RM4o8WgdU_8rxE/s220/mine...jpg"
profile_url = "https://www.blogger.com/profile/02273268851121458996"
comment_url = "https://mos3abof.blogspot.com/2007/07/blog-post.html?showComment=1185927000000#c2927236474641730036"

[[comments]]
author = "Doba"
date = "2007-08-07T12:13:00+00:00"
text = "مصر جميلة قوى دائما وابدا - بس فعلا العيب فى اللى فيها واللى معمرينها<br /><br />وزى مقلت - ياريت فعلا كل واحد يبتدى بنفسه ويبتدى يدلها حقوقها ويعمل واجباته ناحيتها - ولو الطريق ضلمة اكيد اكيد - هيكون النور فى نهاية الطريق<br /><br />ربك كبيييييييييير قوى ويمهل ولا يهمل<br />بوست جميل قوى<br />تحياتى -- هبة"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjs66fYKEgBQnN5HavnilBiowtiwJYPCZmh2GYYzGjPoYSsiZqOJiphwkv49UwLobvwRn0BbTdKH0ZXmQzwoBbdmsS2i75T4b7gUR3KkNTpO6qsuRD_7IzJrV_GfAm_WA/s220/artwork30.jpg"
profile_url = "https://www.blogger.com/profile/02122322922502722638"
comment_url = "https://mos3abof.blogspot.com/2007/07/blog-post.html?showComment=1186488780000#c2458022291035221053"

[[comments]]
author = "weswes"
date = "2007-08-08T11:52:00+00:00"
text = "بص يا مصعب <br />مصر شبكتها واقع بقلها كام عقد من السنين<br />فتاكد اذا كنت باعت الرساله دى على الموبيل يبقى اكيد مش هتوصل<br />ولو بعتها على النت خلاص يا حج هيحجروا على النت واكيد برضوا مش هتوصل<br />انما بقى لو فى البريد عادى<br />فصدقنى الجوبات فى مصر بضيع وبرضوا مش هتوصل<br />فلو مش ردة عليك مش تبقى تزعل علشان كل الاتصلات منعنها عنها<br />على رائ اغنية كاظم الساهر ممنوعة انتى"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiw4snw0O4r8EYHQhiu7PCP3YXbjsOVmNj5zsVG2NmG_iJW8qfvdrvDKQVVXpYEQyxkgnLEal7LDhjHT9wSDmHEaztJc2mql6BgND38sUt9YXFFoG0Id5pU9R8WI3ItEKo/s220/IMG_0034.JPG"
profile_url = "https://www.blogger.com/profile/04810150175952124524"
comment_url = "https://mos3abof.blogspot.com/2007/07/blog-post.html?showComment=1186573920000#c155196857436459898"

[[comments]]
author = "حروف تايهه"
date = "2007-08-09T14:21:00+00:00"
text = "بوست رائع يامصعب ومدونة رائعه <br />حسيت إحساسك ومشاعرك <br />لكن أنا واثق ان مصر فى الفترة الجايه هتتغير <br />مادام بقى فيه ناس بتقول لأ ده غلط وعددهم كتير أكيد فى أمل"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/08771414174830500141"
comment_url = "https://mos3abof.blogspot.com/2007/07/blog-post.html?showComment=1186669260000#c5192455546970168449"

[[comments]]
author = "حسام مراد"
date = "2007-08-12T15:31:00+00:00"
text = "بوستك شغاااااال<br />وكلمه جميله  اسمها مصر <br />!!!!!!!!!!! مصر الى اين"
avatar_url = "http://photos1.blogger.com/x/blogger2/3380/744879211792750/269/z/187482/gse_multipart9688.jpg"
profile_url = "https://www.blogger.com/profile/04927063046161770148"
comment_url = "https://mos3abof.blogspot.com/2007/07/blog-post.html?showComment=1186932660000#c7068341078849867190"

[[comments]]
author = "Ahmed Yousof"
date = "2008-05-07T11:14:00+00:00"
text = "اسف يا مصعب و لكن مصرنا أسيرة لا نستطيع أن نؤدى واجبنا نحوها و لا نتمتع بعطائها لنا و لا حتى رسالتك لن تصل إليها إلا إذا تحررت بأيدينا _ ليس فقط بأيدينا _ بل اظنها تحتاج الى دمائنا .<br />هكذا تتحرر مصرنا.<br />هى ليست بأيد أمينة بل بأيد قذرة ملوثة عابثة.<br />حتى متى نراك اسيرة ؟<br />حتى متى نراك اسيرة ؟<br />حتى متى نراك اسيرة ؟"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgse-XUeZ1PsN37YuARbDhRN6sXvv61G2xjXBSj0sFJbz-ZgaAMOvcPiNiZBcWzbLC2TJKKVcp-NaaWaN4QagTZREtfBvIZR66PwFvXU6uSQ-PMzKO7FO-bbLcj0sq2xQ/s220/AboYousof.jpg"
profile_url = "https://www.blogger.com/profile/03325476180863657403"
comment_url = "https://mos3abof.blogspot.com/2007/07/blog-post.html?showComment=1210158840000#c4938043928330984856"
