pygmentsUseClasses = true

baseURL = "https://mosab.co.uk/"
# baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Mosab | مُصْعَب"
#theme = "rfc"
theme = "hugo-bearblog"

copyright = "(c) 2022 Mosab Ibrahim"

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
blog = "/:slug/"
tags = "/blog/:slug"

[menu]
[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 5
[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 10
[[menu.main]]
name = "Resources"
url = "/resources/"
weight = 15
[[menu.main]]
name = "Resume"
url = "/resume/"
weight = 20
[[menu.main]]
name = "Cycling"
url = "/cycling/"
weight = 25
[[menu.main]]
name = "Woodworking"
url = "/woodworking/"
weight = 30
[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 35

[params]
name = "Mosab Ibrahim"
description = "Random blobs from an Egyptian Software/Systems Engineer living in the UK"
images = ["mosab-london-bridge.jpg"]
title = "Mosab Ibrahim"

#[markup]
#  [markup.highlight]
#    anchorLineNos = false
#    codeFences = true
#    guessSyntax = false
#    hl_Lines = ""
#    lineAnchors = ""
#    lineNoStart = 1
#    lineNos = false
#    lineNumbersInTable = true
#    noClasses = true
#    style = "monokai"
#    tabWidth = 4
