[[comments]]
author = "elkamhawi"
date = "2007-10-13T05:21:00+00:00"
text = "كل سنة وانتا طيب يا باشا<br />realy you beatiful mos3b"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/09923750534350910131"
comment_url = "https://mos3abof.blogspot.com/2007/10/beatiful-mine.html?showComment=1192252860000#c633836358833163609"

[[comments]]
author = "weswes"
date = "2007-10-13T10:30:00+00:00"
text = "كل سنه وانت طيب يا مصعب<br />ويا رب تلاقى اللى تعرف تفهمك<br />لك تحياتى"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiw4snw0O4r8EYHQhiu7PCP3YXbjsOVmNj5zsVG2NmG_iJW8qfvdrvDKQVVXpYEQyxkgnLEal7LDhjHT9wSDmHEaztJc2mql6BgND38sUt9YXFFoG0Id5pU9R8WI3ItEKo/s220/IMG_0034.JPG"
profile_url = "https://www.blogger.com/profile/04810150175952124524"
comment_url = "https://mos3abof.blogspot.com/2007/10/beatiful-mine.html?showComment=1192271400000#c6589806361837602409"

[[comments]]
author = "Omar"
date = "2007-10-14T18:40:00+00:00"
text = "ايع الرومانسيه والكلام الجامد ده  ومعيشنه في مود جامد والواحد بيقرا التدوينه وهوه جنبه شمعتين وكبيتين لمون وشجره وفي الاخر تال ادبك كده وانت لسه متعرفتش عليها اصلا ده الواحد وهوه ماشي لما بيلاقي كلب جعان وهوه لسه اول مره يكلموا بيطلع يجري تقوم انت تسب \"a beautiful mind”يا اخي ده ىرمضان لسه خلصان امال لو انت مش بترومانسس  وبتقول كده وبتشجينا تقوم تقول الكلام ده ده حتى مكنش في حد بيلعب الهرم تامر ولا احنا قاعدين مع عمر <br /> اتعلموها بءه تقول  <br />يا رب تلاقي الربنا يكون في عونها"
avatar_url = "http://1.bp.blogspot.com/_uU6aLT1vZs0/Sha7cwlVWFI/AAAAAAAAAUI/2a29l9P2ke4/S220/Family+(1).jpg"
profile_url = "https://www.blogger.com/profile/10164006741123254135"
comment_url = "https://mos3abof.blogspot.com/2007/10/beatiful-mine.html?showComment=1192387200000#c5103217537239612606"

[[comments]]
author = "Amira Qassim"
date = "2007-10-14T21:44:00+00:00"
text = "يا مصعب يا جامد ..<br />بتثبتها من دلوقتي <br />انت بس أول ما تلاقيها ..ابقي وريها التدوينة دي ..وهي هتطفش علي طول <br />هينت صغير:أكيد هي كمان مشتاقة لك أوي <br /><br />ان شاء الله ربنا هيكرمك بيها"
avatar_url = "http://img107.imageshack.us/img107/712/ice36pd7.jpg"
profile_url = "https://www.blogger.com/profile/08351482421774299913"
comment_url = "https://mos3abof.blogspot.com/2007/10/beatiful-mine.html?showComment=1192398240000#c1854079836519031913"

[[comments]]
author = "Amira Qassim"
date = "2007-10-14T21:47:00+00:00"
text = "وبعدين تعالي هنا ..انت عاتبتني أني نزلت بوست من غير ما ابعت لك اللينك <br />!!!!وانت يا مفتتتتتتتتتتتري نزلت 3<br /> <br />الحساب بيجمع يا عم مصعب"
avatar_url = "http://img107.imageshack.us/img107/712/ice36pd7.jpg"
profile_url = "https://www.blogger.com/profile/08351482421774299913"
comment_url = "https://mos3abof.blogspot.com/2007/10/beatiful-mine.html?showComment=1192398420000#c653477412687934179"

[[comments]]
author = "mohamed"
date = "2007-10-15T13:29:00+00:00"
text = "ان شاء الله هتتقبلوا قريب <br /><br />وتتحملك زي ما انت هتتحملها وتقف جمبها <br /><br />:)"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiGfWhZiigMyqtTXuNGhGuZ7kCzQpSXHHBQFxacGHOFHEX81agRvyAHVvJNqxlHc4r65JdjhzBKu76zKEj0TXhBVJ-Rjmpfciyt9XBGHfdbSKJJfq-Rc3UeAgPD5FN-SK0/s220/DSCF29155.jpg"
profile_url = "https://www.blogger.com/profile/11099621052476900765"
comment_url = "https://mos3abof.blogspot.com/2007/10/beatiful-mine.html?showComment=1192454940000#c718205497800685021"

[[comments]]
author = "Salma Amer"
date = "2007-10-16T12:44:00+00:00"
text = "ربنا يرزقك بانسانة تستهلك بجد يا مصعب ان شاء الله بس لما تلاقيها حاول ماطلعش عنيها قوي يعني احسن الناس الكويسين بقوا قليلين جدا"
avatar_url = "http://farm2.static.flickr.com/1132/1365681113_f20faceeb5.jpg?v=0"
profile_url = "https://www.blogger.com/profile/08716194696950096714"
comment_url = "https://mos3abof.blogspot.com/2007/10/beatiful-mine.html?showComment=1192538640000#c7235651297461049539"

[[comments]]
author = "azmeralda"
date = "2007-10-25T06:28:00+00:00"
text = "لما قريت اليوست ده افتكرت بوست كنت كتباه من مده كده كان تقريبا عن نفس الموضوع اقراه كده وقولي رايك <br /><br />http://kawkab-tani.blogspot.com/2007/03/blog-post.html<br />وربنا يوفقك وتلاقيها يااااااااااااارب وابقي ادعيلنا نلاقي اي حاجة احنا كمان يا باشمهندس"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/02733730322616163797"
comment_url = "https://mos3abof.blogspot.com/2007/10/beatiful-mine.html?showComment=1193293680000#c5603691464826077709"
