[[comments]]
author = "قضية عم أحمد    Ahmed Case"
date = "2008-01-08T12:50:00+00:00"
text = "ياااااااااااااه يا مصعب هي المشكلة في المكروباص بيقف فين المشكلة الاكبر في صمت الناس عن غلاء الاسعار وصمتهم عن تبديد 50 مليار جنيه سنويا .. <br /><br />المشكلة يا مصعب بقيت اكبر من مكان وقوف المكروباص .. <br /><br />المهم انا عايز اركب المترو اتفرج انا كمان ...."
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgV-wcarXLkgWhQQil5kwuYh3wp9AEWNEDcLSaQD2LN0vM_G4H9YJFgqa0XczHwll6yiqoYqdHkRIaOBrs7mUlUTV8btyQ-yKEFvsGrNIWlN99lkjHG8LD-zKscO0MMuVA/s220/DSC_7364.JPG"
profile_url = "https://www.blogger.com/profile/07000569434293484731"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_08.html?showComment=1199796600000#c3193727264981277589"

[[comments]]
author = "محمد السيد..مش حاسكت"
date = "2008-01-08T12:50:00.001000+00:00"
text = "إيه الكلام الكبير ده بس يا كبييييييييير ؟<br /><br />أهه أنا النهاردة لسة حاصل لي موقف زي بتاع الميكروباص ده بعدما البيه السواق وقف علي أول الشارع وطلب اجرة تانية لدخول الشارع لآخره للموقف ......<br /><br />وصباح الاستبعاط بقي ..<br />طبعا بعد شد وجذب . قمت نزلت ومرضتش أدفع لكن الغريييييييب ... <br /><br />إن الناس كلها عملت زيي كده ؟؟؟<br />تخيل ؟؟<br />أنا شكيت في نفسي حقيقي ..<br /><br />بس أهه أقول هم لأ يعني؟؟؟"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/15123433931771567833"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_08.html?showComment=1199796600001#c1699699956868870440"

[[comments]]
author = "Salma Amer"
date = "2008-01-08T12:52:00+00:00"
text = "برافو عليك انك رديت على الراجل لان كل واحد بيعمل نفسة قاضي على الفاضي<br />بالنسبة للقرار الحكيم بتاع مترو انا دلوقتي فهمت سببه<br />اكيد لانهم حسوا بمعانات الراجلة واملهم في انهم يشوفوا السواق فقرروا يسعدوا قلبهم  ويحققوا هذه الامنية مع بداية 2008<br />مرسي يا مصعايبو فهمتني السبب"
avatar_url = "http://farm2.static.flickr.com/1132/1365681113_f20faceeb5.jpg?v=0"
profile_url = "https://www.blogger.com/profile/08716194696950096714"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_08.html?showComment=1199796720000#c6555927742902306631"

[[comments]]
author = "Lens Geek"
date = "2008-01-08T14:15:00+00:00"
text = "مبروك يا مصعب و على كل رجالة المترو الشرفاء<br />كنا رجالة ووقفنا وقفة رجالة متشعلقين في حلقتين"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhDH6cac8DhCu85r5fVw0KJDQyTSgnbUN_on5yZRrtKG44soaS5wrAZnDMZBnmYItm4PSgM5Be26Q5kswvv4w84fGE-zjxA4uFGBZW67q5kjJzKnPEAcvpMpdz-KsYUpg/s220/Ahmed2.gif"
profile_url = "https://www.blogger.com/profile/08391635125789451063"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_08.html?showComment=1199801700000#c7967840792916957024"

[[comments]]
author = "ام مليكة"
date = "2008-01-08T14:49:00+00:00"
text = "عندك حق يا مصعب والله بس الافظع من عربيات الجيزة هي عريبات الهرم اللي مقطعين الشارع 5 محطات وهو في الاصل محطة واحدة يعني افترا<br /><br />اما بقى موضوع عربية الستات ده فانا ضده تماما وبصراحة عمري ما بادور عليها عشان اركبها باركب اول عربية تيجي قصادي وانا نازلة واهنئك على رؤيتك كابينة السائق من جديد"
avatar_url = "http://admins.20at.com/do3a2/bentbalad.jpg"
profile_url = "https://www.blogger.com/profile/17720828413632673574"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_08.html?showComment=1199803740000#c1602940178129724580"

[[comments]]
author = "Camellia Hussein"
date = "2008-01-11T00:06:00+00:00"
text = "فكرتني بحادث قديم..كنا في رمضان تقريبا قبل الفطار بربع ساعة والميكروباص اليتيم اللي لقيناه بعد طول انتظار سواقه قرر -كصائم محترم-ان الاجرة 75 بدل نص جنيه،الناس كلها اعطوا الاجرة عن يدٍ وهم صاغرون،الا واحد ثار -كمواطن شريف صائم برضه-وقال يا اخواننا لو كلنا اتحدنا وقلنا لا هيضطر السواق انه يرضخ لمطالبنا المشروعة....وطبعا طبعا طبعا الشعب كله قصدي الركاب كلهم اتحدوا فعلا ،لكن اتحدوا في انهم يقولوا لاخوهم الراكب الشريف كلمة واحدة(انزل)وكل ميكروباص وانت طيب"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg6KZuDgMk9CMt_vMft5N5xJJ0k5I3QTlPdcU-TQPDTAqe5E0uZpMiiL0V6jMKlMsbmPuUaXlDuyN0331exGVVvOkUtkGfdGgwbvWbDcfylIeb8mzTpbcywmnIF-RRV8Vc/s220/reflections.jpg"
profile_url = "https://www.blogger.com/profile/15735434869492317332"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_08.html?showComment=1200009960000#c7536259150109953612"

[[comments]]
author = "Yassor"
date = "2008-01-11T12:48:00+00:00"
text = "يا سلام عليك يا مصعب الخبر بتاع عربية الستات ده تستاهل عليه تعليق عشان انا عمري ما شفت كابينة السواق وكل مرة كنت بأصاب بذبحة صدرية من الحقد..<br />يالا الحمد لله أما بخصوص الميكروباصات يا جماعة أنا قولتلكم من زمان نولع فيهم ومحدش سمع كلامي اشربوا بقي أصلنا شعب كيرع(لما ابقي أقابلك إن شاء الله هابقي أفهمك يعني ايه كيرع دي)."
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/17950613708626082139"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_08.html?showComment=1200055680000#c1392145268778796953"

[[comments]]
author = "Anonymous"
date = "2008-01-11T17:06:00+00:00"
text = "أسلوبك لذيذ يا عم مصعب<br />حسستني إني معاك في رحلتك<br /><br />و ألف مبروك على إنك شفت كابينة السواق تاني - عقبال كده ما تسوق المترو بنفسك و تعمل بقى اللي انت عايزة"
comment_url = "https://mos3abof.blogspot.com/2008/01/blog-post_08.html?showComment=1200071160000#c7207725051109632995"
