[[comments]]
author = "Amira Hassan"
date = "2007-01-03T03:16:00+00:00"
text = "يا حلاوة يا حلاوة <br />مصعب نزل اسمه في الدورنال يا رداله<br /><br />لولولوللي"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjKwkbS92ad0pzdLQkHLcToR78dqrG___FfPXTF7qAL6Eml7VawwAzFxt-bHWDIWOwjxbeWWob3GpF-cygVRx34PDduMFcrff3Zh1VxP_o5DrDK-5RHQ3UVoWbveXLLzg/s220/DSC04172.JPG"
profile_url = "https://www.blogger.com/profile/08135823930111514700"
comment_url = "https://mos3abof.blogspot.com/2007/01/blog-post_03.html?showComment=1167794160000#c6031806027604304703"

[[comments]]
author = "Anonymous"
date = "2007-01-03T03:34:00+00:00"
text = "نعزيك طبعا<br />انت اكيد \"اهيف\" من كده بكتييير :)<br />بصراحه بيفكرني ببيت شعر لإيليا ابو ماضي بيقول:<br />وترى الشوك في الورود وتعمى ..أن ترى فوقهاالندى إكليلا<br /><br />على العموم لسنا من نفخر بالأهرام ولكن الأهرام من يفخر بنا"
comment_url = "https://mos3abof.blogspot.com/2007/01/blog-post_03.html?showComment=1167795240000#c1186584015324354741"

[[comments]]
author = "abderrahman"
date = "2007-01-03T05:40:00+00:00"
text = "سؤال يا مصعب<br />إنت فوجئت بالتقرير النهارده ولا كان فيه حوار معاك<br />؟؟<br /><br />عموما مبروك يا سيدي<br />المرة الجاية قلهم ينشروا صور المدونين كمان<br />:)"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/08795800558717098361"
comment_url = "https://mos3abof.blogspot.com/2007/01/blog-post_03.html?showComment=1167802800000#c4495442806804377992"

[[comments]]
author = "sherif"
date = "2007-01-03T10:02:00+00:00"
text = "مبروك يا اسطي"
avatar_url = "http://photos1.blogger.com/blogger/2776/3195/400/Image%28926%29.jpg"
profile_url = "https://www.blogger.com/profile/15629143312998547267"
comment_url = "https://mos3abof.blogspot.com/2007/01/blog-post_03.html?showComment=1167818520000#c3857439296317517177"

[[comments]]
author = "محمد السيد..مش حاسكت"
date = "2007-01-03T12:35:00+00:00"
text = "عايز منه ... عايز منه ....<br /><br />معلم يا ابني .... معلم ...<br /><br />مبروك يا سيدي .. وعقبال أنجالك ...."
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/15123433931771567833"
comment_url = "https://mos3abof.blogspot.com/2007/01/blog-post_03.html?showComment=1167827700000#c1713587430277470210"

[[comments]]
author = "shabfa2re"
date = "2007-01-03T13:16:00+00:00"
text = "<b> مبروك يا ابو المصاعيب<br /></b>"
avatar_url = "http://img54.imageshack.us/img54/4756/1606160816011604yy2.jpg"
profile_url = "https://www.blogger.com/profile/13162086599879303972"
comment_url = "https://mos3abof.blogspot.com/2007/01/blog-post_03.html?showComment=1167830160000#c892250544712136587"

[[comments]]
author = "كراكيب نـهـى مـحمود"
date = "2007-01-03T19:46:00+00:00"
text = "بيقولوا الاهرام في المدونات نصرة"
avatar_url = "http://www.geocities.com/ninthnona/nona.jpg"
profile_url = "https://www.blogger.com/profile/15392866437391821080"
comment_url = "https://mos3abof.blogspot.com/2007/01/blog-post_03.html?showComment=1167853560000#c9154298620642183441"

[[comments]]
author = "Mony The Angel"
date = "2007-01-03T20:58:00+00:00"
text = ":)<br />msh 3arfa almafrood sa7 nbarek walla ne3mel eh..<br />bas e7tyaaty <br />Mabrooooooooooooooooooooooooooooook<br />(kda enta afelt algarayed, 7koomy we mo3arda ;))"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjj4h6hlbKyUklJB5J_QeHmZidZ8mEHO-s5lWgxcP3qUEQSPg4AS0GkKHyrjWHC4Z5y2O3vBW2OY7WPf-cZ0PSVMC-DcEJ6cu6SRYKhpVq1jh6S9ve07RM4o8WgdU_8rxE/s220/mine...jpg"
profile_url = "https://www.blogger.com/profile/02273268851121458996"
comment_url = "https://mos3abof.blogspot.com/2007/01/blog-post_03.html?showComment=1167857880000#c4139577314604528742"

[[comments]]
author = "Anonymous"
date = "2007-01-03T21:47:00+00:00"
text = "مصعبكم للتدوين الاسلامي..<br /><br /> شعارنا<br /><br />انشأ مدونتك..انفع أمتك..ادخل الجنة..وتقدم في ترتيب اليكسا"
comment_url = "https://mos3abof.blogspot.com/2007/01/blog-post_03.html?showComment=1167860820000#c4989069803249601364"

[[comments]]
author = "We2am"
date = "2007-01-03T22:01:00+00:00"
text = "طب والله اشطة جدا..مبروك يا عم..دي اجل حاجة عندينا :D<br />بما ان اميرة زغرطت فنا جاية ارقص! :D"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhQcQ1ZEVto0d3Q-8SYrlhPe65gtdb7vieD2O9VTjley8Ol9gRSSIxfYCsbogR3Vwo_4gVGfgbPaXcMMYxpPYMmGgitzKr2RN8hp4O1ZV_ezx9D2Wqd3AhCUjMKrXUByu0/s113/14803259_10154014513627023_722172126_o.jpg"
profile_url = "https://www.blogger.com/profile/11798083370261251218"
comment_url = "https://mos3abof.blogspot.com/2007/01/blog-post_03.html?showComment=1167861660000#c7631709660545764035"

[[comments]]
author = "dandana"
date = "2007-01-04T00:01:00+00:00"
text = "ماااااا علينا"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjKF0u0iITfv8fS9C08maQkVzFmDKdHy7ixk8ae8p6c9rw_et67HwBOZCIisfxOSs62z9gP931dzo5uvigMzctXr0PuecZBrBUa7Gcm-lDvzsfLpN1SDkBdcrZJSEzolVw/s220/Felicity-tv-show-031.jpg"
profile_url = "https://www.blogger.com/profile/18250869441398432677"
comment_url = "https://mos3abof.blogspot.com/2007/01/blog-post_03.html?showComment=1167868860000#c8389225422198920427"

[[comments]]
author = "Anonymous"
date = "2007-01-07T23:41:00+00:00"
text = "ما شاء الله لا قوة إلا بالله <br />أحسن حاجة إن المدونات المحترمة تبقى هى المثل او النموذج ومش أى مدونات تااااانية <br />ألف مبروك <br />وتحياتى لمدونتك الجميلة والمحترمة"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/18109115295535905745"
comment_url = "https://mos3abof.blogspot.com/2007/01/blog-post_03.html?showComment=1168213260000#c6030995419815657680"

[[comments]]
author = "Haitham Abu Akrab"
date = "2007-01-25T15:20:00+00:00"
text = "الله بقي الخبطه دي ليه<br /> هيا  نزت ف الدورنال <br /> ولا ع النت<br />اعذر فهمي اصلي صعيدي<br /><br />بس بيني وبينك عجاباني الصوره جدا <br /> لانها متاخده من علي <br />الماكنتوش<br />حبيبي<br /><br />مبروك يا ددع"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/04974115727167951432"
comment_url = "https://mos3abof.blogspot.com/2007/01/blog-post_03.html?showComment=1169738400000#c3587955161120096251"

[[comments]]
author = "AbdElRaHmaN Ayyash"
date = "2007-01-25T20:00:00+00:00"
text = "لا طبعا نباركلك يا سيدي :D <br />بس اوعى تتكرر ;) <br />ألف مبروك يا صعب<br />سلامو"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/01249867116407271986"
comment_url = "https://mos3abof.blogspot.com/2007/01/blog-post_03.html?showComment=1169755200000#c163600846838612991"
