[[comments]]
author = "ياء"
date = "2007-04-02T00:46:00+00:00"
text = "ربنا يخلهملك<br /><br />ويطرحلك فيهم البركه<br /><br />عقبال ما تخاويهم<br /><br /><br />حلوه اوى فكره ان الواحد يكون عنده حاجات يتعلق بيها ويحبها <br /><br />ذى المج بتاعك اللى اتكلمت عليه مره<br /><br />عارف انا عندى عصفوره بلاستيك صغير ه <br />ناوى اخدها معايا الجيش<br /><br />العصفوره اللعبه دى عندى يقالها اكتر من 10 سنين تخيل"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/09927085065103433253"
comment_url = "https://mos3abof.blogspot.com/2007/04/artie.html?showComment=1175474760000#c8827488117744798461"

[[comments]]
author = "LAMIA MAHMOUD"
date = "2007-04-02T00:47:00+00:00"
text = "اللي جابلك يخليلك:)"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj9Eh5lF-XRHtud8suhl5K4yhMxWsSKxr7oyl2dnkn5hzt8OEtado-gJjkufoVPTgqAHHfWXLwNj3X6sZUl4NWiUVH9XjUZWWmADmu-GQHwrYWvQyo2KAfaSJmBtk1jSw/s220/lets-dance-2.jpg"
profile_url = "https://www.blogger.com/profile/05758996758350593398"
comment_url = "https://mos3abof.blogspot.com/2007/04/artie.html?showComment=1175474820000#c4387239740239781959"

[[comments]]
author = "Oma"
date = "2007-04-02T01:03:00+00:00"
text = "لذيذ آرتي اوي<br />ولايق على لاب توب<br />كنبوره تديك احساس بنضاره كعب كبايه او حاجه تقيله:D<br />مع انك بتقول انها خفيفه وبتريحك<br />نضارتك وانت حر فيها <br />كنبوره<br />ممكن تدلعها تقولها كوكي<br />:))<br />خلي بالك منهم بقى"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgkyjSYWqXw4YBOpvP-96TyE2UNOj8WOswTKULdPzB70B6zrqDGJHhff9VHgxIxelyXO3EKU7YW8ajjqkmMwG9IO7yT-08dfl5BYELB9hvKRZscAn2UfctX1Oxivr_uIw/s220/dancing.jpg"
profile_url = "https://www.blogger.com/profile/00803900258553286221"
comment_url = "https://mos3abof.blogspot.com/2007/04/artie.html?showComment=1175475780000#c3496621503101139030"

[[comments]]
author = "AbdElRaHmaN Ayyash"
date = "2007-04-02T01:05:00+00:00"
text = ":d و الله لو كل واحد هيسمي لاب توبه .. هنلاقي في اختلاط انساب لابتوبات وحاجات من دي<br />انا نصيحتي تسميه ارتي سوني<br />او ارتي توشيبا<br />على الاقل ميبقاش ارتي مصعب<br />:D وزي ما لمياء بتقوللك<br />اللي جابلك يخلليلك<br />:]"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/01249867116407271986"
comment_url = "https://mos3abof.blogspot.com/2007/04/artie.html?showComment=1175475900000#c8574186928990715305"

[[comments]]
author = "Dananeer"
date = "2007-04-02T06:09:00+00:00"
text = "كنبوره جامده جدا<br /><br />و ارتى حلو<br /><br />ربنا يخليهملك يا مصاعيبو"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhDHGvgY5KpZ8XEsPyzaaDpmG53SKgaqkXxb8lI5SrPxQajlLmAm6PnP9A8howzgOVmDKonJLsRa4LRH3mPV9LiGH0oloUzdu0hFwoqEumr2ko-f1X_ntVu5FpwKKpEWtE/s1600/2141.jpg"
profile_url = "https://www.blogger.com/profile/08617762348908989998"
comment_url = "https://mos3abof.blogspot.com/2007/04/artie.html?showComment=1175494140000#c3206180569285885476"

[[comments]]
author = "Anonymous"
date = "2007-04-02T08:57:00+00:00"
text = "خلاص .. إحنا نعرف كمبيوتر الديسكتوب بتاعى (أينشتاين) على أرتى .. وأهى برضه تبقى صداقة نكسب فيهم ثواب<br />:)<br />وسلملى على أرتى وكنبورة<br />وربنا يطمنا عليك دايما يارب<br />:)"
comment_url = "https://mos3abof.blogspot.com/2007/04/artie.html?showComment=1175504220000#c4544448183900389208"

[[comments]]
author = "marwa salah"
date = "2007-04-02T09:59:00+00:00"
text = "الف الف مبروك يا مصعب انك وصلت لاسم ليهم لانها اصعب حاجة فعلا ان الواحد يلاقى اسم لحاجة هو متعلق بيها، وتعزمنا على السبوع قريب (سبوع التسمية)."
avatar_url = "http://photos1.blogger.com/blogger/6631/3271/1600/water.1.jpg"
profile_url = "https://www.blogger.com/profile/01915363504191088852"
comment_url = "https://mos3abof.blogspot.com/2007/04/artie.html?showComment=1175507940000#c5007692856355057010"

[[comments]]
author = "Anonymous"
date = "2007-04-02T10:26:00+00:00"
text = "يتربوا في عزك يارب :))))"
comment_url = "https://mos3abof.blogspot.com/2007/04/artie.html?showComment=1175509560000#c4227672796673810690"

[[comments]]
author = "mohamed elbanna"
date = "2007-04-02T11:46:00+00:00"
text = "مصعب ياخويا<br />قولى الحقيقة<br />الموضوع ده ليه علاقة بجواز اخوك براء<br />واحساسك بالوحدة من بعده<br />قول الحقيقة"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/05793287566129189152"
comment_url = "https://mos3abof.blogspot.com/2007/04/artie.html?showComment=1175514360000#c4730979614438725635"

[[comments]]
author = "Anonymous"
date = "2007-04-02T12:02:00+00:00"
text = "ربنا يخليهملك<br /><br />اللاب توب بتاعي مسميه شحيبر و النضارة سوسن <br /><br />بس هو شحيبر بعافية شوية لما كنت من ساعة ما كنت بانقل للينوكس ربنا يسامحه<br /><br /><br />تحياتي"
comment_url = "https://mos3abof.blogspot.com/2007/04/artie.html?showComment=1175515320000#c4177785067180480386"

[[comments]]
author = "Anonymous"
date = "2007-04-02T12:39:00+00:00"
text = "حـــــــاضريا يافندم، يا حضرة \"الـبروكرامور\" ، أنا من هنا و رايح، حبقى نا ديلك: ''  يا بتاع الآرتي ، و الكنبورة''، لكن مممم...المشكلة، إنت شاب لطيف.... و رقيق..... و لذيذ.......و....مش كات معك التسمية دي، و لا أقولك خليها : ''يا فندم مصعب'' أحسن......ربنا يكرمك و يحفظك في أولادك الصغار يارب ،.....يتربوا في عزك يا رب...."
comment_url = "https://mos3abof.blogspot.com/2007/04/artie.html?showComment=1175517540000#c819821743306461666"

[[comments]]
author = "دوللي"
date = "2007-04-02T12:47:00+00:00"
text = "فكرة جامدة اوي يا مصعب وعلى فكرة انا كمان عندي حاجات بحبها اوي واكترهم عربيتي والله بحس انها فهماني وعرفة انا عايزة اعمل ايه وبحسها انها معايا على الخط وكمان ليها اسم جامد اوي انا سمتها fantas بالعربي فانتس <br />وعموما ساعات الواحد بيحس انو محتاج حد يفهمو غير البشر"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/06515904854255564384"
comment_url = "https://mos3abof.blogspot.com/2007/04/artie.html?showComment=1175518020000#c3779147909767170553"

[[comments]]
author = "Amira Hassan"
date = "2007-04-02T13:44:00+00:00"
text = "اشاعير ومحاسس<br />ههههههههههههههههههه<br /><br />دي زي الاكلات الحلوة بتعدي في صواني<br /><br />يا رب يا رب ارتي و كنبورة يتربوا في عزك يا معلم"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjKwkbS92ad0pzdLQkHLcToR78dqrG___FfPXTF7qAL6Eml7VawwAzFxt-bHWDIWOwjxbeWWob3GpF-cygVRx34PDduMFcrff3Zh1VxP_o5DrDK-5RHQ3UVoWbveXLLzg/s220/DSC04172.JPG"
profile_url = "https://www.blogger.com/profile/08135823930111514700"
comment_url = "https://mos3abof.blogspot.com/2007/04/artie.html?showComment=1175521440000#c4745741288733962980"

[[comments]]
author = "قضية عم أحمد    Ahmed Case"
date = "2007-04-02T13:57:00+00:00"
text = "بتحب عليا يا مصعب لاب توب ونظارة وبتدلعهم يا خاين <br />اخص على الصداقة اخص على الصحوبية <br />دلع حاجاتك براحتك المهم تيجي تأخد حاجتك اللى في شنطة عربيتي ومش عايز اعلى صوتي واقول انت سايب ايه فاهم يا بتاع اللاب توب ونظارة ال <br /><br />عجبي <br />الشقشوق احمد رفعت"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgV-wcarXLkgWhQQil5kwuYh3wp9AEWNEDcLSaQD2LN0vM_G4H9YJFgqa0XczHwll6yiqoYqdHkRIaOBrs7mUlUTV8btyQ-yKEFvsGrNIWlN99lkjHG8LD-zKscO0MMuVA/s220/DSC_7364.JPG"
profile_url = "https://www.blogger.com/profile/07000569434293484731"
comment_url = "https://mos3abof.blogspot.com/2007/04/artie.html?showComment=1175522220000#c2796627448101105251"

[[comments]]
author = "قضية عم أحمد    Ahmed Case"
date = "2007-04-02T14:03:00+00:00"
text = "باقولك ياد يا بتاع الاب توب <br />ملكش دعوة بسكسكه تاني انت فاهم (سكسكه ديه الكاميرا بتاعتي)وجعبل زعلان منك (جعبل ده الموبيل بتاعي الايميت) <br /><br />يا بتاع اللاب توب والنظارة ."
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgV-wcarXLkgWhQQil5kwuYh3wp9AEWNEDcLSaQD2LN0vM_G4H9YJFgqa0XczHwll6yiqoYqdHkRIaOBrs7mUlUTV8btyQ-yKEFvsGrNIWlN99lkjHG8LD-zKscO0MMuVA/s220/DSC_7364.JPG"
profile_url = "https://www.blogger.com/profile/07000569434293484731"
comment_url = "https://mos3abof.blogspot.com/2007/04/artie.html?showComment=1175522580000#c2721131962425029176"

[[comments]]
author = "ola salem"
date = "2007-04-02T16:09:00+00:00"
text = "هههههههههههههههههههههه<br />وربنا انت بتهرج <br />حلو كنبورة دى<br />ليا واحدة صحبتى ايطالية اسمها كنبورة بس التانية شحم ولحم وصنع فى روما<br />ههههههههههه<br />وربنا نت بتهرج<br />يا ابو ارتى انت<br />اللى جابلك يخليلك<br />انا هروح اسمى الاب توب انا كمان اشمعنى انت يعنى؟<br />هسميه عويييييييس"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjHFDt3TCMySOaOIfSKy1pm6Fftth7KbZ_FXRBySjWFuS7GVEefAkoeQ4UT7wLJKsNj-DSKxiKoIDNRQxC5kWxU39tZKuKXxikTJMw7maf5gEdDgr9yq5SBrSAtNlvcZw/s220/ola.jpg"
profile_url = "https://www.blogger.com/profile/16188352166168735049"
comment_url = "https://mos3abof.blogspot.com/2007/04/artie.html?showComment=1175530140000#c6011929285569940248"

[[comments]]
author = "emz"
date = "2007-04-02T18:45:00+00:00"
text = "اشاعير و محاسس<br />هههههههههههههههههههههههههه<br />ربنا يخليكوا لبعض انت و ارتى كنبورة"
avatar_url = "http://www2.0zz0.com/2007/11/09/21/19408873.jpg"
profile_url = "https://www.blogger.com/profile/06702188321496445002"
comment_url = "https://mos3abof.blogspot.com/2007/04/artie.html?showComment=1175539500000#c4870742084160645249"

[[comments]]
author = "shimaa"
date = "2007-04-02T18:51:00+00:00"
text = "اشاعير و محاسس:D<br /><br />انا بقى عايزة اجيب واحدة زي كنبورة كده و برضة متضايقنيش ..و لو طلعت كويسة و بنت حلال ها اسميها اسم اكيد..<br />وربنا يخلي لك كنبورة و ارتي ..بالمناسبة ارتي اسم حلو قوي"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj0Q5LXS1guXTqQoB0zCHEZOdUy6VL3nZOF09JFgFjB2ZKI7SRVGnsEpow8i6WeBwPNL3VCRwjsY6jLM3vTnN_MxCnD6L9Mx9G_Jib_8zjjXWZsvvskr0XyKAIKOdV0xw/s220/hyori-lee[1].jpg"
profile_url = "https://www.blogger.com/profile/10764917878271047406"
comment_url = "https://mos3abof.blogspot.com/2007/04/artie.html?showComment=1175539860000#c7131902942366252066"

[[comments]]
author = "دينا فهمي"
date = "2007-04-02T18:53:00+00:00"
text = "واضح ان الدماغ عالية الحقيقة (:<br />ربنا يديم عليك كل حاجة حلوة"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/07685435794478937439"
comment_url = "https://mos3abof.blogspot.com/2007/04/artie.html?showComment=1175539980000#c2667477455756960599"

[[comments]]
author = "أميرة من غير قصر ولا بستان.. ولا الشاطر حسن كمان"
date = "2007-04-02T19:16:00+00:00"
text = "ههههههههههههههههههههههههههه<br />ربنا يطرحلك فيهم البركه <br />و بعدين هو الانسان ايه غير نضاره و لاب توب <br />انا حققت الاولى<br />ياااااااااااارب احقق التانيه بقى"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEirdirzKebc0hcGC4MQ6kvVkx2q0MdxprJrl-jqSZ5l_jxE2bWsZVd-Pla_Zla1V4g0FjN5PUa4k3oTN0AO0cgFlRcbwr6XbP-7sqohbU_KGsAtNaDenb4eAJmqzrb0EGE/s220/blogpic5ke.jpg"
profile_url = "https://www.blogger.com/profile/16391848599214933906"
comment_url = "https://mos3abof.blogspot.com/2007/04/artie.html?showComment=1175541360000#c1813691651435954021"

[[comments]]
author = "Anonymous"
date = "2007-04-02T20:24:00+00:00"
text = "ليه بالذات ال2 دول؟<br />نظارتك ولابتوبك<br />لاشعوريا عايزك تركز في ال2 وتجاوبني<br />:<br />:<br />:<br />علي فكرة عاملين زي اسماء الاشرار في افلام الكارتون"
comment_url = "https://mos3abof.blogspot.com/2007/04/artie.html?showComment=1175545440000#c2342202203169069756"

[[comments]]
author = "Ahmed taher"
date = "2007-04-05T08:53:00+00:00"
text = "ازيك يا عم مصعب مبروك عليك يا سيدي الشيخ ارتي والحاجة كمبورة شكلي هحصلك قريب واجبلي انا كمان حته كمبورة...<br />سلام يا عم الصعب<br />اخوك في الدكة اللي وراك في ال pmo<br />خمن بقا"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjbFhgaioW1FLydp_YjgIbIdT_PfEfb-FJ6Wea1dfWhm5sDil4QGxRwRq6e2dga4L1XvCz2TCil8src4IaBcNPYJy02xDIon98UPnfluT_iQwYmS7rGW_pA3bp1KSqvAg/s1600/gse_multipart60378.jpg"
profile_url = "https://www.blogger.com/profile/13243848176786616475"
comment_url = "https://mos3abof.blogspot.com/2007/04/artie.html?showComment=1175763180000#c6193389828308050317"

[[comments]]
author = "Иεşċąfě &иεmö"
date = "2007-04-06T17:50:00+00:00"
text = "ربنا يخليهم لك<br /><br />ويطرحلك فيهم البركه<br />و اشوفك كدة يا مصعيبو انت و كنبورة و أرتي في احسن حال ديما يا رب و ميحرمكشي منهم ابدا ابدا انا بردوا مستر مانكي صديقي العزيز و مئدرشي استغني عنه ابدا ابد"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/14635860789423949153"
comment_url = "https://mos3abof.blogspot.com/2007/04/artie.html?showComment=1175881800000#c7132330963009176906"

[[comments]]
author = "دعاء عادل"
date = "2007-04-07T21:46:00+00:00"
text = "احنا بنرحب معاك بعائلتك الصغيره<br />بجد اسم ارتى عاجبنى اوى <br />وكمبورة اسم لذيذ<br />ربنا يخليهم ليك ويخليك ليهم<br />بس دايما افتكر يا مصاعيبو ان <br />الراجل مش بس بكلمته الراجل برعايته لبيته واسرته<br />:)"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/10121139069642274432"
comment_url = "https://mos3abof.blogspot.com/2007/04/artie.html?showComment=1175982360000#c6239648059743928259"

[[comments]]
author = "vision"
date = "2007-04-11T03:47:00+00:00"
text = "الحروف عباره عن خروم والخروم نقط بتتطبع بااااااارررررررررزه عالورق فظيعه فظيعه"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/08518080480364362981"
comment_url = "https://mos3abof.blogspot.com/2007/04/artie.html?showComment=1176263220000#c3653463974951575537"

[[comments]]
author = "Mohamed Moshrif"
date = "2007-04-25T08:15:00+00:00"
text = "أزال أحد مشرفي المدونة هذا التعليق."
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEinaOoEanUJtd9nj1ZAeuLM8jTJ6PSLWPrigGsbhi-_H56s_FuxAY8Odb39P66UE1RvOEm2-q9mIbBRAcdT-9JCfoa4wTA2U0BWcVIMiC6ZkP6wndy2O56yHZjVwu98rA/s113/418929_290190011036352_100001360671902_769264_471170163_n.jpg"
profile_url = "https://www.blogger.com/profile/04748476186265746697"
comment_url = "https://mos3abof.blogspot.com/2007/04/artie.html?showComment=1177488900000#c6582151927956951512"

[[comments]]
author = "مُصْعَب إِبْرَاهِيم"
date = "2007-04-25T09:05:00+00:00"
text = "Mohammed Moshref,<br /><br />As I told you before you are not welcomed here till you appologize to Dananeer about your rudness in a previous post you commented on...<br /><br />that's why i deleted your comment.."
is_author = true
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgODM4s6ekNMNbaTTY1KX0U5U6D_NmyJiuN60nsF_0DI--Js7olkUmXZpRkimU0I2gC8pwXBGOZKcTWjzCKgs6XJHV-A4s5wS7B14z2CPMUU-zrXc2WZZqVk9n76-iUZg/s220/mosab_profile.jpg"
profile_url = "https://www.blogger.com/profile/02204752041306044746"
comment_url = "https://mos3abof.blogspot.com/2007/04/artie.html?showComment=1177491900000#c3370170102279228334"

[[comments]]
author = "Mohamed Moshrif"
date = "2007-04-25T17:24:00+00:00"
text = "Which comment?!<br />And I really don't care for you to delete it, I just find this \"uniqueness\" in Egypt only, when someone tells people \"This OS is bad, please don't use it, I hate it\" and he's using it himself, nice principles really"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEinaOoEanUJtd9nj1ZAeuLM8jTJ6PSLWPrigGsbhi-_H56s_FuxAY8Odb39P66UE1RvOEm2-q9mIbBRAcdT-9JCfoa4wTA2U0BWcVIMiC6ZkP6wndy2O56yHZjVwu98rA/s113/418929_290190011036352_100001360671902_769264_471170163_n.jpg"
profile_url = "https://www.blogger.com/profile/04748476186265746697"
comment_url = "https://mos3abof.blogspot.com/2007/04/artie.html?showComment=1177521840000#c5342393494407000976"

[[comments]]
author = "مُصْعَب إِبْرَاهِيم"
date = "2007-04-25T18:05:00+00:00"
text = "Well Mohamed,<br />I really don't have time to spend with a kid in microsoft, and i don't care about what u think of me...<br /><br />You are NOT welcomed here anymore...<br /><br />by the way, this comment is written through SUSE Linux distro, version 10.1, and this is what i use at home..<br />but -unfortunately- at work they use windows."
is_author = true
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgODM4s6ekNMNbaTTY1KX0U5U6D_NmyJiuN60nsF_0DI--Js7olkUmXZpRkimU0I2gC8pwXBGOZKcTWjzCKgs6XJHV-A4s5wS7B14z2CPMUU-zrXc2WZZqVk9n76-iUZg/s220/mosab_profile.jpg"
profile_url = "https://www.blogger.com/profile/02204752041306044746"
comment_url = "https://mos3abof.blogspot.com/2007/04/artie.html?showComment=1177524300000#c6364470739912637491"

[[comments]]
author = "monasosh"
date = "2007-05-14T22:54:00+00:00"
text = "ايه ده!! انا اللاب توب بتاعى اسمه رينو مدعوء<br /><br />و الله دى فرصة سعيدة خالص<br />:)"
avatar_url = "http://4.bp.blogspot.com/_bJGfOyR2V7o/SfWt3eancKI/AAAAAAAAAhA/d9kL5H4BMmQ/S220/Dying+in+the+sun.png"
profile_url = "https://www.blogger.com/profile/12342888726720407970"
comment_url = "https://mos3abof.blogspot.com/2007/04/artie.html?showComment=1179183240000#c7707755393138724647"
