[[comments]]
author = "Salma Amer"
date = "2008-06-19T11:49:00+00:00"
text = "تقريبا فعلا اخدت ضربت قمر :)"
avatar_url = "http://farm2.static.flickr.com/1132/1365681113_f20faceeb5.jpg?v=0"
profile_url = "https://www.blogger.com/profile/08716194696950096714"
comment_url = "https://mos3abof.blogspot.com/2008/06/shortcuts.html?showComment=1213876140000#c4864463791503127826"

[[comments]]
author = "علي عبد المنعم"
date = "2008-06-19T12:03:00+00:00"
text = "جميلة أوي يا مصعب.. <br /><br />ورغم أنني راجل شورت كتاوي shortcuttawy إلا أني برضه بحب الطرق المستقيمة.. فربنا يجعلكم حياتكم كلها مستقيمة.. مع بعض shortcuts اللي تملا حياتكم سعادة إن شاء الله"
avatar_url = "http://www.20at.com/images/aly-abdel-moneam.jpg"
profile_url = "https://www.blogger.com/profile/13086694108023411873"
comment_url = "https://mos3abof.blogspot.com/2008/06/shortcuts.html?showComment=1213876980000#c1388921061431391617"

[[comments]]
author = "Anonymous"
date = "2008-06-19T12:13:00+00:00"
text = "هو صحيح انت من زمان بتقول كلام درر لكن المرة دي الحكمة واضحة قوي بكلامك <br />دا ياترى عوامل السن ولا الحب بدأ يصهر ما بداخلك فاخرج الحكمة ؟:)"
comment_url = "https://mos3abof.blogspot.com/2008/06/shortcuts.html?showComment=1213877580000#c2620965679638689115"

[[comments]]
author = "ام مليكة"
date = "2008-06-19T13:18:00+00:00"
text = "الحب الحب.......الشوق الشوق......اميرة اميرة"
avatar_url = "http://admins.20at.com/do3a2/bentbalad.jpg"
profile_url = "https://www.blogger.com/profile/17720828413632673574"
comment_url = "https://mos3abof.blogspot.com/2008/06/shortcuts.html?showComment=1213881480000#c6872650927073051910"

[[comments]]
author = "Amr"
date = "2008-06-19T14:06:00+00:00"
text = "وحياة بنتي آية هتتحسدوا يا جدعان <br /><br />ربنا يخليكم لبعض"
avatar_url = "http://www.arttoheart.ca/newimages/blueflrs.jpg"
profile_url = "https://www.blogger.com/profile/03741243192561256269"
comment_url = "https://mos3abof.blogspot.com/2008/06/shortcuts.html?showComment=1213884360000#c1238635902026069716"

[[comments]]
author = "Иεşċąfě &иεmö"
date = "2008-06-19T19:31:00+00:00"
text = "كل الي ئئدر ئئوله ربنا يخليكوا لبعض و يوفئكم يا رب"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/14635860789423949153"
comment_url = "https://mos3abof.blogspot.com/2008/06/shortcuts.html?showComment=1213903860000#c2831872614707359169"

[[comments]]
author = "اميرة هشام"
date = "2008-06-20T14:16:00+00:00"
text = "ربنا يخليكوا لبعض يااارب"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgzhHsKSw_63WMVYoxM1E7Gqma2VMArukpqj1084AIl6g7XJS2oC7MDNhOm01CT3678md0HSGIHEpoYkK2Er6QGarwKHFwUItjRFzsCMITsQJgcpqQmRiXJcZIY0MY9doU/s220/n1225417935_30237264_2188.jpg"
profile_url = "https://www.blogger.com/profile/16048503349469323361"
comment_url = "https://mos3abof.blogspot.com/2008/06/shortcuts.html?showComment=1213971360000#c2333524281870066618"

[[comments]]
author = "sakayar"
date = "2008-06-20T15:38:00+00:00"
text = "حلوة اوووي بجد الشورت كت<br />الطريق والمطب <br />والدايركت بدل الدائري<br />وأخيرا وبجد<br />مبرووووووك بجد فرحان انا اوووي<br />على الرغم من انها اول زيارة وانا كنت بشوفك عند احمد رفعت<br />لكن فرحان بجد كإني اعرفكم<br />بحب اوووي الاخبار الحلوة بتاعة الخطوبات والجوازات وكده وخصووووصا بين المدونين حتى لو كانوا يعرفوا بعض او عرفوا بعض بعد التدوين<br />بجد فرحااان ومبرووووك وخد بالك منكم وخدوا بالكم من بعض<br />رب يكتبلكم السعادة والحب والرضوان ولو مكونتش في ابوظبي كنت جيتلك جرررري باركتلك هههههه<br />ما تيجي انت وانا اباركلك برضه<br />رب يسعدكم مصعب واضح اوي من مدونتك أد إيه انت حد حلو ونضيييف<br />تحياتي"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiKMAqwX6Dxa10h0qMfytpXszZfDwA8g24LBCCfFpggjuqIk7UBKAZCZYGBdMozrc5Y3bZktcBl4LSJHlASqoIpLr2p6uNdCqFBxP7oCI_l5mVQSFgK0M4Yi6r9d-7IpA/s220/17112010845+%25283%25292.jpg"
profile_url = "https://www.blogger.com/profile/12307416483803962632"
comment_url = "https://mos3abof.blogspot.com/2008/06/shortcuts.html?showComment=1213976280000#c2764088259377742648"

[[comments]]
author = "Camellia Hussein"
date = "2008-06-23T11:50:00+00:00"
text = "the picture(malhash 7al)i`ll come again to comment at ur words<br /><br />(heya comment at walla comment on wlla eh?)"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg6KZuDgMk9CMt_vMft5N5xJJ0k5I3QTlPdcU-TQPDTAqe5E0uZpMiiL0V6jMKlMsbmPuUaXlDuyN0331exGVVvOkUtkGfdGgwbvWbDcfylIeb8mzTpbcywmnIF-RRV8Vc/s220/reflections.jpg"
profile_url = "https://www.blogger.com/profile/15735434869492317332"
comment_url = "https://mos3abof.blogspot.com/2008/06/shortcuts.html?showComment=1214221800000#c8348535065684808754"

[[comments]]
author = "آيــة"
date = "2008-06-23T16:03:00+00:00"
text = "انا وقفت قدام البوست شوية محترمين على فكرة ... و قريته كذا مرة ...<br /><br />اتفق معك تماما ... اننا نغتال براءتنا بمنتهى البراءة .... للأسف ...<br /><br />ربنا يباركلكم و يسعدكم ...<br /> و حلوة الشورتكت اوووووووي<br /><br />تحياتي :)"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgzEaJRCYA-SSanwraLdtEYkzEZkjETcQMB4sx-VFNA160NDSdRAzYDCG7SBTFCJ6v6_43x3JhlcsEwZXRf-2uz4kcAgWHsOcophQjBdHIt_Z69ULOm0iIAz4djYj3gNaY/s220/71759122.jpg"
profile_url = "https://www.blogger.com/profile/15592042263655359394"
comment_url = "https://mos3abof.blogspot.com/2008/06/shortcuts.html?showComment=1214236980000#c4617440678767275455"

[[comments]]
author = "Dina Samaha"
date = "2008-06-28T16:00:00+00:00"
text = "بجد Shortcuts جامدين جدا<br /><br />كل واحدة وقفت عندها..<br /><br />فعلا الطرق المستقمية هى الاصعب وبنضطر ان احنا نمشيها عشان متعودناش على الممهدة منها.. <br /><br />برائتنا زى ما انت قولت بنفقدها بمنتهى البراءة بس بنكسبها تانى فى لحظات بريئة غصب عننا مع ناس فى منتهى البراءة :)<br /><br />اميرتك هى العنوان اللى فى طريقك هاتوصله مهما كان طويل :)<br /><br />ربنا يخلى  حياتك دايما NEW <br /><br />(F)"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjyReb2q9ukC_TJk3HZGSvl7ezJGDzR7fmc9Xg79XPVZrKeUQPK52BIuqMLxKneTbBx4MbidRE8Xl6yaJ4URdfO9y33rGkaBPidVWZ08MgG1FduqZmZQxVbG8hr4uGgGf8/s220/horse_photo3.jpg"
profile_url = "https://www.blogger.com/profile/07959942602092011511"
comment_url = "https://mos3abof.blogspot.com/2008/06/shortcuts.html?showComment=1214668800000#c4016954546101328822"

[[comments]]
author = "إنسان <br /> Human"
date = "2008-06-28T23:53:00+00:00"
text = "الطرق المستقيمه دائماً أصعب ...أو ربما أسهل ......لأنها لاتترك شعوراً بالذنب عند من مازالت عندهم ضمير<br />...<br />الطرق الملتويه صعبه وسهله لمن لا توخذهم ضمائرهم"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEitsa6Fhz8BAJwKEp_SWJdLlFvznjYHETv3lk_f-om9DhNZO53ocE-_e-5vq9m86sARlmKSlf5fEOWtXy31uE1_2igkDJwFWicsh5ICa3SKUh06JfQfoR8g8Gr8TKKJCg/s220/just_a_moral_like_you_by_Alharbiseye.jpg"
profile_url = "https://www.blogger.com/profile/14309183286418898268"
comment_url = "https://mos3abof.blogspot.com/2008/06/shortcuts.html?showComment=1214697180000#c1933356261405024451"

[[comments]]
author = "MarwaAshraf"
date = "2008-07-04T19:53:00+00:00"
text = "تيرارارارارارارار<br /><br />ربنا يسعدكم كمان وكمان وعقبال كل العوازل <br /><br />:)"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/12117806503113618382"
comment_url = "https://mos3abof.blogspot.com/2008/06/shortcuts.html?showComment=1215201180000#c4133557152611512039"
