[[comments]]
author = "Mony The Angel"
date = "2007-08-22T21:55:00+00:00"
text = "kol sana w hwa tayeb<br />w wenta sa7bo :))"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjj4h6hlbKyUklJB5J_QeHmZidZ8mEHO-s5lWgxcP3qUEQSPg4AS0GkKHyrjWHC4Z5y2O3vBW2OY7WPf-cZ0PSVMC-DcEJ6cu6SRYKhpVq1jh6S9ve07RM4o8WgdU_8rxE/s220/mine...jpg"
profile_url = "https://www.blogger.com/profile/02273268851121458996"
comment_url = "https://mos3abof.blogspot.com/2007/08/blog-post_22.html?showComment=1187819700000#c4397886894464002252"

[[comments]]
author = "Anonymous"
date = "2007-08-23T06:20:00+00:00"
text = "عارف الصورة دي فكرتني بايه<br />أيام الكشافة و احنا طالع عينينا و رايحين رحلة خلوية<br />أو حتى مش خلوية <br />أو مش رحلة أصلا<br />المهم هن عينينا كانت بتطلع و خلاص<br /><br />أنا معرفش انت هتفتكرني و لالأ<br />عموما انا محمد فوزى"
comment_url = "https://mos3abof.blogspot.com/2007/08/blog-post_22.html?showComment=1187850000000#c2022431376478269138"

[[comments]]
author = "مُصْعَب إِبْرَاهِيم"
date = "2007-08-23T07:06:00+00:00"
text = "ربنا يكرمك يا رب يا منة<br /><br />محمد فوزي باشا، أو لنقل \"فوري\"<br />طويل العمر يطول عمره<br />فاكرك طبعا <br />وعرفتك على طول من التعليق اللي فات<br />بس أنت مش سايب ايميل أو بلوج أو حتى نمرة موبايل أقول لك عليها إني عرفتك<br />وأقول لك كمان وحشتني :)"
is_author = true
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgODM4s6ekNMNbaTTY1KX0U5U6D_NmyJiuN60nsF_0DI--Js7olkUmXZpRkimU0I2gC8pwXBGOZKcTWjzCKgs6XJHV-A4s5wS7B14z2CPMUU-zrXc2WZZqVk9n76-iUZg/s220/mosab_profile.jpg"
profile_url = "https://www.blogger.com/profile/02204752041306044746"
comment_url = "https://mos3abof.blogspot.com/2007/08/blog-post_22.html?showComment=1187852760000#c1764347894895880948"

[[comments]]
author = "أميرة من غير قصر ولا بستان.. ولا الشاطر حسن كمان"
date = "2007-08-23T15:47:00+00:00"
text = "كل سنه و انت طيب يا براء :) و عقبال مليون سنه <br /><br />و عقبالك انت كمان يا مصعب لما تكبر و تعجز و يبقى عندك 22 سنه بحالهم :):)"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEirdirzKebc0hcGC4MQ6kvVkx2q0MdxprJrl-jqSZ5l_jxE2bWsZVd-Pla_Zla1V4g0FjN5PUa4k3oTN0AO0cgFlRcbwr6XbP-7sqohbU_KGsAtNaDenb4eAJmqzrb0EGE/s220/blogpic5ke.jpg"
profile_url = "https://www.blogger.com/profile/16391848599214933906"
comment_url = "https://mos3abof.blogspot.com/2007/08/blog-post_22.html?showComment=1187884020000#c1109314733242207840"

[[comments]]
author = "Anonymous"
date = "2007-08-24T12:41:00+00:00"
text = "eng_emohamed@yahoo.com<br />عشان ميبقاش ليك حجة"
comment_url = "https://mos3abof.blogspot.com/2007/08/blog-post_22.html?showComment=1187959260000#c7547586537885964653"

[[comments]]
author = "حلم الحرية"
date = "2007-08-26T10:22:00+00:00"
text = "كل سنة وانتوا الاتنين صحاب اووووي<br /><br />كل سنة وانتوا الاتنين قريبين لبعض اووووووي<br /><br />كل سنة وانتوا مصعب وبراء<br /><br /><br />كل سنة وانت طيب يا براء وعقبال 524657436431 سنة<br /><br /><br />ربنا يجمعكم ببعض علي خير دايما"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj5134mBTHr7rVK3DSDgnRf5E_RugYPeh5cWZbeDoXKvwsHyL4tD1n_WEYXUeoJ4PMOSErPXCdUpGN274-0C5lbxDHtZQHsGch0ykrvpLnt52BWXdtpgWRytPSyMnw4MA/s1600/*"
profile_url = "https://www.blogger.com/profile/16809490468014096848"
comment_url = "https://mos3abof.blogspot.com/2007/08/blog-post_22.html?showComment=1188123720000#c3515744697802542893"

[[comments]]
author = "Anonymous"
date = "2007-08-26T15:59:00+00:00"
text = "جميل انه يكون في معاني بالرقة دي في حياتنا<br />تحياتي<br />وحبي"
comment_url = "https://mos3abof.blogspot.com/2007/08/blog-post_22.html?showComment=1188143940000#c2938808690551561963"

[[comments]]
author = "Oma"
date = "2007-08-26T21:00:00+00:00"
text = "كل سنه وانت طيب يابراء<br />وكل سنه وانتوا اصحاب ربنا مايحرمكو من بعض يارب"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgkyjSYWqXw4YBOpvP-96TyE2UNOj8WOswTKULdPzB70B6zrqDGJHhff9VHgxIxelyXO3EKU7YW8ajjqkmMwG9IO7yT-08dfl5BYELB9hvKRZscAn2UfctX1Oxivr_uIw/s220/dancing.jpg"
profile_url = "https://www.blogger.com/profile/00803900258553286221"
comment_url = "https://mos3abof.blogspot.com/2007/08/blog-post_22.html?showComment=1188162000000#c8389575010252427766"

[[comments]]
author = "معاذ الحوت"
date = "2007-08-27T00:20:00+00:00"
text = "كل سنة وانت طيب <br />أخوك في الله<br />معاذ الحوت<br />http://mo3z.blogspot.com/"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/05084033305908196632"
comment_url = "https://mos3abof.blogspot.com/2007/08/blog-post_22.html?showComment=1188174000000#c592479591375996156"
