[[comments]]
author = "Anonymous"
date = "2008-09-25T07:39:00+00:00"
text = "وااااااااااااااااااااو<br /><br /><br /><br />يا بختك يا سيدي <br />                               بيبو"
comment_url = "https://mos3abof.blogspot.com/2008/09/blog-post_25.html?showComment=1222328340000#c5450729154288467912"

[[comments]]
author = "Anonymous"
date = "2008-09-25T09:51:00+00:00"
text = "علي فكرة بقي دي اول مشاركة ليا بعد رجوعي للنت يعني انت اول مدونة اخشها بعد رجوعي<br /><br />كل سنة وهي بصحة وسلامة يارب<br /><br />ويارب السنة الجاية تكون في حضنك ومعاك ويكونوا معاكو بيبي صغنن <br /><br />كل سنة وانتي طيبة يا حبيبه مصعب"
comment_url = "https://mos3abof.blogspot.com/2008/09/blog-post_25.html?showComment=1222336260000#c9301043608388092"

[[comments]]
author = "Lens Geek"
date = "2008-09-25T10:39:00+00:00"
text = "ان شاء الله \"<br />while(1) {<br />  echo \" (f) * 10 ^ 9\";<br />}  \"<br /><br />حتتحقق soon<br /><br />كل سنه وانتي طيبة يا اميره .. وخلي بالك من مصعب plzzz"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhDH6cac8DhCu85r5fVw0KJDQyTSgnbUN_on5yZRrtKG44soaS5wrAZnDMZBnmYItm4PSgM5Be26Q5kswvv4w84fGE-zjxA4uFGBZW67q5kjJzKnPEAcvpMpdz-KsYUpg/s220/Ahmed2.gif"
profile_url = "https://www.blogger.com/profile/08391635125789451063"
comment_url = "https://mos3abof.blogspot.com/2008/09/blog-post_25.html?showComment=1222339140000#c3811930473257437569"

[[comments]]
author = "Salma Amer"
date = "2008-09-25T11:26:00+00:00"
text = "كل سنة وأنتم طيبين <br />وكل سنة والضي دايما بخير وبينكم :)"
avatar_url = "http://farm2.static.flickr.com/1132/1365681113_f20faceeb5.jpg?v=0"
profile_url = "https://www.blogger.com/profile/08716194696950096714"
comment_url = "https://mos3abof.blogspot.com/2008/09/blog-post_25.html?showComment=1222341960000#c8420134813144125580"

[[comments]]
author = "Lola"
date = "2008-09-25T11:33:00+00:00"
text = "كل سنة وانتو بخير وسلامة وسعاده وهنا وايامكم كلها حلوه..بجد ربنا يوقفكم.<br />وكمان يكون عام السعادة والنجااااااااااااح.<br />لولا"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjyK-WNQBo0pdHjdQC_LRknotU1JRUdn1vmcg3ldA0KfIdAUq2Xk5gZPnK5A9s-AwXzZCe-84HcV4WuGbUwJMdliWokuLVyWkNEq2YzSsubGvUzsi4ZuQsB3khAyFRsSns/s220/06b83166d2.png"
profile_url = "https://www.blogger.com/profile/04771539150205049403"
comment_url = "https://mos3abof.blogspot.com/2008/09/blog-post_25.html?showComment=1222342380000#c539800106282427124"

[[comments]]
author = "mohamed"
date = "2008-09-25T13:17:00+00:00"
text = "كل سنة والضي طيب :)"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiGfWhZiigMyqtTXuNGhGuZ7kCzQpSXHHBQFxacGHOFHEX81agRvyAHVvJNqxlHc4r65JdjhzBKu76zKEj0TXhBVJ-Rjmpfciyt9XBGHfdbSKJJfq-Rc3UeAgPD5FN-SK0/s220/DSCF29155.jpg"
profile_url = "https://www.blogger.com/profile/11099621052476900765"
comment_url = "https://mos3abof.blogspot.com/2008/09/blog-post_25.html?showComment=1222348620000#c1669143739972266310"

[[comments]]
author = "علي عبد المنعم"
date = "2008-09-25T13:59:00+00:00"
text = "كل سنة وأنتي طيبة يا أميرة وكل عام وأنتما إلى الله أقرب وعلى طاعته أدوم وإلى جنته أقرب، وعن معصيته أبعد.. <br /><br />وربنا ييسر لكما أمركما ويبارك لكما وعليكما ويجمع بينكما في خير"
avatar_url = "http://www.20at.com/images/aly-abdel-moneam.jpg"
profile_url = "https://www.blogger.com/profile/13086694108023411873"
comment_url = "https://mos3abof.blogspot.com/2008/09/blog-post_25.html?showComment=1222351140000#c1795211339786469089"

[[comments]]
author = "Omar"
date = "2008-09-25T14:40:00+00:00"
text = "ماشي يا ابن المحظوظه الله يسهلك"
avatar_url = "http://1.bp.blogspot.com/_uU6aLT1vZs0/Sha7cwlVWFI/AAAAAAAAAUI/2a29l9P2ke4/S220/Family+(1).jpg"
profile_url = "https://www.blogger.com/profile/10164006741123254135"
comment_url = "https://mos3abof.blogspot.com/2008/09/blog-post_25.html?showComment=1222353600000#c573794282063561417"

[[comments]]
author = "Anonymous"
date = "2008-09-26T11:23:00+00:00"
text = "اهئ اهئ اهئ<br /><br />دي دموع الفرحة<br /><br />oh God am so happy for youuuuuuuu<br /><br />عوصا ممكن تشيل الصورة لاني بجد خايفة عليكم<br /><br /><br />ربنا يحفظكم و يجمع ما بينكم على خير دايما يا رب<br /><br />و يجاوطكم بحب اللي بيحبوكم و يبعد عنكم كل شر"
comment_url = "https://mos3abof.blogspot.com/2008/09/blog-post_25.html?showComment=1222428180000#c7972936957507984763"

[[comments]]
author = "hana zain"
date = "2008-09-30T01:28:00+00:00"
text = "كل سنة و انت طيب يا عوصا<br /><br />ان شاء الله اشوفك انت و اميرة السنة الجاية في بيت العدل يا رب<br /><br />تحياتي"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/11151560686637318501"
comment_url = "https://mos3abof.blogspot.com/2008/09/blog-post_25.html?showComment=1222738080000#c5169186343212343931"

[[comments]]
author = "shabfa2re"
date = "2008-10-01T11:42:00+00:00"
text = "beeeeep beeeeeeeep<br />happy eiiiiiiiiiid"
avatar_url = "http://img54.imageshack.us/img54/4756/1606160816011604yy2.jpg"
profile_url = "https://www.blogger.com/profile/13162086599879303972"
comment_url = "https://mos3abof.blogspot.com/2008/09/blog-post_25.html?showComment=1222861320000#c2811401858643976577"

[[comments]]
author = "سواح النت"
date = "2008-10-02T13:19:00+00:00"
text = "هي تدوينات السهتنة والتسبيل دي<br />اللي مشوهة صورتنا"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/10382296582068681241"
comment_url = "https://mos3abof.blogspot.com/2008/09/blog-post_25.html?showComment=1222953540000#c1125990479184647218"
