[[comments]]
author = "علي عبد المنعم"
date = "2009-10-04T23:35:59.698000+00:00"
text = "جامدة التنين"
avatar_url = "http://www.20at.com/images/aly-abdel-moneam.jpg"
profile_url = "https://www.blogger.com/profile/13086694108023411873"
comment_url = "https://mos3abof.blogspot.com/2009/10/blog-post.html?showComment=1254699359698#c222362689667144204"

[[comments]]
author = "Anonymous"
date = "2009-10-05T04:06:33.435000+00:00"
text = "سلطة وحش السباغيتي الطائر :)<br /><br />http://en.wikipedia.org/wiki/Flying_Spaghetti_Monster"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/08637529907403415507"
comment_url = "https://mos3abof.blogspot.com/2009/10/blog-post.html?showComment=1254715593435#c5727627981219497745"

[[comments]]
author = "يوسف"
date = "2009-10-05T08:51:19.212000+00:00"
text = "مصعب باشا <br />واحشني جدا..<br /><br />بقي ياراجل حد يروح ياكل في فدراكرز! ده محل تعبان :]"
comment_url = "https://mos3abof.blogspot.com/2009/10/blog-post.html?showComment=1254732679212#c2108876859203805674"

[[comments]]
author = "TheSane"
date = "2009-10-05T12:11:58.639000+00:00"
text = "طيب وهو ينفع يعني الوحش يبقي من غير مناخير ولا ده عشان ميشمش ريحة السلطة :D<br />وفعلا فردركرز ده تعبان"
avatar_url = "//blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgKwTj0zQgdDd0xQOrF03RqMVoarSutn2qURyauLXgFJKVxbDE0CxZvBPwHxOZoqTAXnuZYAU1G7DsfBUFAv5qrjFiSB0RS1eGrSfDKcGjZxeU-JSeYk1JZcKOyRcWo9Q/s220/3G.jpg"
profile_url = "https://www.blogger.com/profile/07162269646851276658"
comment_url = "https://mos3abof.blogspot.com/2009/10/blog-post.html?showComment=1254744718639#c6928235111794864484"

[[comments]]
author = "Unknown"
date = "2009-10-05T12:14:15.324000+00:00"
text = "صحيح فكرتنى  , انا جعان ,لما اروح اشوف حاجه تتاكل"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/11317187924625926555"
comment_url = "https://mos3abof.blogspot.com/2009/10/blog-post.html?showComment=1254744855324#c7190371046601663247"

[[comments]]
author = "marwa salah"
date = "2009-10-05T13:36:49.565000+00:00"
text = "لا حلوة <br />مبدع من يومك"
avatar_url = "http://photos1.blogger.com/blogger/6631/3271/1600/water.1.jpg"
profile_url = "https://www.blogger.com/profile/01915363504191088852"
comment_url = "https://mos3abof.blogspot.com/2009/10/blog-post.html?showComment=1254749809565#c1240941196120580821"

[[comments]]
author = "Salma Amer"
date = "2009-10-05T19:00:52.166000+00:00"
text = "ما شاء الله شكلة يتاكل لوحدة مش عايز اي اكل جنبه <br />:)"
avatar_url = "http://farm2.static.flickr.com/1132/1365681113_f20faceeb5.jpg?v=0"
profile_url = "https://www.blogger.com/profile/08716194696950096714"
comment_url = "https://mos3abof.blogspot.com/2009/10/blog-post.html?showComment=1254769252166#c5793828314629253590"

[[comments]]
author = "Mohammad Al Mo'tassem"
date = "2009-10-07T18:34:18.021000+00:00"
text = "Gamda awy ya bos3abov<br /><br />Mohammad al Mo&#39;tassem"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/00404191220643356992"
comment_url = "https://mos3abof.blogspot.com/2009/10/blog-post.html?showComment=1254940458021#c7176627642330526589"
