name: Build and deploy my website

env:
  ZOLA_VERSION: "0.19.2"
  SOURCE_BRANCH: "main"
  TARGET_BRANCH: "gh-pages"
  BUILD_MODE: "github"

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install zola
        run: |
          set -x
          wget -O - \
             "https://github.com/getzola/zola/releases/download/v${ZOLA_VERSION}/zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz" \
          | sudo tar xzf - -C /usr/local/bin
      - name: Checkout the reposirtory code
        uses: actions/checkout@v4
      - name: Build the world
        run: make build
      - name: Publish website to github pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == format('refs/heads/{0}', env.SOURCE_BRANCH) }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
