name: Build and deploy my website

env:
  ZOLA_VERSION: "0.19.2"
  SOURCE_BRANCH: "main"
  TARGET_BRANCH: "gh-pages"
  BUILD_MODE: "github"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mos3abof/ubuntu-lualatex:latest
    steps:
      - name: Checkout the reposirtory code
        uses: actions/checkout@v4
      - name: Debugging info
        run: |
          id
          pwd
          which make
          which wget
          which lualatex
      # - name: Build the website and resume
      #   run: make all
      - name: Build the world
        run: make build
      - name: Publish website to github pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == format('refs/heads/{0}', env.SOURCE_BRANCH) }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
