[[comments]]
author = "أميرة من غير قصر ولا بستان.. ولا الشاطر حسن كمان"
date = "2007-12-12T22:56:00+00:00"
text = "ياااااااااااااااااه<br />و انا كمان يمكن فى لحظات كتيرة....نسيت<br />لكن اللى واثقة منه ...ان هو مش بينسانا"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEirdirzKebc0hcGC4MQ6kvVkx2q0MdxprJrl-jqSZ5l_jxE2bWsZVd-Pla_Zla1V4g0FjN5PUa4k3oTN0AO0cgFlRcbwr6XbP-7sqohbU_KGsAtNaDenb4eAJmqzrb0EGE/s220/blogpic5ke.jpg"
profile_url = "https://www.blogger.com/profile/16391848599214933906"
comment_url = "https://mos3abof.blogspot.com/2007/12/blog-post_13.html?showComment=1197500160000#c1564018557668740656"

[[comments]]
author = "العـابــــــــره"
date = "2007-12-12T22:59:00+00:00"
text = "ويسكت منه الكلام<br /><br />مشاعرها عميقه اوى<br />كلمات بسيطه واسلوب ساحر<br /> <br />تحياتى<br />    العـابره"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjirpnB1jlU7bWG0V6oQLFugE9LdCMmPYCneTsqfh2X7QHo46m-E-v1cdrCVcEqswMoAqKAfbCjRjc-xZIYckh1rq-QCi0KDc5B3O1mEHShrSAU5djGV2RpP_EXGiIOJA/s220/amanyyyyyy.jpg"
profile_url = "https://www.blogger.com/profile/02540503067719024339"
comment_url = "https://mos3abof.blogspot.com/2007/12/blog-post_13.html?showComment=1197500340000#c1877765976578206998"

[[comments]]
author = "محمد السيد..مش حاسكت"
date = "2007-12-12T23:02:00+00:00"
text = "إيه يا أخي ده ؟؟؟؟<br /><br />وقدر ينسي ؟؟ معقولة قدر ؟؟<br /><br />ينسي؟؟؟<br /><br /><br />خدني معاك جنيه ... ونفكر بعض ..."
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/15123433931771567833"
comment_url = "https://mos3abof.blogspot.com/2007/12/blog-post_13.html?showComment=1197500520000#c675044130627283400"

[[comments]]
author = "Omar"
date = "2007-12-12T23:07:00+00:00"
text = "انا مش هعلق وانت عارف ليه<br />):"
avatar_url = "http://1.bp.blogspot.com/_uU6aLT1vZs0/Sha7cwlVWFI/AAAAAAAAAUI/2a29l9P2ke4/S220/Family+(1).jpg"
profile_url = "https://www.blogger.com/profile/10164006741123254135"
comment_url = "https://mos3abof.blogspot.com/2007/12/blog-post_13.html?showComment=1197500820000#c138965150978395384"

[[comments]]
author = "Camellia Hussein"
date = "2007-12-12T23:35:00+00:00"
text = "يا الله....حلوة أوي وجاتني في وقتها اوي<br />حلو تعبير نور مضلم ده أد ما هو بسيط أد ما هومعبر<br />روح يا ابني الهي ينورلك طريقك بنور حقيقي دايما...."
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg6KZuDgMk9CMt_vMft5N5xJJ0k5I3QTlPdcU-TQPDTAqe5E0uZpMiiL0V6jMKlMsbmPuUaXlDuyN0331exGVVvOkUtkGfdGgwbvWbDcfylIeb8mzTpbcywmnIF-RRV8Vc/s220/reflections.jpg"
profile_url = "https://www.blogger.com/profile/15735434869492317332"
comment_url = "https://mos3abof.blogspot.com/2007/12/blog-post_13.html?showComment=1197502500000#c2315209991948127549"

[[comments]]
author = "Amr Magdi"
date = "2007-12-12T23:51:00+00:00"
text = "جميل تعبيرك يا مصعب..<br /><br />لي تعليق مفصل ، ربما أكتبه في تدوينة خاصة لاحقا<br /><br />ربنا يقويك"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhIrHm-CeixCZEck7AfZkhJYW0pOgawSdv6vj2cD3-TG4U96HKM4A-6BXcoIYlt-ZLjs1uEG_HRSjZt0K7QwKrQKHQSFbNUpIsk5aDHyXm6dRWs3mhidJPscLkMqlVk748/s1600/20130624_222606.jpg"
profile_url = "https://www.blogger.com/profile/14453415571936774156"
comment_url = "https://mos3abof.blogspot.com/2007/12/blog-post_13.html?showComment=1197503460000#c7472854521819692395"

[[comments]]
author = "marwa salah"
date = "2007-12-13T09:15:00+00:00"
text = "هو قريب أوووووى بس إحنا اللى محتاجين ناخد بالنا ونحطه فى بالنا <br /><br />على طول .. مش وقت ما نتزنق"
avatar_url = "http://photos1.blogger.com/blogger/6631/3271/1600/water.1.jpg"
profile_url = "https://www.blogger.com/profile/01915363504191088852"
comment_url = "https://mos3abof.blogspot.com/2007/12/blog-post_13.html?showComment=1197537300000#c4230748252194356214"

[[comments]]
author = "أحمد الدريني"
date = "2007-12-13T09:27:00+00:00"
text = "وماذا عن قربك انت؟"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/17300680267091030312"
comment_url = "https://mos3abof.blogspot.com/2007/12/blog-post_13.html?showComment=1197538020000#c6751965325632696642"

[[comments]]
author = "قضية عم أحمد    Ahmed Case"
date = "2007-12-13T09:32:00+00:00"
text = "لو نسيت تبقى انت مش جنبة أصل اللي جنبه عمره ما بينسى <br /><br />ده جنبه"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgV-wcarXLkgWhQQil5kwuYh3wp9AEWNEDcLSaQD2LN0vM_G4H9YJFgqa0XczHwll6yiqoYqdHkRIaOBrs7mUlUTV8btyQ-yKEFvsGrNIWlN99lkjHG8LD-zKscO0MMuVA/s220/DSC_7364.JPG"
profile_url = "https://www.blogger.com/profile/07000569434293484731"
comment_url = "https://mos3abof.blogspot.com/2007/12/blog-post_13.html?showComment=1197538320000#c2066310597327379141"

[[comments]]
author = "دوللي"
date = "2007-12-13T10:03:00+00:00"
text = "مينفعش تكون جمبه وتسرح في نور مضلم لانه وانت معاه مينفعش يكون في ضلمة هو النور <br />خليك حنبه بقلبك وعقلك وكل مافيك ."
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/06515904854255564384"
comment_url = "https://mos3abof.blogspot.com/2007/12/blog-post_13.html?showComment=1197540180000#c8193677155288497293"

[[comments]]
author = "Anonymous"
date = "2007-12-13T11:45:00+00:00"
text = "قصه قصيره ولكن معنيها كبيره وحلوه ده زي العظه وعبره للي بعد ونسى !!!  بس في واحد عمره مابنساه مهما بعد ومسيره يرجعه في يوم من الايام....."
comment_url = "https://mos3abof.blogspot.com/2007/12/blog-post_13.html?showComment=1197546300000#c7462659574821054382"

[[comments]]
author = "None"
date = "2007-12-13T16:00:00+00:00"
text = "بس سرحت في نور مضلم، ونسيت إنه هو النور.<br /><br />رائع بجد<br />وسلاااااااااااااااام"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi4Yu2bP8lKSq9t3v_U1xa-cd-ERVelzgHrDVr6BzjCxR8-nm2NgNMqYbMGu1MKGftLCIPDYksLr8kVRSAAcZRVFi__vwio52OOQ1WL1kTu952riMhmqtshHKQLwzWmETU/s1600/*"
profile_url = "https://www.blogger.com/profile/08542366881566698240"
comment_url = "https://mos3abof.blogspot.com/2007/12/blog-post_13.html?showComment=1197561600000#c6954785457830365440"

[[comments]]
author = "MarwaAshraf"
date = "2007-12-14T10:01:00+00:00"
text = "أنا جنبه والله..<br />أنا بس يمكن نسيت..<br /><br />يااااااه يا مصعب ، إنت جيت على الجرح أوي <br /><br />يارب نكون جنبة ونكون فاكرينة <br /><br />بجد البوست أثر فيه أوي<br /> <br />:)"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/12117806503113618382"
comment_url = "https://mos3abof.blogspot.com/2007/12/blog-post_13.html?showComment=1197626460000#c6189266920159270848"

[[comments]]
author = "Anonymous"
date = "2007-12-14T11:18:00+00:00"
text = "انا كمان نسيت بس كلي ثقة اني هرجع تاني وانه مش نسيني"
comment_url = "https://mos3abof.blogspot.com/2007/12/blog-post_13.html?showComment=1197631080000#c4416156791699689913"

[[comments]]
author = "leila"
date = "2007-12-14T22:38:00+00:00"
text = "3aref ana dayman ba7es ennak betkteb elly ana 7assah, ka2enny batkalem b lesanak :))) bgd mahma kont ha7awel a3bar 3an elly 7asah makontesh ha3raf zay manta edert<br /><br />\"ويسكت منه الكلام\"<br />yaaaaaaaaaaaaaaaaaaaaahya mos3ab bgd to7faaa :)))"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/07209122217966475424"
comment_url = "https://mos3abof.blogspot.com/2007/12/blog-post_13.html?showComment=1197671880000#c4562168971834682631"

[[comments]]
author = "Salma Amer"
date = "2007-12-15T13:08:00+00:00"
text = "نور مضلم <br />قريت الجملة دي و سرحت و قريتها تاني <br />انا حقيقي فهماك قوي قوي وحاسة بالكلام<br /><br />النور مش مضلم بس كتر الهم بيخليك تفقد الرؤية احيانا بس انت هنا وما بعتش ولا نسيت أنا متاكدة <br />وغمض وفتح حتلاقي نور رجع <br />تحياتي من القلب من جوة"
avatar_url = "http://farm2.static.flickr.com/1132/1365681113_f20faceeb5.jpg?v=0"
profile_url = "https://www.blogger.com/profile/08716194696950096714"
comment_url = "https://mos3abof.blogspot.com/2007/12/blog-post_13.html?showComment=1197724080000#c4224214955442568596"

[[comments]]
author = "Иεşċąfě &иεmö"
date = "2007-12-15T22:45:00+00:00"
text = "المشكله ان كلنا عرفين العلاجلكل مشاكلنا بس للأسف بننسي نأخده بس فعلا هو ربنا عمرة ما نسينا"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/14635860789423949153"
comment_url = "https://mos3abof.blogspot.com/2007/12/blog-post_13.html?showComment=1197758700000#c7523885741982335838"

[[comments]]
author = "Oma"
date = "2007-12-16T20:18:00+00:00"
text = "more7a awy ya mos3b...te7s enk 3ayz ttnhd kda w t2om te3'sl weshk :)<br />ranma ye3ena kolna"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgkyjSYWqXw4YBOpvP-96TyE2UNOj8WOswTKULdPzB70B6zrqDGJHhff9VHgxIxelyXO3EKU7YW8ajjqkmMwG9IO7yT-08dfl5BYELB9hvKRZscAn2UfctX1Oxivr_uIw/s220/dancing.jpg"
profile_url = "https://www.blogger.com/profile/00803900258553286221"
comment_url = "https://mos3abof.blogspot.com/2007/12/blog-post_13.html?showComment=1197836280000#c7594329045358621040"

[[comments]]
author = "عمر محمود"
date = "2007-12-17T03:57:00+00:00"
text = "عفواً<br />انا مش داخل اعمل إعلان والله<br />بس الوقت ضيق <br />فاضل على عرفة يوم<br />ناويين على إيه<br /><br />8 ذى الحجة"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgJtHKs88p1wHzsQ93Tc3kT_jleEXS0RxQZQAh2Kx403hAQuwv09INg-6JH-G0fhBKmiuKVJGvdeTFHnHOxk1_uX45lE0DDEb7jyEb3yhYEzZvvWd8NuBEw6dVEHUuQovQ/s220/Titel_01.gif"
profile_url = "https://www.blogger.com/profile/12161387737338769681"
comment_url = "https://mos3abof.blogspot.com/2007/12/blog-post_13.html?showComment=1197863820000#c4108847725051928443"

[[comments]]
author = "Anonymous"
date = "2007-12-17T11:52:00+00:00"
text = "اللهم انت ربي لا إله الا انت خلقتني وانا عبدك وانا على عهدك ووعدك ما استطعت اعوذ بك من شر ما صنعت وابوء لك بنعمتك علي وابوء بذنبي فاغفرلي فانه لا يغفر الذنوب الا انت"
comment_url = "https://mos3abof.blogspot.com/2007/12/blog-post_13.html?showComment=1197892320000#c7450859226099253726"

[[comments]]
author = "moodysalihamidzic"
date = "2007-12-18T17:56:00+00:00"
text = "كل سنة وانتم طيبين"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjw3-k6mbp2_HFYeMui6SVJpEsfGMYABElP-WuyAJsrbLQDEBO0j16bMmMybdf3KEXi-0H14hx6cNHzfa06s6QL0k_XNbyPSsZqGkDekeA350iefVq7Q7AXwo94chgQEQ/s220/mmmmmm.jpg"
profile_url = "https://www.blogger.com/profile/07854567324462397155"
comment_url = "https://mos3abof.blogspot.com/2007/12/blog-post_13.html?showComment=1198000560000#c2144785437029605341"
