[[comments]]
author = "dead man"
date = "2007-08-19T09:11:00+00:00"
text = "لأنهم ببساطة لا يفعلون.. فيظنون ان الكل لا يفعل"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgblVMh7Nlr7ton4EF6_WEIvx8uFAb-eyxAuL1LWv4FXTV92r6gCplvVR4alR4sN7zoTvIKKNYNdwspZiK_KxIj22bYHSiigq8zeWWpnNoyw8kdaUTj-R6MOh9v1vhBvNg/s220/wait.jpg"
profile_url = "https://www.blogger.com/profile/10592260848284665609"
comment_url = "https://mos3abof.blogspot.com/2007/08/blog-post_19.html?showComment=1187514660000#c1887388188174718688"

[[comments]]
author = "Salma Amer"
date = "2007-08-19T09:17:00+00:00"
text = "عادي جدا ان الواحد دلوقتي ينسى احيانا باحس اننا بنفضي الميموري بتاعتنا أول باول علشان نعرف نعيش ونلاحق الضغوط اللي حوالينا <br />واللي مش عايش في الضغط ده مش حيقدر يصدق ولا يهمك اهم حاجة ما تنساش اسمك بس"
avatar_url = "http://farm2.static.flickr.com/1132/1365681113_f20faceeb5.jpg?v=0"
profile_url = "https://www.blogger.com/profile/08716194696950096714"
comment_url = "https://mos3abof.blogspot.com/2007/08/blog-post_19.html?showComment=1187515020000#c3151074631162836770"

[[comments]]
author = "Иεşċąfě &иεmö"
date = "2007-08-19T09:22:00+00:00"
text = "للأسف ان احنا بئنا ننسي ابسط الاشياء حتي بئينا ننسي اسمي ئقرب الناس لينا مهيمكشي من حد :)"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/14635860789423949153"
comment_url = "https://mos3abof.blogspot.com/2007/08/blog-post_19.html?showComment=1187515320000#c4523220866239381213"

[[comments]]
author = "شيرين"
date = "2007-08-19T09:27:00+00:00"
text = "أولا لأنه ببساطة ميعرفكش.. لأن من يعرفك يا مصاعيبو أكيد شافك في يوم وانت ناسي تاكل أو تشرب :) <br /><br />Geek ba2a :)<br /><br />ثانيا لأن العالم اللي بتعلمنا الكدب دي معندهمش دماغ تخليهم يفهموا الناس اللي قدامهم ويستوعبوهم.. ولا يهمك يا مصاعيبو.. أحنا فاهمينك <br />;)"
avatar_url = "http://photos-279.ll.facebook.com/photos-ll-sctm/v99/129/13/717256279/n717256279_214552_3758.jpg"
profile_url = "https://www.blogger.com/profile/08718885335246773468"
comment_url = "https://mos3abof.blogspot.com/2007/08/blog-post_19.html?showComment=1187515620000#c7393904895246616273"

[[comments]]
author = "قضية عم أحمد    Ahmed Case"
date = "2007-08-19T09:34:00+00:00"
text = "لاننا بنحب كتير نصدق الكذب . <br /><br />صدق رسول الله (اذا كذبكم تركمتوه واذا صدقكم ضربتموه )"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgV-wcarXLkgWhQQil5kwuYh3wp9AEWNEDcLSaQD2LN0vM_G4H9YJFgqa0XczHwll6yiqoYqdHkRIaOBrs7mUlUTV8btyQ-yKEFvsGrNIWlN99lkjHG8LD-zKscO0MMuVA/s220/DSC_7364.JPG"
profile_url = "https://www.blogger.com/profile/07000569434293484731"
comment_url = "https://mos3abof.blogspot.com/2007/08/blog-post_19.html?showComment=1187516040000#c5298767710612820203"

[[comments]]
author = "العـابــــــــره"
date = "2007-08-19T09:44:00+00:00"
text = "انت عارف المشكله ايه<br />ان الناس ما بتصدقش غير اللى عايزه تصدقه<br /><br />يمكن لو كنت سكت ومقولتش ايوه <br />مكانش حد قال عليك كذاب<br />لكن المشكله انك صادق فى وسط عالم وخدين ع الكذب<br /> <br />تحياتى"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjirpnB1jlU7bWG0V6oQLFugE9LdCMmPYCneTsqfh2X7QHo46m-E-v1cdrCVcEqswMoAqKAfbCjRjc-xZIYckh1rq-QCi0KDc5B3O1mEHShrSAU5djGV2RpP_EXGiIOJA/s220/amanyyyyyy.jpg"
profile_url = "https://www.blogger.com/profile/02540503067719024339"
comment_url = "https://mos3abof.blogspot.com/2007/08/blog-post_19.html?showComment=1187516640000#c1108341327803644148"

[[comments]]
author = "لو كنت أعلم"
date = "2007-08-19T10:25:00+00:00"
text = "لإنهم حتى لو مصدقين <br />ما ينفعش يقولولك ده<br /><br />لإننا كلنا بنتربى على ثقافة الخوف<br /><br />وإن الكبير دائماً على حق<br /><br />إلى أن<br />.........<br />.............<br />..................<br />نكتشف الحقيقة<br /><br />فتضيع معها كل الثقة<br />وكل المثل العليا<br /><br />لنحيا ثقافة التسفيه لكل عظيم<br />والتشكيك بكل نقي<br /><br />يعني كان هيجرى إيه لو كنت ما نسيتش تحل الواجب؟!؟<br />ههههههههههههه"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/04311149989087603827"
comment_url = "https://mos3abof.blogspot.com/2007/08/blog-post_19.html?showComment=1187519100000#c4111400593669732565"

[[comments]]
author = "weswes"
date = "2007-08-19T11:06:00+00:00"
text = "عارف يا مصعب زمان كنت برضوا بقول زيك كده <br />وكنت بتغاض اوى من الكلمه نسيت تشرب وتاكل والحاجات دى<br />اول ما اشتغلت فى المدرسه<br />لقتنى بقولها تلقائى<br />رغم انى مش مقتنعه بيها<br />وعلشان كده مش بيقيت اقولها خالص<br />فتقريبا هو الموضوع مش كونهم مصدقين ولا لا<br />الموضوع انهم ورثوا الجمله وبيرددوها<br />ولك تحياتى"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiw4snw0O4r8EYHQhiu7PCP3YXbjsOVmNj5zsVG2NmG_iJW8qfvdrvDKQVVXpYEQyxkgnLEal7LDhjHT9wSDmHEaztJc2mql6BgND38sUt9YXFFoG0Id5pU9R8WI3ItEKo/s220/IMG_0034.JPG"
profile_url = "https://www.blogger.com/profile/04810150175952124524"
comment_url = "https://mos3abof.blogspot.com/2007/08/blog-post_19.html?showComment=1187521560000#c201803873725366237"

[[comments]]
author = "دوللي"
date = "2007-08-19T13:08:00+00:00"
text = "كلنا بننسى دا حتى الزهيمر دلوقتي بقى منتشر اوي"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/06515904854255564384"
comment_url = "https://mos3abof.blogspot.com/2007/08/blog-post_19.html?showComment=1187528880000#c5606389351098246764"

[[comments]]
author = "أحمد الدريني"
date = "2007-08-19T13:38:00+00:00"
text = "وانا ساعات بفتكر"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/17300680267091030312"
comment_url = "https://mos3abof.blogspot.com/2007/08/blog-post_19.html?showComment=1187530680000#c4946515459507368911"

[[comments]]
author = "MariumaZ"
date = "2007-08-19T16:42:00+00:00"
text = "أنا عن نفسي بنسى آكل وبنسى أشرب <br />وده لأن الواحد فعلاً بينسى .... الشخص اللي بيسألك ده نفسه بينسى<br /><br />المدرس اللي بيسألك نسيت كتاب المدرسة ليه؟<br />هو نفسه بينساه وساعات بينسى الحصة اللي عليه .. مش بنشوف ده بيحصل كتير<br />النتيجة النهائية يا مصعب إن الكبير في السن اللي المفروض إن بينسى أكتر كل ما يكبر بيعاقب الصغير لأنه بينسى ... مع إن دي طبيعة بشرية ..<br />من الطبيعي جداً إن أنسى كشكول الفصل بس المهم ما أنساش أصلي على سبيل المثال<br />في حاجات تانية كتير كانت في دماغي أكتبهالك .. بس نسيت<br />زي ما بنسى آكل وأشرب وأدخل الحمام<br />وعلى فكرة ... مش بكدب"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg9giUV2iCTwwtfQoUxjZXLMjO4Scq0iKCUdYMCgmovIiMOde9B26aqPY_6wwiZy8PHqssu8sQSZDgaBjnhd_kQL0aeEev2mUQs1l-tOOUp6mUNQV2JilPBktEhrS_AHqU/s220/IMG_0084.jpg"
profile_url = "https://www.blogger.com/profile/12796121153780883763"
comment_url = "https://mos3abof.blogspot.com/2007/08/blog-post_19.html?showComment=1187541720000#c8351226035337304271"

[[comments]]
author = "menSh"
date = "2007-08-20T10:05:00+00:00"
text = "تلك القصة المكررة في حياة كل منا بلا استثناء ما زالت تتكرر بشكل روتيني في حياة كل منا.. إساءة فهم الأخرين وتعريضك لمواقف سيئة دون قصد منك أو حتى دون قصد من آخرين... مأساة متكررة في حياة كل منا"
avatar_url = "http://photos1.blogger.com/blogger/4938/2050/1600/am.jpg"
profile_url = "https://www.blogger.com/profile/14221308254991337821"
comment_url = "https://mos3abof.blogspot.com/2007/08/blog-post_19.html?showComment=1187604300000#c5809292894321120732"

[[comments]]
author = "Anonymous"
date = "2007-08-20T15:03:00+00:00"
text = "والله انا دائما بانسي<br />و احيانا اتذكر<br />كنت امقت النسيان <br />ولكن الان<br />احمد الله علي نعمة النسيان<br />:)"
comment_url = "https://mos3abof.blogspot.com/2007/08/blog-post_19.html?showComment=1187622180000#c5108088107718055229"

[[comments]]
author = "Anonymous"
date = "2007-08-21T10:26:00+00:00"
text = "لأن لنت نسيت تقولهم ان انت مش كداب<br />بص يا سيدي<br />سيبك من موضوع الكدب ده بقى<br />انا باختصار عايز افكرك انا مين<br />معرفش الإسم زحده هيكفيك و لا لأ<br />محمد فوزى<br />لو مش كفاية قوللى و انا هقوللك انا مين<br />ماشي<br />و متنساش تعمل الواجب تاني يا كابتن"
comment_url = "https://mos3abof.blogspot.com/2007/08/blog-post_19.html?showComment=1187691960000#c8244327891013657198"

[[comments]]
author = "Anonymous"
date = "2007-08-21T11:34:00+00:00"
text = "لازم حد يدرس موضوع الزهايمر ده وازاى بقة يصيب الصغيرين والشباب دلوقتي اكتر من العواجيز"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/13176205141056724221"
comment_url = "https://mos3abof.blogspot.com/2007/08/blog-post_19.html?showComment=1187696040000#c4131181971658342961"

[[comments]]
author = "أميرة من غير قصر ولا بستان.. ولا الشاطر حسن كمان"
date = "2007-08-21T17:32:00+00:00"
text = "الوحيده اللى انا فعلا متأكده انك بتعملها على طول هى <br />نسيت تاكل :):)"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEirdirzKebc0hcGC4MQ6kvVkx2q0MdxprJrl-jqSZ5l_jxE2bWsZVd-Pla_Zla1V4g0FjN5PUa4k3oTN0AO0cgFlRcbwr6XbP-7sqohbU_KGsAtNaDenb4eAJmqzrb0EGE/s220/blogpic5ke.jpg"
profile_url = "https://www.blogger.com/profile/16391848599214933906"
comment_url = "https://mos3abof.blogspot.com/2007/08/blog-post_19.html?showComment=1187717520000#c3329575523587767621"

[[comments]]
author = "Mony The Angel"
date = "2007-08-21T21:19:00+00:00"
text = ":)<br />7aseet be 7aneen lelmadrasa walawenny mal7e2tsh ab3ed 3anha :))<br /><br />bas ana kont barod a2ool<br />\"galla man la yasho\"<br />e3'lato f kalam rabbona b2a lol"
avatar_url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjj4h6hlbKyUklJB5J_QeHmZidZ8mEHO-s5lWgxcP3qUEQSPg4AS0GkKHyrjWHC4Z5y2O3vBW2OY7WPf-cZ0PSVMC-DcEJ6cu6SRYKhpVq1jh6S9ve07RM4o8WgdU_8rxE/s220/mine...jpg"
profile_url = "https://www.blogger.com/profile/02273268851121458996"
comment_url = "https://mos3abof.blogspot.com/2007/08/blog-post_19.html?showComment=1187731140000#c8809364376855863701"

[[comments]]
author = "شقاوة شعب"
date = "2007-08-27T07:23:00+00:00"
text = "الواحد بينسى ياكل و ينسى يشرب لما يكون مشغوووول قوى<br />اكيد حضرتك كنت طفل عبقرى وكنت مشغوووول قوى فى العاب وتركيباتك عشان كدةكنت بتنسى الاكل والشرب<br /><br />صح ولا اييييه"
avatar_url = "http://bp3.blogger.com/_pgBiB1O7SK4/R2-dh6kbggI/AAAAAAAAAFY/R2-CBw8BtMY/S220/1+copy.gif"
profile_url = "https://www.blogger.com/profile/17816660759609053478"
comment_url = "https://mos3abof.blogspot.com/2007/08/blog-post_19.html?showComment=1188199380000#c6244559822644689958"

[[comments]]
author = "vision"
date = "2007-08-31T17:41:00+00:00"
text = "موضوع السمندوتشات ده صحيح يا منه... والنسيان يا جماعه ده <br /><br />انا لما كنت بتسأل السؤال ده كن الفصل كولو بيرد بالنيابه عنى لأنى مكنتش بجيب سندوتشات ولا كولمان الميه وكنت باخد من بنات الفصل ففى شهود  على ده وبالتالى بنسى او بتناسى اجيب الأكل يبأه هجيب الحاجات دى يااااااا جماعه كل دى شكليات"
avatar_url = "https://img1.blogblog.com/img/b16-rounded.gif"
profile_url = "https://www.blogger.com/profile/08518080480364362981"
comment_url = "https://mos3abof.blogspot.com/2007/08/blog-post_19.html?showComment=1188582060000#c6924510544790131060"
